import { createClient } from 'jsr:@supabase/supabase-js@2';

import { corsHeaders } from '../_shared/cors.ts';
import { refreshAccessToken } from '../_shared/spotify.ts';

const TRACKS_PER_ARTIST = 3;

async function spotifyFetch(path: string, accessToken: string, init?: RequestInit) {
  const res = await fetch(`https://api.spotify.com/v1${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
      ...init?.headers,
    },
  });
  if (!res.ok) throw new Error(`Spotify API ${path} failed (${res.status}): ${await res.text()}`);
  return res.json();
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('Missing Authorization header');

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser(authHeader.replace('Bearer ', ''));
    if (userError || !user) throw new Error('Not authenticated');

    const { festivalId, editionId } = await req.json();
    if (!festivalId || !editionId) throw new Error('Missing festivalId or editionId');

    const { data: connection, error: connError } = await supabase
      .from('spotify_connections')
      .select('*')
      .eq('user_id', user.id)
      .single();
    if (connError || !connection) throw new Error('Spotify not connected');

    let accessToken = connection.access_token as string;
    if (new Date(connection.expires_at) <= new Date()) {
      const refreshed = await refreshAccessToken(connection.refresh_token);
      accessToken = refreshed.access_token;
      await supabase
        .from('spotify_connections')
        .update({
          access_token: refreshed.access_token,
          refresh_token: refreshed.refresh_token,
          expires_at: new Date(Date.now() + refreshed.expires_in * 1000).toISOString(),
        })
        .eq('user_id', user.id);
    }

    const [{ data: festival, error: festivalError }, { data: edition, error: editionError }] =
      await Promise.all([
        supabase.from('festivals').select('name').eq('id', festivalId).single(),
        supabase.from('festival_editions').select('year').eq('id', editionId).single(),
      ]);
    if (festivalError || !festival) throw new Error('Festival not found');
    if (editionError || !edition) throw new Error('Edition not found');

    const { data: lineup, error: lineupError } = await supabase
      .from('edition_artists')
      .select('order_index, artists(id, name, spotify_artist_id)')
      .eq('edition_id', editionId)
      .order('order_index', { ascending: true });
    if (lineupError) throw lineupError;
    if (!lineup || lineup.length === 0) throw new Error('No lineup published for this edition');

    const trackUris: string[] = [];
    const skippedArtists: string[] = [];
    let matchedArtists = 0;

    for (const entry of lineup as unknown as {
      order_index: number;
      artists: { id: string; name: string; spotify_artist_id: string | null };
    }[]) {
      const artist = entry.artists;
      let spotifyArtistId = artist.spotify_artist_id;

      if (!spotifyArtistId) {
        const search = await spotifyFetch(
          `/search?type=artist&limit=1&q=${encodeURIComponent(artist.name)}`,
          accessToken,
        );
        spotifyArtistId = search.artists?.items?.[0]?.id ?? null;
        if (spotifyArtistId) {
          await supabase.from('artists').update({ spotify_artist_id: spotifyArtistId }).eq('id', artist.id);
        }
      }

      if (!spotifyArtistId) {
        skippedArtists.push(artist.name);
        continue;
      }

      matchedArtists += 1;
      const topTracks = await spotifyFetch(`/artists/${spotifyArtistId}/top-tracks?market=US`, accessToken);
      for (const track of (topTracks.tracks ?? []).slice(0, TRACKS_PER_ARTIST)) {
        trackUris.push(track.uri);
      }
    }

    if (trackUris.length === 0) throw new Error('No tracks matched on Spotify for this lineup');

    const playlistName = `${festival.name} ${edition.year}`;
    const playlist = await spotifyFetch(`/users/${connection.spotify_user_id}/playlists`, accessToken, {
      method: 'POST',
      body: JSON.stringify({
        name: playlistName,
        description: `Generated by Festiq from the ${festival.name} ${edition.year} lineup.`,
        public: false,
      }),
    });

    // Spotify caps "add items" at 100 URIs per request.
    for (let i = 0; i < trackUris.length; i += 100) {
      await spotifyFetch(`/playlists/${playlist.id}/tracks`, accessToken, {
        method: 'POST',
        body: JSON.stringify({ uris: trackUris.slice(i, i + 100) }),
      });
    }

    await supabase.from('playlists_generated').insert({
      user_id: user.id,
      festival_id: festivalId,
      edition_id: editionId,
      spotify_playlist_id: playlist.id,
      playlist_name: playlistName,
      total_artists: lineup.length,
      matched_artists: matchedArtists,
      total_tracks: trackUris.length,
      status: 'created',
    });

    return new Response(
      JSON.stringify({
        playlistUrl: playlist.external_urls.spotify,
        playlistId: playlist.id,
        totalArtists: lineup.length,
        matchedArtists,
        totalTracks: trackUris.length,
        skippedArtists,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  } catch (error) {
    return new Response(JSON.stringify({ error: (error as Error).message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
