-- ============================================================
-- 2026 lineups for DJ Mag Top 100 festivals with a confirmed
-- edition (see djmag_editions_2026.sql). Headliner / notable-artist
-- subsets sourced from official announcements, RA, DJ Mag, EDM.com.
-- Festivals with a confirmed edition but no lineup announced yet as
-- of seed time are intentionally left without lineup rows.
--
-- spotify_artist_id left null on purpose (see lineups_2026.sql):
-- generate-playlist resolves + caches it via live Spotify search.
-- ============================================================

insert into public.artists (name)
select v.name
from (values
  ('070 Shake'),
  ('4am Kru'),
  ('7SKIES'),
  ('999999999'),
  ('A.M.C'),
  ('AC Slater'),
  ('ANNA'),
  ('AREA ØNE'),
  ('ARMNHMR'),
  ('ARTBAT'),
  ('ATLiens'),
  ('AYYBO'),
  ('AZYR'),
  ('Above & Beyond'),
  ('Adam Beyer'),
  ('Adam Curtain'),
  ('Adam Ten'),
  ('Addison Rae'),
  ('Adiel'),
  ('Adventure Club'),
  ('Afrojack'),
  ('Agents Of Time'),
  ('Agoria'),
  ('Al Wootton'),
  ('Alabama Shakes'),
  ('Alan Fitzpatrick'),
  ('Alan Walker'),
  ('Alarico'),
  ('Alesso'),
  ('Alex G'),
  ('Alison Wonderland'),
  ('Alle Farben'),
  ('Alok'),
  ('Aly & Fila'),
  ('Amaliah'),
  ('Ame'),
  ('Amelie Lens'),
  ('Andrew Rayel'),
  ('Andromedik'),
  ('Andy C'),
  ('Anetha'),
  ('Angerfist'),
  ('Anna Reusch'),
  ('Annie Mac'),
  ('Anyma'),
  ('Apashe'),
  ('Aquenta'),
  ('Arcando'),
  ('Argy'),
  ('Armand Van Helden'),
  ('Armin van Buuren'),
  ('Ashnikko'),
  ('Aster'),
  ('Aurora Halal'),
  ('Autopski'),
  ('Avalon Emerson'),
  ('Axwell'),
  ('Azzecca'),
  ('BLOND:ISH'),
  ('BUNT.'),
  ('Bad Gyal'),
  ('Badger'),
  ('Baiyia'),
  ('Barry Can''t Swim'),
  ('Batu'),
  ('Bebe Rexha'),
  ('Bedouin'),
  ('Beltran'),
  ('Ben Hemsley'),
  ('Ben Klock'),
  ('Ben Nicky'),
  ('Ben Sims'),
  ('Ben Techy'),
  ('Ben UFO'),
  ('Benny Benassi'),
  ('Benny Rodrigues'),
  ('Big Special'),
  ('Biianco'),
  ('Black Tiger Sex Machine'),
  ('Blanke'),
  ('Blastoyz'),
  ('Blawan'),
  ('Blood Orange'),
  ('Bone Thugs-N-Harmony'),
  ('Boris Brejcha'),
  ('Bou'),
  ('Boys Noize'),
  ('Bradley Zero'),
  ('Breakage'),
  ('Brunello'),
  ('Brutalismus 3000'),
  ('Bunney'),
  ('Burr Oak'),
  ('CCL'),
  ('Cabaret Voltaire'),
  ('Caiiro'),
  ('Calibre'),
  ('Call Super'),
  ('Calvin Harris'),
  ('CamelPhat'),
  ('Candice'),
  ('Cardia'),
  ('Caribou'),
  ('Carl Cox'),
  ('Carl Craig'),
  ('Carla Schmitt'),
  ('Cascada'),
  ('Cassian'),
  ('Channel One'),
  ('Channel Tres'),
  ('Charli XCX'),
  ('Charlotte de Witte'),
  ('Chase & Status'),
  ('Chelina Manuhutu'),
  ('Chez Damier'),
  ('Chloé Caillet'),
  ('Chris Avantgarde'),
  ('Chris Lake'),
  ('Chris Liebing'),
  ('Chris Lorenzo'),
  ('Chris Stussy'),
  ('Chromeo'),
  ('Cinthie'),
  ('Clara Cuvé'),
  ('Clementine Douglas'),
  ('Clipse'),
  ('Cloonee'),
  ('Commodo'),
  ('Confidence Man'),
  ('Cormac'),
  ('Cosmic Gate'),
  ('Crankdat'),
  ('Crazy P'),
  ('Culture Shock'),
  ('D-Block & S-te-Fan'),
  ('DARKSIDE'),
  ('DEATHPACT'),
  ('DJ EZ'),
  ('DJ Gigola'),
  ('DJ Koze'),
  ('DJ Nobu'),
  ('DJ Rush'),
  ('DJ Seinfeld'),
  ('DJ Snake'),
  ('DJ Sprinkles'),
  ('DJ Storm'),
  ('DJ Tennis'),
  ('DMX Krew'),
  ('DVS1'),
  ('Da Hool'),
  ('Da Tweekaz'),
  ('Dabin'),
  ('Dan Shake'),
  ('Danny Brown'),
  ('Danny Howard'),
  ('Daphni'),
  ('Daria Kolosova'),
  ('Dave Harvey'),
  ('David Guetta'),
  ('Dax J'),
  ('De Capo'),
  ('De La Soul'),
  ('Decius'),
  ('Deep Dish'),
  ('Dennis Ferrer'),
  ('Derrick Carter'),
  ('Devault'),
  ('Dimension'),
  ('Dimitri Vegas'),
  ('Dimitri Vegas & Like Mike'),
  ('Diplo'),
  ('Disclosure'),
  ('Dixon'),
  ('Doja Cat'),
  ('Dom Dolla'),
  ('Dombresky'),
  ('Don Diablo'),
  ('Donna Leake'),
  ('Dr. Peacock'),
  ('DubVision'),
  ('Dubfire'),
  ('East End Dubs'),
  ('Eats Everything'),
  ('Eileen'),
  ('Elder Island'),
  ('Eliza Rose'),
  ('Ellen Allien'),
  ('Empire of the Sun'),
  ('Enrico Sangiuliano'),
  ('Entasia'),
  ('Eptic'),
  ('Eric Prydz'),
  ('Eris Drew'),
  ('Ethel Cain'),
  ('Eve'),
  ('Evian Christ'),
  ('Ewan McVicar'),
  ('Excision'),
  ('Ezra Collective'),
  ('FISHER'),
  ('FJAAK'),
  ('Fabio'),
  ('Faithless'),
  ('Fallon'),
  ('Fantasm'),
  ('Fatboy Slim'),
  ('Fatima Hajji'),
  ('Fcukers'),
  ('Felipe Gordon'),
  ('Felix Jähn'),
  ('Felix Kroecher'),
  ('Felix Kröcher'),
  ('Ferry Corsten'),
  ('Fish56Octagon'),
  ('Floating Points'),
  ('Floorplan'),
  ('Flux Pavilion'),
  ('Flying Lotus'),
  ('Folamour'),
  ('Formula'),
  ('Four Tet'),
  ('Fox Stevenson'),
  ('Frank Walker'),
  ('Franky Wah'),
  ('Funk Tribu'),
  ('GRiZ'),
  ('GZA'),
  ('Galantis'),
  ('Gareth Emery'),
  ('Gennaro'),
  ('Gerd Janson'),
  ('Ghost Rider'),
  ('Girls Don''t Sync'),
  ('Giuseppe Ottaviani'),
  ('GloRilla'),
  ('Goldie'),
  ('Gorgon City'),
  ('Gorillaz'),
  ('Gourski'),
  ('Grace Sands'),
  ('Green Velvet'),
  ('Gregor Tresher'),
  ('Groove Armada'),
  ('Grooverider'),
  ('Gryffin'),
  ('HBz'),
  ('HI-LO'),
  ('Hannah Laing'),
  ('Hardwell'),
  ('Harry Romero'),
  ('Hector Oaks'),
  ('Hedex'),
  ('Helena Hauff'),
  ('High Vis'),
  ('Holly Lester'),
  ('Holy Priest'),
  ('Honey Dijon'),
  ('HoneyLuv'),
  ('Horse Meat Disco'),
  ('Horsemeat Disco'),
  ('Hot 8 Brass Band'),
  ('Hot Since 82'),
  ('Hugel'),
  ('Hugo Martinez'),
  ('Hybrid Minds'),
  ('Héctor Oaks'),
  ('I Hate Models'),
  ('ISOxo'),
  ('Illenium'),
  ('Indira Paganotto'),
  ('Interplanetary Criminal'),
  ('JENNIE'),
  ('James Holden'),
  ('James Hype'),
  ('Jamie Jones'),
  ('Jan Blomqvist'),
  ('Japanese Breakfast'),
  ('Jax Jones'),
  ('Jayda G'),
  ('Jeff Mills'),
  ('Jennifer Loveless'),
  ('Jessica Audiffred'),
  ('Job Jobse'),
  ('John Digweed'),
  ('John Newman'),
  ('John O''Callaghan'),
  ('John Summit'),
  ('John Talabot'),
  ('Jon Hopkins'),
  ('Jonas Blue'),
  ('Joris Voorn'),
  ('Joseph Capriati'),
  ('Josh Baker'),
  ('Josh Caffe'),
  ('Joy Orbison'),
  ('Juan Atkins'),
  ('Judge Jules'),
  ('K Motionz'),
  ('KAAZE'),
  ('KETTAMA'),
  ('KI/KI'),
  ('KSHMR'),
  ('Kai Wachi'),
  ('Kali Uchis'),
  ('Karah'),
  ('Kasablanca'),
  ('Kaskade'),
  ('Kelela'),
  ('Kelis'),
  ('Kesha'),
  ('Kevin Saunderson'),
  ('Kevin de Vries'),
  ('Kid Cudi'),
  ('Kid Fonque'),
  ('Kimonos'),
  ('Kirollus'),
  ('KlangKuenstler'),
  ('Klofama'),
  ('Kneecap'),
  ('Knife Party'),
  ('Knock2'),
  ('Kobosil'),
  ('Kode9'),
  ('Korolova'),
  ('Koven'),
  ('Krewella'),
  ('Krystal Klear'),
  ('Kuko'),
  ('Kyau & Albert'),
  ('Kygo'),
  ('Kyle Watson'),
  ('Kölsch'),
  ('LF SYSTEM'),
  ('LP'),
  ('La Chica'),
  ('Laura van Dam'),
  ('Laurent Garnier'),
  ('Layla Benitez'),
  ('Layton Giordani'),
  ('Len Faki'),
  ('Level Up'),
  ('Levity'),
  ('Licaxxx'),
  ('Lil Uzi Vert'),
  ('Lil'' Kim'),
  ('Lil'' Louis'),
  ('Lilly Palmer'),
  ('Little Simz'),
  ('Lola Haro'),
  ('Lorde'),
  ('Loren'),
  ('Lost Frequencies'),
  ('Lottie'),
  ('Loud Luxury'),
  ('Louie Vega'),
  ('Low Steppa'),
  ('Loxy'),
  ('Luke Una'),
  ('Luude'),
  ('MARRØN'),
  ('MJ Cole'),
  ('MK'),
  ('MORTEN'),
  ('MPH'),
  ('MRAK'),
  ('Maceo Plex'),
  ('Maddix'),
  ('Madness'),
  ('Major Lazer'),
  ('Mala'),
  ('Mall Grab'),
  ('Mallrat'),
  ('Manda Moor'),
  ('Marcel'),
  ('Marcel Dettmann'),
  ('Marco Carola'),
  ('Marco Faraone'),
  ('Maribou State'),
  ('Marie Davidson'),
  ('Markus Schulz'),
  ('Marlon Hoffstadt'),
  ('Marsh'),
  ('Marshmello'),
  ('Martin Garrix'),
  ('Massano'),
  ('Massive Attack'),
  ('Masters at Work'),
  ('Mathame'),
  ('Mathew Jonson'),
  ('Matisse & Sadko'),
  ('Matroda'),
  ('Mau P'),
  ('Mauro Picotto'),
  ('Maverick Sabre'),
  ('Max Dean'),
  ('Meduza'),
  ('Mefjus'),
  ('Men I Trust'),
  ('Merow'),
  ('Mesto'),
  ('Michael Bibi'),
  ('Michael Mayer'),
  ('Midland'),
  ('Mind Against'),
  ('Mischluft'),
  ('Miss K8'),
  ('Miss Monique'),
  ('Mochakk'),
  ('Moderat'),
  ('Modest Mouse'),
  ('Monolink'),
  ('Moodymann'),
  ('Morgan Seatree'),
  ('Mosimann'),
  ('Mozey'),
  ('Muzz'),
  ('My Bloody Valentine'),
  ('N2N'),
  ('NERVO'),
  ('NOTD'),
  ('Neelix'),
  ('Neptunica'),
  ('Netsky'),
  ('Nia Archives'),
  ('Nic Fanciulli'),
  ('Nick León'),
  ('Nicky Romero'),
  ('Nico Moreno'),
  ('Nicolas Cuer'),
  ('Nicole Moudaber'),
  ('Nifra'),
  ('Nina Kraviz'),
  ('Noah Kahan'),
  ('Nome'),
  ('Nothing But Thieves'),
  ('Novah'),
  ('OK Williams'),
  ('OMIKI'),
  ('OXIA'),
  ('Objekt'),
  ('Obskur'),
  ('Octo Octa'),
  ('Oden & Fatzo'),
  ('Oliver Heldens'),
  ('Olivia Dean'),
  ('Olivia Rodrigo'),
  ('Om Unit'),
  ('Or:la'),
  ('Orbital'),
  ('Oscar L'),
  ('Overmono'),
  ('PAN-POT'),
  ('PLK'),
  ('Paco Osuna'),
  ('Pale Jay'),
  ('Palms Trax'),
  ('Parcels'),
  ('Partiboi69'),
  ('Patrick Mason'),
  ('Patrick Topping'),
  ('Paul Kalkbrenner'),
  ('Paul Woolford'),
  ('Paul van Dyk'),
  ('Pawsa'),
  ('Peach'),
  ('Pegassi'),
  ('Peggy Gou'),
  ('Pendulum'),
  ('Peverelist'),
  ('PlastiK Funk'),
  ('Porter Robinson'),
  ('Powder'),
  ('Prada2000'),
  ('Primate'),
  ('Princess Nokia'),
  ('Prospa'),
  ('Prosumer'),
  ('Purple Disco Machine'),
  ('R3HAB'),
  ('RAMØN'),
  ('RL Grime'),
  ('RONI'),
  ('Radioactive Man'),
  ('Ran-D'),
  ('Rank 1'),
  ('Raxon'),
  ('Ray Volpe'),
  ('Rebelion'),
  ('Rebolledo'),
  ('Rebuke'),
  ('Reptant'),
  ('Rhadoo'),
  ('Ricardo Villalobos'),
  ('Richie Hawtin'),
  ('Riot'),
  ('Robert Hood'),
  ('Robin Schulz'),
  ('Role Model'),
  ('Roman Flugel'),
  ('Rossi'),
  ('Rossi.'),
  ('Rudimental'),
  ('Ryan Elliott'),
  ('Ryan Key'),
  ('RÜFÜS DU SOL'),
  ('Röyksopp'),
  ('Rødhåd'),
  ('SG Lewis'),
  ('SHDW'),
  ('SHERELLE'),
  ('SIDEPIECE'),
  ('SLANDER'),
  ('SOFI TUKKER'),
  ('SVDDEN DEATH'),
  ('Sabai'),
  ('Salome'),
  ('Salvatore Ganacci'),
  ('Sam Binga'),
  ('Sam Divine'),
  ('Sama'' Abdulhadi'),
  ('Sammy Virji'),
  ('Sampa the Great'),
  ('Sampha'),
  ('Santøs'),
  ('Sara Landry'),
  ('Sasha'),
  ('Satoshi Tomiie'),
  ('Schiller'),
  ('Scissor Sisters'),
  ('Scooter'),
  ('Sebastian Ingrosso'),
  ('Serafina'),
  ('Seth Troxler'),
  ('Seven Lions'),
  ('Shaggy'),
  ('Shanti Celeste'),
  ('Shimza'),
  ('Shy FX'),
  ('Shygirl'),
  ('Sidney Charles'),
  ('Silva Bumpa'),
  ('Simo Cell'),
  ('Sirup'),
  ('Sistek'),
  ('Skepta'),
  ('Skindred'),
  ('Skream'),
  ('Skrillex'),
  ('Sleaford Mods'),
  ('Sleep D'),
  ('Slushii'),
  ('Solardo'),
  ('Solomun'),
  ('Sombr'),
  ('Sonja Moonear'),
  ('Sonny Fodera'),
  ('Soulwax'),
  ('Sound Rush'),
  ('Soundrush'),
  ('Space Laces'),
  ('Spacey Jane'),
  ('Spartaque'),
  ('Speedy J'),
  ('Stacey Pullen'),
  ('Stephan Bodzin'),
  ('Steve Angello'),
  ('Steve Aoki'),
  ('Stoog3s'),
  ('Sub Focus'),
  ('Subtronics'),
  ('Sully'),
  ('Sultan + Shepard'),
  ('Supermayer'),
  ('Sven Väth'),
  ('Swedish House Mafia'),
  ('Syreeta'),
  ('TSHA'),
  ('TV Rock'),
  ('Tara Brooks'),
  ('Tate McRae'),
  ('Teddy Swims'),
  ('Temper Trap'),
  ('The Avalanches'),
  ('The Blessed Madonna'),
  ('The Bug'),
  ('The Chainsmokers'),
  ('The Cure'),
  ('The Dare'),
  ('The Ghost'),
  ('The Martinez Brothers'),
  ('The Neighbourhood'),
  ('The Prodigy'),
  ('The Smashing Pumpkins'),
  ('The Strokes'),
  ('The xx'),
  ('Third Party'),
  ('Tiga'),
  ('Tim Reaper'),
  ('Timmy Trumpet'),
  ('Tiësto'),
  ('Toby Romeo'),
  ('Todd Terry'),
  ('Tokischa'),
  ('Toni Varga'),
  ('Topic'),
  ('Torren Foot'),
  ('Tricky'),
  ('Trikk'),
  ('Turnstile'),
  ('Twenty One Pilots'),
  ('Underground Resistance'),
  ('Underworld'),
  ('VTSS'),
  ('Venga'),
  ('Vengaboys'),
  ('Vieze Asbak'),
  ('Vince Staples'),
  ('Vini Vici'),
  ('Vintage Culture'),
  ('Vladimir Cauchemar'),
  ('WORSHIP'),
  ('Wade'),
  ('Westbam'),
  ('Wet Leg'),
  ('Wilkinson'),
  ('William Black'),
  ('Wooli'),
  ('Xzibit'),
  ('YUNGBLUD'),
  ('Yazmin Lacey'),
  ('Yellow Claw'),
  ('Yotto'),
  ('Young Franco'),
  ('Yousuke Yukimatsu'),
  ('Zack Fox'),
  ('Zara Larsson'),
  ('Zedd'),
  ('Zomboy'),
  ('aespa'),
  ('beabadoobee'),
  ('deadmau5'),
  ('fumi'),
  ('horsegiirL'),
  ('livwutang'),
  ('Âme')
) as v(name)
where not exists (
  select 1 from public.artists a where lower(a.name) = lower(v.name)
);

-- ---------- lineups per 2026 edition ----------
with lineup(slug, artist_name, order_index) as (
  values
    -- kappa-futurfestival
    ('kappa-futurfestival', 'Sven Väth', 0), ('kappa-futurfestival', 'Charlotte de Witte', 1),
    ('kappa-futurfestival', 'Amelie Lens', 2), ('kappa-futurfestival', 'Armin van Buuren', 3),
    ('kappa-futurfestival', 'Peggy Gou', 4), ('kappa-futurfestival', 'Richie Hawtin', 5),
    ('kappa-futurfestival', 'Carl Craig', 6), ('kappa-futurfestival', 'Solomun', 7),
    ('kappa-futurfestival', 'Four Tet', 8), ('kappa-futurfestival', 'Maceo Plex', 9),
    ('kappa-futurfestival', 'Boys Noize', 10), ('kappa-futurfestival', 'Diplo', 11),
    ('kappa-futurfestival', 'Disclosure', 12), ('kappa-futurfestival', 'Enrico Sangiuliano', 13),
    ('kappa-futurfestival', 'Jamie Jones', 14), ('kappa-futurfestival', 'Joseph Capriati', 15),
    ('kappa-futurfestival', 'Seth Troxler', 16), ('kappa-futurfestival', 'Michael Bibi', 17),
    ('kappa-futurfestival', 'DJ Rush', 18), ('kappa-futurfestival', 'Avalon Emerson', 19),
    ('kappa-futurfestival', 'Sebastian Ingrosso', 20),
    -- electric-love
    ('electric-love', 'Swedish House Mafia', 0), ('electric-love', 'Armin van Buuren', 1),
    ('electric-love', 'Paul Kalkbrenner', 2), ('electric-love', 'Dimitri Vegas', 3),
    ('electric-love', 'KSHMR', 4), ('electric-love', 'John Newman', 5),
    ('electric-love', 'Hugel', 6), ('electric-love', 'BUNT.', 7),
    ('electric-love', 'KlangKuenstler', 8), ('electric-love', 'Holy Priest', 9),
    -- parklife
    ('parklife', 'Calvin Harris', 0), ('parklife', 'Skepta', 1),
    ('parklife', 'Sammy Virji', 2), ('parklife', 'Zara Larsson', 3),
    ('parklife', 'Rudimental', 4), ('parklife', 'Chris Stussy', 5),
    ('parklife', 'Josh Baker', 6), ('parklife', 'Nia Archives', 7),
    ('parklife', 'Shy FX', 8), ('parklife', 'Andy C', 9),
    ('parklife', 'Rossi.', 10), ('parklife', 'Bou', 11),
    ('parklife', 'Silva Bumpa', 12), ('parklife', 'AZYR', 13),
    ('parklife', 'Prospa', 14), ('parklife', 'Morgan Seatree', 15),
    ('parklife', 'Clementine Douglas', 16), ('parklife', 'Chloé Caillet', 17),
    ('parklife', 'K Motionz', 18), ('parklife', 'Mozey', 19),
    -- time-warp
    ('time-warp', 'Richie Hawtin', 0), ('time-warp', 'Sven Väth', 1),
    ('time-warp', 'Adam Beyer', 2), ('time-warp', 'Amelie Lens', 3),
    ('time-warp', 'Kobosil', 4), ('time-warp', 'Nina Kraviz', 5),
    ('time-warp', 'Marcel Dettmann', 6), ('time-warp', 'Sara Landry', 7),
    ('time-warp', 'Honey Dijon', 8), ('time-warp', 'Laurent Garnier', 9),
    -- edc-orlando
    ('edc-orlando', 'Martin Garrix', 0), ('edc-orlando', 'Alesso', 1),
    ('edc-orlando', 'Hardwell', 2), ('edc-orlando', 'David Guetta', 3),
    ('edc-orlando', 'Kaskade', 4), ('edc-orlando', 'Afrojack', 5),
    ('edc-orlando', 'Alison Wonderland', 6), ('edc-orlando', 'Adventure Club', 7),
    ('edc-orlando', 'SLANDER', 8), ('edc-orlando', 'Alan Walker', 9),
    ('edc-orlando', 'I Hate Models', 10), ('edc-orlando', 'KlangKuenstler', 11),
    ('edc-orlando', 'Jessica Audiffred', 12), ('edc-orlando', 'Level Up', 13),
    ('edc-orlando', 'Levity', 14), ('edc-orlando', 'Ray Volpe', 15),
    ('edc-orlando', 'Wooli', 16), ('edc-orlando', 'Brunello', 17),
    ('edc-orlando', 'Devault', 18), ('edc-orlando', 'Marlon Hoffstadt', 19),
    -- dekmantel
    ('dekmantel', 'Underground Resistance', 0), ('dekmantel', 'Ricardo Villalobos', 1),
    ('dekmantel', 'DARKSIDE', 2), ('dekmantel', 'SHERELLE', 3),
    ('dekmantel', 'DVS1', 4), ('dekmantel', 'Eris Drew', 5),
    ('dekmantel', 'Octo Octa', 6), ('dekmantel', 'Jeff Mills', 7),
    ('dekmantel', 'DJ Sprinkles', 8), ('dekmantel', 'Sampha', 9),
    ('dekmantel', 'James Holden', 10),
    -- primer
    ('primer', 'Axwell', 0), ('primer', 'MRAK', 1),
    ('primer', 'Adam Ten', 2), ('primer', 'Armand Van Helden', 3),
    ('primer', 'Bedouin', 4), ('primer', 'OMIKI', 5),
    ('primer', 'Stephan Bodzin', 6),
    -- boomtown
    ('boomtown', 'Kneecap', 0), ('boomtown', 'Scissor Sisters', 1),
    ('boomtown', 'Madness', 2), ('boomtown', 'Skrillex', 3),
    ('boomtown', 'Four Tet', 4), ('boomtown', 'Faithless', 5),
    ('boomtown', 'Scooter', 6), ('boomtown', 'Shaggy', 7),
    ('boomtown', 'Ashnikko', 8), ('boomtown', 'Eve', 9),
    ('boomtown', 'SHERELLE', 10), ('boomtown', 'Groove Armada', 11),
    ('boomtown', 'Floating Points', 12), ('boomtown', 'Shy FX', 13),
    ('boomtown', 'Princess Nokia', 14), ('boomtown', 'Sampa the Great', 15),
    ('boomtown', 'High Vis', 16), ('boomtown', 'Big Special', 17),
    ('boomtown', 'Vengaboys', 18), ('boomtown', 'Skindred', 19),
    -- amf
    ('amf', 'David Guetta', 0), ('amf', 'Armin van Buuren', 1),
    ('amf', 'Afrojack', 2), ('amf', 'Amelie Lens', 3),
    ('amf', 'ARTBAT', 4), ('amf', 'D-Block & S-te-Fan', 5),
    ('amf', 'Korolova', 6), ('amf', 'Marlon Hoffstadt', 7),
    -- terminal-v
    ('terminal-v', 'Robert Hood', 0), ('terminal-v', 'Sara Landry', 1),
    ('terminal-v', 'I Hate Models', 2), ('terminal-v', 'Clara Cuvé', 3),
    ('terminal-v', 'Ben Hemsley', 4), ('terminal-v', 'Novah', 5),
    ('terminal-v', 'Santøs', 6), ('terminal-v', 'Patrick Mason', 7),
    ('terminal-v', 'Vieze Asbak', 8), ('terminal-v', 'East End Dubs', 9),
    ('terminal-v', 'Patrick Topping', 10), ('terminal-v', 'Mall Grab', 11),
    ('terminal-v', 'Morgan Seatree', 12), ('terminal-v', 'Klofama', 13),
    -- world-club-dome
    ('world-club-dome', 'DJ Snake', 0), ('world-club-dome', 'Steve Aoki', 1),
    ('world-club-dome', 'Alok', 2), ('world-club-dome', 'Eric Prydz', 3),
    ('world-club-dome', 'Robin Schulz', 4), ('world-club-dome', 'Bebe Rexha', 5),
    ('world-club-dome', 'Steve Angello', 6), ('world-club-dome', 'James Hype', 7),
    ('world-club-dome', 'Miss Monique', 8), ('world-club-dome', 'Ran-D', 9),
    ('world-club-dome', 'Felix Kröcher', 10), ('world-club-dome', 'Gregor Tresher', 11),
    ('world-club-dome', 'Topic', 12), ('world-club-dome', 'Toby Romeo', 13),
    ('world-club-dome', 'Holy Priest', 14), ('world-club-dome', 'Neptunica', 15),
    -- world-dj-festival
    ('world-dj-festival', 'Armin van Buuren', 0), ('world-dj-festival', 'Marshmello', 1),
    ('world-dj-festival', 'Amelie Lens', 2), ('world-dj-festival', 'SLANDER', 3),
    ('world-dj-festival', 'Zedd', 4), ('world-dj-festival', 'Eric Prydz', 5),
    ('world-dj-festival', 'I Hate Models', 6), ('world-dj-festival', 'Loud Luxury', 7),
    ('world-dj-festival', 'D-Block & S-te-Fan', 8), ('world-dj-festival', 'Rebelion', 9),
    ('world-dj-festival', 'Sound Rush', 10),
    -- monegros
    ('monegros', 'Richie Hawtin', 0), ('monegros', 'Amelie Lens', 1),
    ('monegros', 'Ben Klock', 2), ('monegros', 'Marco Faraone', 3),
    ('monegros', 'Seth Troxler', 4), ('monegros', 'Paco Osuna', 5),
    ('monegros', 'Joseph Capriati', 6), ('monegros', 'Len Faki', 7),
    ('monegros', 'Manda Moor', 8), ('monegros', 'Chelina Manuhutu', 9),
    ('monegros', 'Toni Varga', 10),
    -- neopop
    ('neopop', 'Jeff Mills', 0), ('neopop', 'Goldie', 1),
    ('neopop', 'Nina Kraviz', 2), ('neopop', 'Dubfire', 3),
    ('neopop', 'Enrico Sangiuliano', 4), ('neopop', 'Joseph Capriati', 5),
    ('neopop', 'Ben Klock', 6), ('neopop', 'Ben Sims', 7),
    ('neopop', 'DJ Nobu', 8), ('neopop', 'Helena Hauff', 9),
    ('neopop', 'Ellen Allien', 10), ('neopop', 'Héctor Oaks', 11),
    ('neopop', 'Indira Paganotto', 12), ('neopop', 'Mathew Jonson', 13),
    ('neopop', 'Supermayer', 14), ('neopop', 'Adiel', 15),
    ('neopop', 'Cardia', 16), ('neopop', 'Daria Kolosova', 17),
    ('neopop', 'DJ Storm', 18),
    -- siam-songkran
    ('siam-songkran', 'Martin Garrix', 0), ('siam-songkran', 'John Summit', 1),
    ('siam-songkran', 'Marshmello', 2), ('siam-songkran', 'Alok', 3),
    ('siam-songkran', 'ARTBAT', 4), ('siam-songkran', 'R3HAB', 5),
    ('siam-songkran', 'Agents Of Time', 6), ('siam-songkran', 'Ben Nicky', 7),
    ('siam-songkran', 'Vini Vici', 8), ('siam-songkran', 'Gorgon City', 9),
    ('siam-songkran', 'Afrojack', 10), ('siam-songkran', 'Layton Giordani', 11),
    ('siam-songkran', 'Andromedik', 12), ('siam-songkran', 'Arcando', 13),
    ('siam-songkran', 'Slushii', 14), ('siam-songkran', 'Third Party', 15),
    ('siam-songkran', 'DubVision', 16), ('siam-songkran', 'Matisse & Sadko', 17),
    -- primavera-sound
    ('primavera-sound', 'Doja Cat', 0), ('primavera-sound', 'Massive Attack', 1),
    ('primavera-sound', 'Bad Gyal', 2), ('primavera-sound', 'The Cure', 3),
    ('primavera-sound', 'Addison Rae', 4), ('primavera-sound', 'Skrillex', 5),
    ('primavera-sound', 'The xx', 6), ('primavera-sound', 'Gorillaz', 7),
    ('primavera-sound', 'My Bloody Valentine', 8), ('primavera-sound', 'Olivia Rodrigo', 9),
    ('primavera-sound', 'Peggy Gou', 10), ('primavera-sound', 'Alex G', 11),
    ('primavera-sound', 'Little Simz', 12), ('primavera-sound', 'Wet Leg', 13),
    -- s2o-bangkok
    ('s2o-bangkok', 'Alan Walker', 0), ('s2o-bangkok', 'Steve Aoki', 1),
    ('s2o-bangkok', 'Zedd', 2), ('s2o-bangkok', 'Kygo', 3),
    ('s2o-bangkok', 'Lost Frequencies', 4), ('s2o-bangkok', 'Don Diablo', 5),
    ('s2o-bangkok', 'Dabin', 6), ('s2o-bangkok', 'Gryffin', 7),
    ('s2o-bangkok', 'I Hate Models', 8), ('s2o-bangkok', 'AC Slater', 9),
    ('s2o-bangkok', 'SIDEPIECE', 10), ('s2o-bangkok', 'Ray Volpe', 11),
    ('s2o-bangkok', 'Frank Walker', 12), ('s2o-bangkok', 'William Black', 13),
    ('s2o-bangkok', 'Da Tweekaz', 14),
    -- movement
    ('movement', 'Sara Landry', 0), ('movement', 'Dom Dolla', 1),
    ('movement', 'Carl Cox', 2), ('movement', 'The Dare', 3),
    ('movement', 'Boys Noize', 4), ('movement', 'Juan Atkins', 5),
    ('movement', 'Barry Can''t Swim', 6), ('movement', 'Richie Hawtin', 7),
    ('movement', 'Green Velvet', 8),
    -- panorama
    ('panorama', 'Solomun', 0), ('panorama', 'Peggy Gou', 1),
    ('panorama', 'Mochakk', 2), ('panorama', 'Pawsa', 3),
    ('panorama', 'Mau P', 4), ('panorama', 'BLOND:ISH', 5),
    ('panorama', 'Vintage Culture', 6), ('panorama', 'Jamie Jones', 7),
    ('panorama', 'Seth Troxler', 8), ('panorama', 'The Martinez Brothers', 9),
    ('panorama', 'Josh Baker', 10), ('panorama', 'Yousuke Yukimatsu', 11),
    ('panorama', 'Gennaro', 12), ('panorama', 'Kimonos', 13),
    -- dgtl
    ('dgtl', 'Joy Orbison', 0), ('dgtl', 'Jayda G', 1),
    ('dgtl', 'CamelPhat', 2), ('dgtl', 'Ame', 3),
    ('dgtl', 'DJ Tennis', 4), ('dgtl', 'Armand Van Helden', 5),
    ('dgtl', 'Benny Rodrigues', 6), ('dgtl', 'Eileen', 7),
    ('dgtl', 'Kirollus', 8), ('dgtl', 'Trikk', 9),
    ('dgtl', 'Hector Oaks', 10), ('dgtl', 'Salome', 11),
    ('dgtl', 'FJAAK', 12), ('dgtl', 'Gerd Janson', 13),
    -- sonar
    ('sonar', 'The Prodigy', 0), ('sonar', 'Charlotte de Witte', 1),
    ('sonar', 'Amelie Lens', 2), ('sonar', 'Skepta', 3),
    ('sonar', 'Kelis', 4), ('sonar', 'Boys Noize', 5),
    ('sonar', 'KETTAMA', 6), ('sonar', 'Funk Tribu', 7),
    ('sonar', 'DJ Gigola', 8), ('sonar', 'Joy Orbison', 9),
    ('sonar', 'Nia Archives', 10), ('sonar', 'Chris Stussy', 11),
    ('sonar', 'Gerd Janson', 12), ('sonar', 'Marcel Dettmann', 13),
    ('sonar', 'MK', 14), ('sonar', 'TSHA', 15),
    ('sonar', 'Cabaret Voltaire', 16),
    -- nibirii
    ('nibirii', 'KlangKuenstler', 0), ('nibirii', 'Vini Vici', 1),
    ('nibirii', 'I Hate Models', 2), ('nibirii', 'Dax J', 3),
    ('nibirii', 'Dimension', 4), ('nibirii', 'Wilkinson', 5),
    ('nibirii', 'Marlon Hoffstadt', 6), ('nibirii', 'Hannah Laing', 7),
    ('nibirii', 'Netsky', 8), ('nibirii', 'Muzz', 9),
    ('nibirii', 'Fox Stevenson', 10), ('nibirii', 'Felix Kroecher', 11),
    ('nibirii', 'Anna Reusch', 12),
    -- veld
    ('veld', 'Above & Beyond', 0), ('veld', 'Armin van Buuren', 1),
    ('veld', 'FISHER', 2), ('veld', 'Illenium', 3),
    ('veld', 'deadmau5', 4), ('veld', 'Kaskade', 5),
    ('veld', 'Charlotte de Witte', 6), ('veld', 'ARTBAT', 7),
    ('veld', 'Galantis', 8), ('veld', 'James Hype', 9),
    ('veld', 'Lost Frequencies', 10), ('veld', 'Subtronics', 11),
    ('veld', 'SLANDER', 12), ('veld', 'Black Tiger Sex Machine', 13),
    ('veld', 'Crankdat', 14), ('veld', 'Ray Volpe', 15),
    -- arc
    ('arc', 'Anyma', 0), ('arc', 'Underworld', 1),
    ('arc', 'Brutalismus 3000', 2), ('arc', 'Chase & Status', 3),
    ('arc', 'Chris Stussy', 4), ('arc', 'Honey Dijon', 5),
    ('arc', 'Derrick Carter', 6), ('arc', 'Sara Landry', 7),
    ('arc', 'Mau P', 8), ('arc', 'Mochakk', 9),
    ('arc', 'Carl Craig', 10), ('arc', 'Moodymann', 11),
    ('arc', 'Stacey Pullen', 12), ('arc', 'The Blessed Madonna', 13),
    ('arc', 'Green Velvet', 14), ('arc', 'Josh Baker', 15),
    ('arc', 'Nicole Moudaber', 16), ('arc', 'Paco Osuna', 17),
    ('arc', 'Dubfire', 18),
    -- tomorrowland-winter
    ('tomorrowland-winter', 'Charlotte de Witte', 0), ('tomorrowland-winter', 'Steve Aoki', 1),
    ('tomorrowland-winter', 'Steve Angello', 2), ('tomorrowland-winter', 'Lost Frequencies', 3),
    ('tomorrowland-winter', 'Dimitri Vegas', 4), ('tomorrowland-winter', 'Alok', 5),
    ('tomorrowland-winter', 'Netsky', 6), ('tomorrowland-winter', 'Agents Of Time', 7),
    ('tomorrowland-winter', 'Mind Against', 8), ('tomorrowland-winter', 'MORTEN', 9),
    ('tomorrowland-winter', 'Nina Kraviz', 10), ('tomorrowland-winter', 'NERVO', 11),
    ('tomorrowland-winter', 'RONI', 12), ('tomorrowland-winter', 'Agoria', 13),
    ('tomorrowland-winter', 'Oden & Fatzo', 14), ('tomorrowland-winter', 'Dombresky', 15),
    -- houghton
    ('houghton', 'Ben UFO', 0), ('houghton', 'Ricardo Villalobos', 1),
    ('houghton', 'Peach', 2), ('houghton', 'Call Super', 3),
    ('houghton', 'Shanti Celeste', 4), ('houghton', 'Donna Leake', 5),
    ('houghton', 'Objekt', 6), ('houghton', 'Rhadoo', 7),
    ('houghton', 'Helena Hauff', 8), ('houghton', 'Grace Sands', 9),
    ('houghton', 'OK Williams', 10), ('houghton', 'Channel One', 11),
    ('houghton', 'The Ghost', 12), ('houghton', 'CCL', 13),
    ('houghton', 'livwutang', 14), ('houghton', 'Aurora Halal', 15),
    ('houghton', 'Underground Resistance', 16), ('houghton', 'Decius', 17),
    ('houghton', 'Peverelist', 18), ('houghton', 'Marie Davidson', 19),
    ('houghton', 'Radioactive Man', 20), ('houghton', 'Al Wootton', 21),
    ('houghton', 'Simo Cell', 22), ('houghton', 'Om Unit', 23),
    -- positiv
    ('positiv', 'Boris Brejcha', 0), ('positiv', 'Charlotte de Witte', 1),
    ('positiv', 'FISHER', 2), ('positiv', 'Marlon Hoffstadt', 3),
    ('positiv', 'Novah', 4), ('positiv', 'Biianco', 5),
    ('positiv', 'Carla Schmitt', 6), ('positiv', 'Nicolas Cuer', 7),
    ('positiv', 'Venga', 8),
    -- edc-mexico
    ('edc-mexico', 'Charlotte de Witte', 0), ('edc-mexico', 'Alesso', 1),
    ('edc-mexico', 'Above & Beyond', 2), ('edc-mexico', 'Diplo', 3),
    ('edc-mexico', 'Hugel', 4), ('edc-mexico', 'ANNA', 5),
    ('edc-mexico', 'Armand Van Helden', 6), ('edc-mexico', 'Chris Lake', 7),
    ('edc-mexico', 'Gareth Emery', 8), ('edc-mexico', 'Anyma', 9),
    ('edc-mexico', 'John Summit', 10), ('edc-mexico', 'Enrico Sangiuliano', 11),
    ('edc-mexico', 'Joseph Capriati', 12), ('edc-mexico', 'Vintage Culture', 13),
    ('edc-mexico', 'Jamie Jones', 14), ('edc-mexico', 'Mau P', 15),
    ('edc-mexico', 'The Martinez Brothers', 16), ('edc-mexico', 'Kevin de Vries', 17),
    ('edc-mexico', 'Sammy Virji', 18), ('edc-mexico', '999999999', 19),
    ('edc-mexico', 'Indira Paganotto', 20), ('edc-mexico', 'Mind Against', 21),
    ('edc-mexico', 'Yotto', 22), ('edc-mexico', 'Adam Ten', 23),
    ('edc-mexico', 'Michael Mayer', 24), ('edc-mexico', 'Rebolledo', 25),
    ('edc-mexico', 'Seth Troxler', 26), ('edc-mexico', 'Interplanetary Criminal', 27),
    ('edc-mexico', 'Beltran', 28),
    -- airbeat-one
    ('airbeat-one', 'Scooter', 0), ('airbeat-one', 'Boris Brejcha', 1),
    ('airbeat-one', 'Charlotte de Witte', 2), ('airbeat-one', 'Vini Vici', 3),
    ('airbeat-one', 'Paul van Dyk', 4), ('airbeat-one', 'Amelie Lens', 5),
    ('airbeat-one', 'Timmy Trumpet', 6), ('airbeat-one', 'HBz', 7),
    ('airbeat-one', 'Holy Priest', 8), ('airbeat-one', 'Lilly Palmer', 9),
    ('airbeat-one', 'Marlon Hoffstadt', 10), ('airbeat-one', 'Prada2000', 11),
    ('airbeat-one', 'Andrew Rayel', 12), ('airbeat-one', 'Blastoyz', 13),
    ('airbeat-one', 'Nifra', 14), ('airbeat-one', 'Ghost Rider', 15),
    ('airbeat-one', '999999999', 16), ('airbeat-one', 'Kobosil', 17),
    ('airbeat-one', 'D-Block & S-te-Fan', 18), ('airbeat-one', 'Da Tweekaz', 19),
    ('airbeat-one', 'Dr. Peacock', 20), ('airbeat-one', 'Ran-D', 21),
    ('airbeat-one', 'Cascada', 22), ('airbeat-one', 'Da Hool', 23),
    -- ultra-europe
    ('ultra-europe', 'Calvin Harris', 0), ('ultra-europe', 'Martin Garrix', 1),
    ('ultra-europe', 'Hardwell', 2), ('ultra-europe', 'Armin van Buuren', 3),
    ('ultra-europe', 'Afrojack', 4), ('ultra-europe', 'DJ Snake', 5),
    ('ultra-europe', 'John Summit', 6), ('ultra-europe', 'FISHER', 7),
    ('ultra-europe', 'Dom Dolla', 8), ('ultra-europe', 'Mau P', 9),
    ('ultra-europe', 'Sara Landry', 10), ('ultra-europe', 'Miss Monique', 11),
    ('ultra-europe', 'I Hate Models', 12), ('ultra-europe', 'WORSHIP', 13),
    ('ultra-europe', 'Adam Beyer', 14), ('ultra-europe', 'CamelPhat', 15),
    ('ultra-europe', 'Oliver Heldens', 16), ('ultra-europe', 'Subtronics', 17),
    -- loveland
    ('loveland', 'Sven Väth', 0), ('loveland', 'Sasha', 1),
    ('loveland', 'John Digweed', 2), ('loveland', 'Fatboy Slim', 3),
    ('loveland', 'Eric Prydz', 4), ('loveland', 'Ben Klock', 5),
    ('loveland', 'Hot Since 82', 6), ('loveland', 'CamelPhat', 7),
    ('loveland', 'Mau P', 8), ('loveland', 'Chris Liebing', 9),
    ('loveland', 'Speedy J', 10), ('loveland', 'East End Dubs', 11),
    ('loveland', 'Enrico Sangiuliano', 12), ('loveland', 'Kevin de Vries', 13),
    ('loveland', 'Jamie Jones', 14), ('loveland', 'Joris Voorn', 15),
    ('loveland', 'Kölsch', 16), ('loveland', 'Marsh', 17),
    ('loveland', 'Nicole Moudaber', 18), ('loveland', 'Robert Hood', 19),
    -- dimensions
    ('dimensions', 'Helena Hauff', 0), ('dimensions', 'John Talabot', 1),
    ('dimensions', 'Sonja Moonear', 2), ('dimensions', 'Amaliah', 3),
    ('dimensions', 'Ryan Elliott', 4), ('dimensions', 'Bunney', 5),
    ('dimensions', 'Radioactive Man', 6), ('dimensions', 'Hugo Martinez', 7),
    ('dimensions', 'Josh Caffe', 8), ('dimensions', 'Loren', 9),
    ('dimensions', 'Prosumer', 10), ('dimensions', 'DJ Storm', 11),
    ('dimensions', 'DMX Krew', 12), ('dimensions', 'Grace Sands', 13),
    ('dimensions', 'Satoshi Tomiie', 14),
    -- s2o-taiwan
    ('s2o-taiwan', 'Illenium', 0), ('s2o-taiwan', 'Zedd', 1),
    ('s2o-taiwan', 'I Hate Models', 2), ('s2o-taiwan', 'SLANDER', 3),
    ('s2o-taiwan', 'Aster', 4), ('s2o-taiwan', 'Arcando', 5),
    ('s2o-taiwan', 'Dabin', 6), ('s2o-taiwan', 'Andy C', 7),
    ('s2o-taiwan', 'Sabai', 8), ('s2o-taiwan', 'Soundrush', 9),
    ('s2o-taiwan', 'Merow', 10), ('s2o-taiwan', 'Nome', 11),
    ('s2o-taiwan', 'Baiyia', 12),
    -- bonnaroo
    ('bonnaroo', 'Skrillex', 0), ('bonnaroo', 'The Strokes', 1),
    ('bonnaroo', 'RÜFÜS DU SOL', 2), ('bonnaroo', 'Noah Kahan', 3),
    ('bonnaroo', 'GRiZ', 4), ('bonnaroo', 'Turnstile', 5),
    ('bonnaroo', 'Teddy Swims', 6), ('bonnaroo', 'The Neighbourhood', 7),
    ('bonnaroo', 'Role Model', 8), ('bonnaroo', 'Kesha', 9),
    ('bonnaroo', 'Four Tet', 10), ('bonnaroo', 'Vince Staples', 11),
    ('bonnaroo', 'Alabama Shakes', 12), ('bonnaroo', 'Chase & Status', 13),
    ('bonnaroo', 'Sara Landry', 14), ('bonnaroo', 'Clipse', 15),
    ('bonnaroo', 'Modest Mouse', 16), ('bonnaroo', 'Japanese Breakfast', 17),
    ('bonnaroo', 'Major Lazer', 18), ('bonnaroo', 'Wet Leg', 19),
    ('bonnaroo', 'Cloonee', 20), ('bonnaroo', 'SIDEPIECE', 21),
    ('bonnaroo', 'Boys Noize', 22), ('bonnaroo', 'Sub Focus', 23),
    ('bonnaroo', 'Gorgon City', 24),
    -- crssd
    ('crssd', 'Mochakk', 0), ('crssd', 'Chris Lake', 1),
    ('crssd', 'Disclosure', 2), ('crssd', 'Marlon Hoffstadt', 3),
    ('crssd', 'I Hate Models', 4), ('crssd', '999999999', 5),
    ('crssd', 'VTSS', 6), ('crssd', 'horsegiirL', 7),
    ('crssd', 'Mathame', 8), ('crssd', 'Groove Armada', 9),
    ('crssd', 'Helena Hauff', 10), ('crssd', 'Ben UFO', 11),
    ('crssd', 'Skepta', 12), ('crssd', 'Sonny Fodera', 13),
    -- a-state-of-trance
    ('a-state-of-trance', 'Armin van Buuren', 0), ('a-state-of-trance', 'Oliver Heldens', 1),
    ('a-state-of-trance', 'Maddix', 2), ('a-state-of-trance', 'Cosmic Gate', 3),
    ('a-state-of-trance', 'Rank 1', 4), ('a-state-of-trance', 'Hannah Laing', 5),
    ('a-state-of-trance', 'Aly & Fila', 6), ('a-state-of-trance', 'John O''Callaghan', 7),
    ('a-state-of-trance', 'Mauro Picotto', 8), ('a-state-of-trance', 'Laura van Dam', 9),
    ('a-state-of-trance', 'Ferry Corsten', 10), ('a-state-of-trance', 'Giuseppe Ottaviani', 11),
    -- hard-summer
    ('hard-summer', 'Kali Uchis', 0), ('hard-summer', 'Knock2', 1),
    ('hard-summer', 'Zedd', 2), ('hard-summer', 'DJ Snake', 3),
    ('hard-summer', 'Tokischa', 4), ('hard-summer', 'Shygirl', 5),
    ('hard-summer', 'Zack Fox', 6), ('hard-summer', 'Charlotte de Witte', 7),
    ('hard-summer', 'Amelie Lens', 8), ('hard-summer', 'Mau P', 9),
    ('hard-summer', 'RL Grime', 10), ('hard-summer', 'Maceo Plex', 11),
    ('hard-summer', 'Vintage Culture', 12), ('hard-summer', 'VTSS', 13),
    ('hard-summer', 'Sammy Virji', 14), ('hard-summer', 'Tiga', 15),
    ('hard-summer', 'Andy C', 16), ('hard-summer', 'Hannah Laing', 17),
    ('hard-summer', 'Chris Lorenzo', 18), ('hard-summer', 'Confidence Man', 19),
    ('hard-summer', 'Nick León', 20),
    -- snowbombing
    ('snowbombing', 'Maribou State', 0), ('snowbombing', 'De La Soul', 1),
    ('snowbombing', 'Orbital', 2), ('snowbombing', 'MJ Cole', 3),
    ('snowbombing', 'Sub Focus', 4), ('snowbombing', '4am Kru', 5),
    ('snowbombing', 'Hot 8 Brass Band', 6), ('snowbombing', 'Hybrid Minds', 7),
    ('snowbombing', 'Folamour', 8), ('snowbombing', 'Interplanetary Criminal', 9),
    ('snowbombing', 'Fish56Octagon', 10), ('snowbombing', 'East End Dubs', 11),
    ('snowbombing', 'Horsemeat Disco', 12), ('snowbombing', 'Girls Don''t Sync', 13),
    -- ava
    ('ava', 'Kneecap', 0), ('ava', 'Annie Mac', 1),
    ('ava', 'KETTAMA', 2), ('ava', 'Honey Dijon', 3),
    ('ava', 'Interplanetary Criminal', 4), ('ava', 'Octo Octa', 5),
    ('ava', 'Eris Drew', 6), ('ava', 'Blawan', 7),
    ('ava', 'Chloé Caillet', 8), ('ava', 'Calibre', 9),
    ('ava', 'Evian Christ', 10), ('ava', 'Or:la', 11),
    ('ava', 'Yousuke Yukimatsu', 12), ('ava', 'Cormac', 13),
    ('ava', 'Holly Lester', 14), ('ava', 'Partiboi69', 15),
    ('ava', 'DJ Gigola', 16), ('ava', 'Pegassi', 17),
    -- ultra-japan
    ('ultra-japan', 'Zedd', 0), ('ultra-japan', 'Knock2', 1),
    ('ultra-japan', 'Alesso', 2), ('ultra-japan', 'Peggy Gou', 3),
    ('ultra-japan', 'The Martinez Brothers', 4), ('ultra-japan', 'Sub Focus', 5),
    ('ultra-japan', 'Dimension', 6), ('ultra-japan', 'Culture Shock', 7),
    ('ultra-japan', 'WORSHIP', 8), ('ultra-japan', 'Sara Landry', 9),
    ('ultra-japan', 'Yousuke Yukimatsu', 10),
    -- les-plages-electroniques
    ('les-plages-electroniques', 'Martin Garrix', 0), ('les-plages-electroniques', 'DJ Snake', 1),
    ('les-plages-electroniques', 'Amelie Lens', 2), ('les-plages-electroniques', 'Marshmello', 3),
    ('les-plages-electroniques', 'PLK', 4), ('les-plages-electroniques', 'Mosimann', 5),
    ('les-plages-electroniques', 'Vladimir Cauchemar', 6), ('les-plages-electroniques', 'Maceo Plex', 7),
    ('les-plages-electroniques', 'Mathame', 8), ('les-plages-electroniques', 'Mind Against', 9),
    ('les-plages-electroniques', 'Nico Moreno', 10), ('les-plages-electroniques', 'Salvatore Ganacci', 11),
    ('les-plages-electroniques', 'Candice', 12), ('les-plages-electroniques', 'La Chica', 13),
    ('les-plages-electroniques', 'Sonny Fodera', 14), ('les-plages-electroniques', 'Interplanetary Criminal', 15),
    ('les-plages-electroniques', 'Anetha', 16), ('les-plages-electroniques', 'Clara Cuvé', 17),
    -- lollapalooza
    ('lollapalooza', 'Charli XCX', 0), ('lollapalooza', 'Tate McRae', 1),
    ('lollapalooza', 'Lorde', 2), ('lollapalooza', 'Olivia Dean', 3),
    ('lollapalooza', 'John Summit', 4), ('lollapalooza', 'JENNIE', 5),
    ('lollapalooza', 'The Smashing Pumpkins', 6), ('lollapalooza', 'The xx', 7),
    ('lollapalooza', 'Lil Uzi Vert', 8), ('lollapalooza', 'Turnstile', 9),
    ('lollapalooza', 'Sombr', 10), ('lollapalooza', 'The Neighbourhood', 11),
    ('lollapalooza', 'YUNGBLUD', 12), ('lollapalooza', 'beabadoobee', 13),
    ('lollapalooza', 'Ethel Cain', 14), ('lollapalooza', 'Empire of the Sun', 15),
    ('lollapalooza', 'Major Lazer', 16), ('lollapalooza', 'The Chainsmokers', 17),
    ('lollapalooza', 'aespa', 18), ('lollapalooza', 'Zara Larsson', 19),
    -- vision-colour
    ('vision-colour', 'Kygo', 0), ('vision-colour', 'John Summit', 1),
    ('vision-colour', 'Charlotte de Witte', 2), ('vision-colour', 'Porter Robinson', 3),
    ('vision-colour', 'Gorgon City', 4), ('vision-colour', 'Gryffin', 5),
    ('vision-colour', 'ISOxo', 6), ('vision-colour', 'Knock2', 7),
    ('vision-colour', 'Netsky', 8), ('vision-colour', 'AC Slater', 9),
    ('vision-colour', 'ARMNHMR', 10), ('vision-colour', 'Markus Schulz', 11),
    ('vision-colour', 'Ray Volpe', 12), ('vision-colour', 'SIDEPIECE', 13),
    ('vision-colour', 'Sultan + Shepard', 14),
    -- hideout
    ('hideout', 'Alan Fitzpatrick', 0), ('hideout', 'Skream', 1),
    ('hideout', 'Gorgon City', 2), ('hideout', 'LF SYSTEM', 3),
    ('hideout', 'Danny Howard', 4), ('hideout', 'Partiboi69', 5),
    ('hideout', 'Badger', 6), ('hideout', 'Krystal Klear', 7),
    ('hideout', '4am Kru', 8), ('hideout', 'East End Dubs', 9),
    ('hideout', 'Eliza Rose', 10), ('hideout', 'Paul Woolford', 11),
    ('hideout', 'Prospa', 12),
    -- beonix
    ('beonix', 'Adam Beyer', 0), ('beonix', 'CamelPhat', 1),
    ('beonix', 'Röyksopp', 2), ('beonix', 'Argy', 3),
    ('beonix', 'Bedouin', 4), ('beonix', 'Benny Benassi', 5),
    ('beonix', 'MRAK', 6), ('beonix', 'Monolink', 7),
    ('beonix', 'Jan Blomqvist', 8), ('beonix', 'Patrick Mason', 9),
    ('beonix', 'PAN-POT', 10), ('beonix', 'Franky Wah', 11),
    ('beonix', 'Raxon', 12), ('beonix', 'Spartaque', 13),
    ('beonix', 'OXIA', 14),
    -- lost-village
    ('lost-village', 'Peggy Gou', 0), ('lost-village', 'Solomun', 1),
    ('lost-village', 'Ben UFO', 2), ('lost-village', 'DJ Koze', 3),
    ('lost-village', 'Dixon', 4), ('lost-village', 'Seth Troxler', 5),
    ('lost-village', 'Horse Meat Disco', 6), ('lost-village', 'Soulwax', 7),
    ('lost-village', 'Ezra Collective', 8), ('lost-village', 'Elder Island', 9),
    ('lost-village', 'DJ Seinfeld', 10), ('lost-village', 'Overmono', 11),
    ('lost-village', 'Pale Jay', 12), ('lost-village', 'Yazmin Lacey', 13),
    ('lost-village', 'The Avalanches', 14), ('lost-village', 'Caribou', 15),
    ('lost-village', 'Bradley Zero', 16), ('lost-village', 'Ewan McVicar', 17),
    -- beyond-the-valley
    ('beyond-the-valley', 'Dom Dolla', 0), ('beyond-the-valley', 'Turnstile', 1),
    ('beyond-the-valley', 'Addison Rae', 2), ('beyond-the-valley', 'Kid Cudi', 3),
    ('beyond-the-valley', 'I Hate Models', 4), ('beyond-the-valley', '070 Shake', 5),
    ('beyond-the-valley', 'VTSS', 6), ('beyond-the-valley', 'Fcukers', 7),
    ('beyond-the-valley', 'Spacey Jane', 8), ('beyond-the-valley', 'Temper Trap', 9),
    ('beyond-the-valley', 'Mallrat', 10), ('beyond-the-valley', 'Luude', 11),
    ('beyond-the-valley', 'TV Rock', 12), ('beyond-the-valley', 'Cassian', 13),
    ('beyond-the-valley', 'Channel Tres', 14), ('beyond-the-valley', 'Chromeo', 15),
    ('beyond-the-valley', 'KETTAMA', 16), ('beyond-the-valley', 'Young Franco', 17),
    -- untold-dubai
    ('untold-dubai', 'Armin van Buuren', 0),
    -- groove-cruise
    ('groove-cruise', 'Ryan Key', 0), ('groove-cruise', 'Chris Lorenzo', 1),
    ('groove-cruise', 'Kyle Watson', 2), ('groove-cruise', 'Sabai', 3),
    ('groove-cruise', 'NOTD', 4), ('groove-cruise', 'Cassian', 5),
    ('groove-cruise', 'Sistek', 6), ('groove-cruise', 'Azzecca', 7),
    ('groove-cruise', 'Fallon', 8), ('groove-cruise', 'Tara Brooks', 9),
    ('groove-cruise', 'AYYBO', 10), ('groove-cruise', 'N2N', 11),
    ('groove-cruise', 'Torren Foot', 12),
    -- ultra-korea
    ('ultra-korea', 'Marshmello', 0), ('ultra-korea', 'Oliver Heldens', 1),
    ('ultra-korea', 'Timmy Trumpet', 2), ('ultra-korea', 'Martin Garrix', 3),
    ('ultra-korea', 'KSHMR', 4), ('ultra-korea', 'Nicky Romero', 5),
    ('ultra-korea', 'Adam Beyer', 6), ('ultra-korea', 'Nicole Moudaber', 7),
    ('ultra-korea', 'Sasha', 8),
    -- blacklist
    ('blacklist', 'Flux Pavilion', 0), ('blacklist', 'Krewella', 1),
    ('blacklist', 'Zomboy', 2), ('blacklist', 'Koven', 3),
    ('blacklist', 'A.M.C', 4), ('blacklist', 'Eptic', 5),
    ('blacklist', 'Mefjus', 6), ('blacklist', 'Primate', 7),
    ('blacklist', 'Riot', 8), ('blacklist', 'Blanke', 9),
    ('blacklist', 'Stoog3s', 10), ('blacklist', 'K Motionz', 11),
    ('blacklist', 'Gourski', 12), ('blacklist', 'Formula', 13),
    ('blacklist', 'Autopski', 14), ('blacklist', 'Burr Oak', 15),
    -- love-international
    ('love-international', 'Crazy P', 0), ('love-international', 'Horse Meat Disco', 1),
    ('love-international', 'Dave Harvey', 2), ('love-international', 'Adam Curtain', 3),
    ('love-international', 'Roman Flugel', 4), ('love-international', 'Palms Trax', 5),
    ('love-international', 'Midland', 6), ('love-international', 'Powder', 7),
    ('love-international', 'Luke Una', 8), ('love-international', 'Lola Haro', 9),
    ('love-international', 'Decius', 10), ('love-international', 'Mathew Jonson', 11),
    ('love-international', 'Reptant', 12),
    -- defected-croatia
    ('defected-croatia', 'Louie Vega', 0), ('defected-croatia', 'Honey Dijon', 1),
    ('defected-croatia', 'Moodymann', 2), ('defected-croatia', 'Jayda G', 3),
    ('defected-croatia', 'Floorplan', 4), ('defected-croatia', 'TSHA', 5),
    ('defected-croatia', 'Horse Meat Disco', 6), ('defected-croatia', 'Folamour', 7),
    ('defected-croatia', 'Armand Van Helden', 8), ('defected-croatia', 'Masters at Work', 9),
    ('defected-croatia', 'Low Steppa', 10), ('defected-croatia', 'Todd Terry', 11),
    ('defected-croatia', 'Dan Shake', 12), ('defected-croatia', 'John Summit', 13),
    ('defected-croatia', 'Seth Troxler', 14), ('defected-croatia', 'DJ EZ', 15),
    ('defected-croatia', 'Krystal Klear', 16), ('defected-croatia', 'Jonas Blue', 17),
    ('defected-croatia', 'Gerd Janson', 18), ('defected-croatia', 'Dennis Ferrer', 19),
    ('defected-croatia', 'Sam Divine', 20), ('defected-croatia', 'Purple Disco Machine', 21),
    -- nameless
    ('nameless', 'Calvin Harris', 0), ('nameless', 'John Summit', 1),
    ('nameless', 'FISHER', 2), ('nameless', 'Andy C', 3),
    ('nameless', 'Hybrid Minds', 4), ('nameless', 'Netsky', 5),
    ('nameless', 'Pendulum', 6), ('nameless', 'Sonny Fodera', 7),
    ('nameless', 'Chris Lorenzo', 8), ('nameless', 'SVDDEN DEATH', 9),
    ('nameless', 'Matisse & Sadko', 10), ('nameless', 'DubVision', 11),
    ('nameless', 'Third Party', 12), ('nameless', 'MPH', 13),
    ('nameless', 'Andromedik', 14), ('nameless', 'Kasablanca', 15),
    ('nameless', 'Mesto', 16), ('nameless', 'Nic Fanciulli', 17),
    ('nameless', 'HoneyLuv', 18), ('nameless', 'Cinthie', 19),
    -- edc-thailand
    ('edc-thailand', 'Martin Garrix', 0), ('edc-thailand', 'Charlotte de Witte', 1),
    ('edc-thailand', 'DJ Snake', 2), ('edc-thailand', 'Above & Beyond', 3),
    ('edc-thailand', 'Dom Dolla', 4), ('edc-thailand', 'Tiësto', 5),
    ('edc-thailand', 'Andy C', 6), ('edc-thailand', 'Paul van Dyk', 7),
    ('edc-thailand', 'Vintage Culture', 8), ('edc-thailand', 'SOFI TUKKER', 9),
    ('edc-thailand', 'James Hype', 10), ('edc-thailand', 'Mau P', 11),
    ('edc-thailand', 'Hannah Laing', 12),
    -- ultra-buenos-aires
    ('ultra-buenos-aires', 'Zedd', 0), ('ultra-buenos-aires', 'Steve Angello', 1),
    ('ultra-buenos-aires', 'Alesso', 2), ('ultra-buenos-aires', 'Above & Beyond', 3),
    ('ultra-buenos-aires', 'deadmau5', 4), ('ultra-buenos-aires', 'Dom Dolla', 5),
    ('ultra-buenos-aires', 'KSHMR', 6), ('ultra-buenos-aires', 'Charlotte de Witte', 7),
    ('ultra-buenos-aires', 'Richie Hawtin', 8), ('ultra-buenos-aires', 'Jamie Jones', 9),
    ('ultra-buenos-aires', 'Joseph Capriati', 10), ('ultra-buenos-aires', 'Mau P', 11),
    ('ultra-buenos-aires', 'Indira Paganotto', 12), ('ultra-buenos-aires', 'Kevin de Vries', 13),
    ('ultra-buenos-aires', 'CamelPhat', 14), ('ultra-buenos-aires', 'Massano', 15),
    -- fly-open-air
    ('fly-open-air', 'Jamie Jones', 0), ('fly-open-air', 'Marlon Hoffstadt', 1),
    ('fly-open-air', 'Max Dean', 2), ('fly-open-air', 'Rossi', 3),
    ('fly-open-air', 'Chloé Caillet', 4), ('fly-open-air', 'Obskur', 5),
    -- pitch-music-arts
    ('pitch-music-arts', 'Charlotte de Witte', 0), ('pitch-music-arts', 'Eris Drew', 1),
    ('pitch-music-arts', 'Octo Octa', 2), ('pitch-music-arts', 'MARRØN', 3),
    ('pitch-music-arts', 'Girls Don''t Sync', 4), ('pitch-music-arts', 'Job Jobse', 5),
    ('pitch-music-arts', 'Ewan McVicar', 6), ('pitch-music-arts', 'Palms Trax', 7),
    ('pitch-music-arts', 'Sama'' Abdulhadi', 8), ('pitch-music-arts', 'DJ Nobu', 9),
    ('pitch-music-arts', 'Aquenta', 10), ('pitch-music-arts', 'Sleep D', 11),
    ('pitch-music-arts', 'Jennifer Loveless', 12),
    -- beyond-wonderland
    ('beyond-wonderland', 'Tiësto', 0), ('beyond-wonderland', 'Zedd', 1),
    ('beyond-wonderland', 'Alison Wonderland', 2), ('beyond-wonderland', 'Alok', 3),
    ('beyond-wonderland', 'SLANDER', 4), ('beyond-wonderland', 'Steve Angello', 5),
    ('beyond-wonderland', 'GRiZ', 6), ('beyond-wonderland', 'ATLiens', 7),
    ('beyond-wonderland', 'Black Tiger Sex Machine', 8), ('beyond-wonderland', 'DEATHPACT', 9),
    ('beyond-wonderland', 'Eptic', 10), ('beyond-wonderland', 'Space Laces', 11),
    ('beyond-wonderland', 'SIDEPIECE', 12), ('beyond-wonderland', 'Matroda', 13),
    ('beyond-wonderland', 'Layton Giordani', 14),
    -- ultra-australia
    ('ultra-australia', 'The Chainsmokers', 0), ('ultra-australia', 'DJ Snake', 1),
    ('ultra-australia', 'Zedd', 2), ('ultra-australia', 'Oliver Heldens', 3),
    ('ultra-australia', 'Miss Monique', 4), ('ultra-australia', 'Nico Moreno', 5),
    ('ultra-australia', 'HI-LO', 6), ('ultra-australia', 'KAAZE', 7),
    ('ultra-australia', 'Fatima Hajji', 8), ('ultra-australia', 'Rebuke', 9),
    ('ultra-australia', 'Oscar L', 10), ('ultra-australia', 'Alesso', 11),
    -- glitch
    ('glitch', 'Amelie Lens', 0), ('glitch', 'Ben Klock', 1),
    ('glitch', 'Rødhåd', 2), ('glitch', 'Job Jobse', 3),
    ('glitch', 'Chris Stussy', 4), ('glitch', 'Alarico', 5),
    ('glitch', 'KI/KI', 6), ('glitch', 'Mall Grab', 7),
    ('glitch', 'Silva Bumpa', 8), ('glitch', 'Serafina', 9),
    ('glitch', 'SHDW', 10), ('glitch', 'Funk Tribu', 11),
    ('glitch', 'Mischluft', 12), ('glitch', 'Pegassi', 13),
    -- medusa
    ('medusa', 'Carl Cox', 0), ('medusa', 'Tiësto', 1),
    ('medusa', 'Dimitri Vegas', 2), ('medusa', 'Adam Beyer', 3),
    ('medusa', 'Angerfist', 4), ('medusa', 'Miss Monique', 5),
    ('medusa', 'Hugel', 6), ('medusa', 'James Hype', 7),
    ('medusa', 'Marco Carola', 8), ('medusa', 'Mau P', 9),
    ('medusa', 'Steve Aoki', 10), ('medusa', 'Sara Landry', 11),
    ('medusa', 'Fantasm', 12), ('medusa', 'Wade', 13),
    ('medusa', 'Oliver Heldens', 14), ('medusa', 'Timmy Trumpet', 15),
    ('medusa', 'NERVO', 16),
    -- sunset-by-neon
    ('sunset-by-neon', 'ARTBAT', 0), ('sunset-by-neon', 'R3HAB', 1),
    ('sunset-by-neon', 'Chris Avantgarde', 2), ('sunset-by-neon', 'PlastiK Funk', 3),
    ('sunset-by-neon', '7SKIES', 4),
    -- gmo-sonic
    ('gmo-sonic', 'Swedish House Mafia', 0), ('gmo-sonic', 'Marshmello', 1),
    ('gmo-sonic', 'Tiësto', 2), ('gmo-sonic', 'Afrojack', 3),
    ('gmo-sonic', 'Steve Aoki', 4), ('gmo-sonic', 'Dom Dolla', 5),
    ('gmo-sonic', 'Meduza', 6), ('gmo-sonic', 'GloRilla', 7),
    ('gmo-sonic', 'Sirup', 8), ('gmo-sonic', 'Licaxxx', 9),
    -- beats-for-love
    ('beats-for-love', 'Calvin Harris', 0), ('beats-for-love', 'Dimitri Vegas & Like Mike', 1),
    ('beats-for-love', 'Marshmello', 2), ('beats-for-love', 'Paul van Dyk', 3),
    ('beats-for-love', 'Charlotte de Witte', 4), ('beats-for-love', 'Dimension', 5),
    ('beats-for-love', 'Pendulum', 6), ('beats-for-love', 'Lilly Palmer', 7),
    -- magic-of-tomorrowland
    ('magic-of-tomorrowland', 'Calvin Harris', 0), ('magic-of-tomorrowland', 'David Guetta', 1),
    ('magic-of-tomorrowland', 'Martin Garrix', 2), ('magic-of-tomorrowland', 'FISHER', 3),
    ('magic-of-tomorrowland', 'John Summit', 4), ('magic-of-tomorrowland', 'NERVO', 5),
    ('magic-of-tomorrowland', 'Hardwell', 6), ('magic-of-tomorrowland', 'Dimitri Vegas & Like Mike', 7),
    ('magic-of-tomorrowland', 'Sebastian Ingrosso', 8), ('magic-of-tomorrowland', 'Sara Landry', 9),
    ('magic-of-tomorrowland', 'Kevin de Vries', 10), ('magic-of-tomorrowland', 'Lost Frequencies', 11),
    ('magic-of-tomorrowland', 'The Chainsmokers', 12), ('magic-of-tomorrowland', 'Marlon Hoffstadt', 13),
    ('magic-of-tomorrowland', 'Agents Of Time', 14),
    -- nature-one
    ('nature-one', 'Paul Kalkbrenner', 0), ('nature-one', 'Fatboy Slim', 1),
    ('nature-one', 'Paul van Dyk', 2), ('nature-one', 'Felix Jähn', 3),
    ('nature-one', 'Sven Väth', 4), ('nature-one', 'Angerfist', 5),
    ('nature-one', 'Lilly Palmer', 6), ('nature-one', 'I Hate Models', 7),
    ('nature-one', 'Alle Farben', 8), ('nature-one', 'Holy Priest', 9),
    ('nature-one', 'Neelix', 10), ('nature-one', 'Miss K8', 11),
    ('nature-one', 'Westbam', 12), ('nature-one', 'Schiller', 13),
    ('nature-one', 'Judge Jules', 14), ('nature-one', 'Da Hool', 15),
    ('nature-one', 'Kyau & Albert', 16),
    -- ultra-south-africa
    ('ultra-south-africa', 'John Summit', 0), ('ultra-south-africa', 'DJ Snake', 1),
    ('ultra-south-africa', 'Axwell', 2), ('ultra-south-africa', 'Afrojack', 3),
    ('ultra-south-africa', 'R3HAB', 4), ('ultra-south-africa', 'Dennis Ferrer', 5),
    ('ultra-south-africa', 'Shimza', 6), ('ultra-south-africa', 'Apashe', 7),
    ('ultra-south-africa', 'Kyle Watson', 8), ('ultra-south-africa', 'Caiiro', 9),
    ('ultra-south-africa', 'De Capo', 10), ('ultra-south-africa', 'Kid Fonque', 11),
    -- lost-lands
    ('lost-lands', 'Excision', 0), ('lost-lands', 'Subtronics', 1),
    ('lost-lands', 'Illenium', 2), ('lost-lands', 'Seven Lions', 3),
    ('lost-lands', 'Wooli', 4), ('lost-lands', 'SLANDER', 5),
    ('lost-lands', 'Flux Pavilion', 6), ('lost-lands', 'Space Laces', 7),
    ('lost-lands', 'Hedex', 8), ('lost-lands', 'Bou', 9),
    ('lost-lands', 'Kai Wachi', 10), ('lost-lands', 'Levity', 11),
    -- defected-malta
    ('defected-malta', 'Hot Since 82', 0), ('defected-malta', 'Syreeta', 1),
    ('defected-malta', 'Chez Damier', 2), ('defected-malta', 'Sidney Charles', 3),
    ('defected-malta', 'Jayda G', 4), ('defected-malta', 'Green Velvet', 5),
    ('defected-malta', 'Lil'' Louis', 6), ('defected-malta', 'Dennis Ferrer', 7),
    ('defected-malta', 'Todd Terry', 8), ('defected-malta', 'Kevin Saunderson', 9),
    ('defected-malta', 'Eliza Rose', 10), ('defected-malta', 'Dan Shake', 11),
    ('defected-malta', 'Sam Divine', 12), ('defected-malta', 'Eats Everything', 13),
    ('defected-malta', 'Low Steppa', 14), ('defected-malta', 'Harry Romero', 15),
    -- verknipt
    ('verknipt', 'AREA ØNE', 0), ('verknipt', 'Ben Techy', 1),
    ('verknipt', 'RAMØN', 2), ('verknipt', 'Entasia', 3),
    ('verknipt', 'Fantasm', 4), ('verknipt', 'fumi', 5),
    ('verknipt', 'Karah', 6), ('verknipt', 'Klofama', 7),
    ('verknipt', 'Vieze Asbak', 8), ('verknipt', 'Kuko', 9),
    -- iii-points
    ('iii-points', 'Underworld', 0), ('iii-points', 'Four Tet', 1),
    ('iii-points', 'Flying Lotus', 2), ('iii-points', 'Blood Orange', 3),
    ('iii-points', 'Kelela', 4), ('iii-points', 'Charlotte de Witte', 5),
    ('iii-points', 'Tricky', 6), ('iii-points', 'Honey Dijon', 7),
    ('iii-points', 'Parcels', 8), ('iii-points', 'Men I Trust', 9),
    ('iii-points', 'Pawsa', 10), ('iii-points', 'horsegiirL', 11),
    ('iii-points', 'Danny Brown', 12), ('iii-points', 'Bone Thugs-N-Harmony', 13),
    ('iii-points', 'GZA', 14), ('iii-points', 'Lil'' Kim', 15),
    ('iii-points', 'Tokischa', 16), ('iii-points', 'Daphni', 17),
    ('iii-points', 'Floating Points', 18),
    -- baum
    ('baum', 'Richie Hawtin', 0), ('baum', 'Boys Noize', 1),
    ('baum', 'Helena Hauff', 2), ('baum', 'Avalon Emerson', 3),
    ('baum', 'Nick León', 4), ('baum', 'Felipe Gordon', 5),
    -- balaton-sound
    ('balaton-sound', 'Martin Garrix', 0), ('balaton-sound', 'Afrojack', 1),
    ('balaton-sound', 'Armin van Buuren', 2), ('balaton-sound', 'Knife Party', 3),
    ('balaton-sound', 'Solomun', 4), ('balaton-sound', 'FISHER', 5),
    ('balaton-sound', 'Yellow Claw', 6),
    -- melt
    ('melt', 'Solomun', 0), ('melt', 'Peggy Gou', 1),
    ('melt', 'Moderat', 2), ('melt', 'Jon Hopkins', 3),
    ('melt', 'Âme', 4),
    -- ravolution
    ('ravolution', 'Armin van Buuren', 0),
    -- sea-star
    ('sea-star', 'Boris Brejcha', 0), ('sea-star', 'KI/KI', 1),
    ('sea-star', 'Holy Priest', 2), ('sea-star', 'Xzibit', 3),
    ('sea-star', 'Layla Benitez', 4), ('sea-star', 'Lottie', 5),
    ('sea-star', 'Marcel', 6),
    -- electric-castle
    ('electric-castle', 'The Cure', 0), ('electric-castle', 'Twenty One Pilots', 1),
    ('electric-castle', 'Teddy Swims', 2), ('electric-castle', 'Chase & Status', 3),
    ('electric-castle', 'Wet Leg', 4), ('electric-castle', 'LP', 5),
    ('electric-castle', 'Nothing But Thieves', 6), ('electric-castle', 'Kneecap', 7),
    ('electric-castle', 'Sleaford Mods', 8), ('electric-castle', 'Subtronics', 9),
    ('electric-castle', 'Maverick Sabre', 10), ('electric-castle', 'Jax Jones', 11),
    ('electric-castle', 'Wilkinson', 12), ('electric-castle', 'Kölsch', 13),
    ('electric-castle', 'Deep Dish', 14), ('electric-castle', 'Solardo', 15),
    ('electric-castle', 'SG Lewis', 16), ('electric-castle', 'Eliza Rose', 17),
    ('electric-castle', 'Mochakk', 18),
    -- outlook-origins
    ('outlook-origins', 'Goldie', 0), ('outlook-origins', 'Ben UFO', 1),
    ('outlook-origins', 'Fabio', 2), ('outlook-origins', 'Grooverider', 3),
    ('outlook-origins', 'Kode9', 4), ('outlook-origins', 'Sully', 5),
    ('outlook-origins', 'Mala', 6), ('outlook-origins', 'The Bug', 7),
    ('outlook-origins', 'Objekt', 8), ('outlook-origins', 'Batu', 9),
    ('outlook-origins', 'Octo Octa', 10), ('outlook-origins', 'Om Unit', 11),
    ('outlook-origins', 'Loxy', 12), ('outlook-origins', 'Breakage', 13),
    ('outlook-origins', 'Channel One', 14), ('outlook-origins', 'Commodo', 15),
    ('outlook-origins', 'Donna Leake', 16), ('outlook-origins', 'Sam Binga', 17),
    ('outlook-origins', 'Tim Reaper', 18)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;

-- Mark these editions as having a published lineup.
update public.festival_editions e
set lineup_published = true
from public.festivals f
where e.festival_id = f.id
  and e.year = 2026
  and f.slug in (
    'kappa-futurfestival',
    'electric-love',
    'parklife',
    'time-warp',
    'edc-orlando',
    'dekmantel',
    'primer',
    'boomtown',
    'amf',
    'terminal-v',
    'world-club-dome',
    'world-dj-festival',
    'monegros',
    'neopop',
    'siam-songkran',
    'primavera-sound',
    's2o-bangkok',
    'movement',
    'panorama',
    'dgtl',
    'sonar',
    'nibirii',
    'veld',
    'arc',
    'tomorrowland-winter',
    'houghton',
    'positiv',
    'edc-mexico',
    'airbeat-one',
    'ultra-europe',
    'loveland',
    'dimensions',
    's2o-taiwan',
    'bonnaroo',
    'crssd',
    'a-state-of-trance',
    'hard-summer',
    'snowbombing',
    'ava',
    'ultra-japan',
    'les-plages-electroniques',
    'lollapalooza',
    'vision-colour',
    'hideout',
    'beonix',
    'lost-village',
    'beyond-the-valley',
    'untold-dubai',
    'groove-cruise',
    'ultra-korea',
    'blacklist',
    'love-international',
    'defected-croatia',
    'nameless',
    'edc-thailand',
    'ultra-buenos-aires',
    'fly-open-air',
    'pitch-music-arts',
    'beyond-wonderland',
    'ultra-australia',
    'glitch',
    'medusa',
    'sunset-by-neon',
    'gmo-sonic',
    'beats-for-love',
    'magic-of-tomorrowland',
    'nature-one',
    'ultra-south-africa',
    'lost-lands',
    'defected-malta',
    'verknipt',
    'iii-points',
    'baum',
    'balaton-sound',
    'melt',
    'ravolution',
    'sea-star',
    'electric-castle',
    'outlook-origins'
  );

