-- ============================================================
-- Fcknye Festival 2025 (Dec 30, 2025 - Jan 1, 2026) — full lineup,
-- for the user who logged attendance to this edition. Sourced from
-- Resident Advisor and festapp.io lineup archives.
-- ============================================================

insert into public.festival_editions (festival_id, year, start_date, end_date)
select f.id, 2025, '2025-12-30'::date, '2026-01-01'::date
from public.festivals f where f.slug = 'fcknye-festival'
on conflict (festival_id, year) do update
  set start_date = excluded.start_date, end_date = excluded.end_date;

insert into public.artists (name) select v.name from (values
  ('Restricted'),
  ('BYØRN'),
  ('OGUZ'),
  ('DYEN'),
  ('Rooler'),
  ('DJ Hyperdrive'),
  ('AMK'),
  ('A5KM'),
  ('Ziak'),
  ('Marion Di Napoli'),
  ('Josman'),
  ('F. Noize'),
  ('Partyraiser'),
  ('DRS'),
  ('Sandy Warez'),
  ('Fenrick'),
  ('EMILIJA'),
  ('ØTTA'),
  ('Shlømo'),
  ('Malaa'),
  ('Camo & Krooked'),
  ('Macky Gee'),
  ('Dirtyphonics'),
  ('Dual Damage'),
  ('Aversion'),
  ('Urumi'),
  ('Stan Christ'),
  ('MATRAKK'),
  ('Eskha'),
  ('Die Klar'),
  ('imHAPPY'),
  ('Rayzen'),
  ('Jolagreen23'),
  ('La Fouine'),
  ('Todiefor'),
  ('Russian Village Boys'),
  ('Eargasm God'),
  ('CLTX'),
  ('L2B'),
  ('Nicolas Julian'),
  ('Omiki'),
  ('Benwal'),
  ('CARV'),
  ('La Fève'),
  ('KUKO'),
  ('Indira Paganotto'),
  ('BIIA'),
  ('Dinos'),
  ('Ran-D'),
  ('La Mano 1.9'),
  ('Creeds'),
  ('Vandal'),
  ('Miss Bashful'),
  ('DBBD'),
  ('Sickmode'),
  ('PLK'),
  ('Warface'),
  ('Onlynumbers'),
  ('Von Bikräv'),
  ('Jersey'),
  ('Vladimir Cauchemar'),
  ('Billx'),
  ('Hades'),
  ('Evil Grimace'),
  ('Vald'),
  ('Sub Zero Project'),
  ('PERCEVAL'),
  ('Ascendant Vierge'),
  ('Omaks'),
  ('Nico Moreno'),
  ('Trym'),
  ('Da Tweekaz'),
  ('Vortek''s'),
  ('GPF'),
  ('Dr Donk'),
  ('Mr. Polska'),
  ('NOVAH'),
  ('Dr. Peacock'),
  ('Dimension Bonus'),
  ('Holy Priest'),
  ('Amygdala'),
  ('Paolo Ferrara'),
  ('The Dark Horror'),
  ('Mandragora'),
  ('Unicorn On Ketamine'),
  ('William Luck'),
  ('Dimitri K'),
  ('MC Robs'),
  ('Koven'),
  ('MARHU'),
  ('Pat B'),
  ('DJ Furax'),
  ('Hard Candy'),
  ('The Purge'),
  ('Jacidorex'),
  ('The Saints'),
  ('999999999'),
  ('Toxic Twins'),
  ('Vernex'),
  ('D-Fence'),
  ('Vendex'),
  ('Major Conspiracy'),
  ('WINSON'),
  ('Pinotello'),
  ('NRKi'),
  ('Basswell'),
  ('Yoshiko'),
  ('Jazzy'),
  ('Jowi'),
  ('RDØ'),
  ('Vieze Asbak'),
  ('KARAH'),
  ('KLOFAMA'),
  ('Angerfist'),
  ('LESSSS'),
  ('GRAViiTY'),
  ('ZAAG'),
  ('Nina Kraviz'),
  ('Black Sun Empire'),
  ('Rebekah')
) as v(name) where not exists (select 1 from public.artists a where lower(a.name) = lower(v.name));

with lineup(artist_name, order_index) as (values
  ('Restricted', 0),
  ('BYØRN', 1),
  ('OGUZ', 2),
  ('DYEN', 3),
  ('Rooler', 4),
  ('DJ Hyperdrive', 5),
  ('AMK', 6),
  ('A5KM', 7),
  ('Ziak', 8),
  ('Marion Di Napoli', 9),
  ('Josman', 10),
  ('F. Noize', 11),
  ('Partyraiser', 12),
  ('DRS', 13),
  ('Sandy Warez', 14),
  ('Fenrick', 15),
  ('EMILIJA', 16),
  ('ØTTA', 17),
  ('Shlømo', 18),
  ('Malaa', 19),
  ('Camo & Krooked', 20),
  ('Macky Gee', 21),
  ('Dirtyphonics', 22),
  ('Dual Damage', 23),
  ('Aversion', 24),
  ('Urumi', 25),
  ('Stan Christ', 26),
  ('MATRAKK', 27),
  ('Eskha', 28),
  ('Die Klar', 29),
  ('imHAPPY', 30),
  ('Rayzen', 31),
  ('Jolagreen23', 32),
  ('La Fouine', 33),
  ('Todiefor', 34),
  ('Russian Village Boys', 35),
  ('Eargasm God', 36),
  ('CLTX', 37),
  ('L2B', 38),
  ('Nicolas Julian', 39),
  ('Omiki', 40),
  ('Benwal', 41),
  ('CARV', 42),
  ('La Fève', 43),
  ('KUKO', 44),
  ('Indira Paganotto', 45),
  ('BIIA', 46),
  ('Dinos', 47),
  ('Ran-D', 48),
  ('La Mano 1.9', 49),
  ('Creeds', 50),
  ('Vandal', 51),
  ('Miss Bashful', 52),
  ('DBBD', 53),
  ('Sickmode', 54),
  ('PLK', 55),
  ('Warface', 56),
  ('Onlynumbers', 57),
  ('Von Bikräv', 58),
  ('Jersey', 59),
  ('Vladimir Cauchemar', 60),
  ('Billx', 61),
  ('Hades', 62),
  ('Evil Grimace', 63),
  ('Vald', 64),
  ('Sub Zero Project', 65),
  ('PERCEVAL', 66),
  ('Ascendant Vierge', 67),
  ('Omaks', 68),
  ('Nico Moreno', 69),
  ('Trym', 70),
  ('Da Tweekaz', 71),
  ('Vortek''s', 72),
  ('GPF', 73),
  ('Dr Donk', 74),
  ('Mr. Polska', 75),
  ('NOVAH', 76),
  ('Dr. Peacock', 77),
  ('Dimension Bonus', 78),
  ('Holy Priest', 79),
  ('Amygdala', 80),
  ('Paolo Ferrara', 81),
  ('The Dark Horror', 82),
  ('Mandragora', 83),
  ('Unicorn On Ketamine', 84),
  ('William Luck', 85),
  ('Dimitri K', 86),
  ('MC Robs', 87),
  ('Koven', 88),
  ('MARHU', 89),
  ('Pat B', 90),
  ('DJ Furax', 91),
  ('Hard Candy', 92),
  ('The Purge', 93),
  ('Jacidorex', 94),
  ('The Saints', 95),
  ('999999999', 96),
  ('Toxic Twins', 97),
  ('Vernex', 98),
  ('D-Fence', 99),
  ('Vendex', 100),
  ('Major Conspiracy', 101),
  ('WINSON', 102),
  ('Pinotello', 103),
  ('NRKi', 104),
  ('Basswell', 105),
  ('Yoshiko', 106),
  ('Jazzy', 107),
  ('Jowi', 108),
  ('RDØ', 109),
  ('Vieze Asbak', 110),
  ('KARAH', 111),
  ('KLOFAMA', 112),
  ('Angerfist', 113),
  ('LESSSS', 114),
  ('GRAViiTY', 115),
  ('ZAAG', 116),
  ('Nina Kraviz', 117),
  ('Black Sun Empire', 118),
  ('Rebekah', 119)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index from lineup l
join public.festivals f on f.slug = 'fcknye-festival'
join public.festival_editions e on e.festival_id = f.id and e.year = 2025
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;

update public.festival_editions e set lineup_published = true from public.festivals f where e.festival_id=f.id and f.slug='fcknye-festival' and e.year=2025;
