-- ============================================================
-- Festival metadata enrichment for the DJ Mag Top 100 imports.
-- Curated city / genres / one-line description / official site.
-- Idempotent and non-destructive: only fills missing fields
-- (existing descriptions, websites and non-empty genre arrays
-- are preserved). Unknown fields stay null.
-- ============================================================

update public.festivals f
set
  city = coalesce(f.city, d.city),
  genres = case when cardinality(f.genres) = 0 and d.genres is not null then d.genres else f.genres end,
  description = coalesce(f.description, d.description),
  official_website = coalesce(f.official_website, d.website)
from (values
  ('sunburn', 'Goa', '{edm,house,techno}'::text[], 'Asia''s largest electronic dance music festival.', 'https://www.sunburn.in'),
  ('kappa-futurfestival', 'Turin', '{techno,house}'::text[], 'Italy''s leading techno festival in the post-industrial Parco Dora.', 'https://kappafuturfestival.it'),
  ('glastonbury', 'Pilton', '{rock,pop,electronic,indie}'::text[], 'The legendary five-day festival of contemporary performing arts.', 'https://www.glastonburyfestivals.co.uk'),
  ('electric-love', 'Plainfeld', '{edm,house,hardstyle,techno}'::text[], 'Austria''s biggest electronic music festival at the Salzburgring.', 'https://electriclove.at'),
  ('parklife', 'Manchester', '{electronic,house,hiphop,pop}'::text[], 'The UK''s biggest metropolitan festival, held in Heaton Park.', 'https://parklife.uk.com'),
  ('time-warp', 'Mannheim', '{techno,house}'::text[], 'The world''s most renowned indoor techno event.', 'https://www.time-warp.de'),
  ('edc-orlando', 'Orlando', '{edm,house,techno,dubstep}'::text[], 'Electric Daisy Carnival''s East Coast edition under the Florida sky.', 'https://orlando.electricdaisycarnival.com'),
  ('dekmantel', 'Amsterdam', '{techno,house,electronic}'::text[], 'Amsterdam''s tastemaker festival for underground electronic music.', 'https://dekmantelfestival.com'),
  ('primer', 'Athens', '{electronic,edm}'::text[], 'Greece''s largest electronic music festival.', null),
  ('boomtown', 'Winchester', '{electronic,bass,dnb,reggae}'::text[], 'A theatrical city-festival with immersive districts and storylines.', 'https://www.boomtownfair.co.uk'),
  ('amf', 'Amsterdam', '{edm,house,trance}'::text[], 'Amsterdam Music Festival — ADE''s stadium-scale flagship night.', 'https://www.amf-festival.com'),
  ('terminal-v', 'Edinburgh', '{techno}'::text[], 'Scotland''s biggest techno festival.', 'https://www.terminalv.co.uk'),
  ('world-club-dome', 'Frankfurt', '{edm,house,techno}'::text[], 'The self-proclaimed biggest club in the world, inside Frankfurt''s stadium.', 'https://www.worldclubdome.com'),
  ('world-dj-festival', 'Seoul', '{edm}'::text[], 'South Korea''s flagship EDM festival.', null),
  ('monegros', 'Fraga', '{techno,house,electronic}'::text[], 'A one-day rave marathon in the Spanish desert.', 'https://monegrosfestival.com'),
  ('808-festival', 'Bangkok', '{edm,bass}'::text[], 'Thailand''s long-running EDM and bass festival.', null),
  ('neopop', 'Viana do Castelo', '{techno}'::text[], 'Portugal''s premier techno gathering by the Atlantic.', 'https://www.neopopfestival.com'),
  ('siam-songkran', 'Bangkok', '{edm}'::text[], 'EDM celebration during Thailand''s Songkran water festival.', null),
  ('primavera-sound', 'Barcelona', '{indie,rock,pop,electronic}'::text[], 'Barcelona''s genre-spanning tastemaker mega-festival.', 'https://www.primaverasound.com'),
  ('burning-man', 'Black Rock City', '{electronic,art}'::text[], 'A temporary city of radical self-expression in the Nevada desert.', 'https://burningman.org'),
  ('s2o-bangkok', 'Bangkok', '{edm}'::text[], 'The world-famous Songkran water music festival.', 'https://www.s2ofestival.com'),
  ('neversea', 'Constanța', '{edm,house,techno}'::text[], 'Untold''s seaside sister festival on the Black Sea beach.', 'https://neversea.com'),
  ('movement', 'Detroit', '{techno,house}'::text[], 'Detroit''s techno homecoming in Hart Plaza.', 'https://www.movementfestival.com'),
  ('panorama', null, '{electronic}'::text[], null, null),
  ('dgtl', 'Amsterdam', '{techno,house}'::text[], 'Circular, art-driven techno festival at the NDSM Docklands.', 'https://dgtl.nl'),
  ('sonar', 'Barcelona', '{electronic,experimental,techno}'::text[], 'Barcelona''s pioneering festival of music, creativity and technology.', 'https://sonar.es'),
  ('nibirii', 'Düren', '{dnb,techno,bass}'::text[], 'Drum & bass and techno on the Dürener lakeside.', null),
  ('veld', 'Toronto', '{edm,hiphop}'::text[], 'Toronto''s biggest electronic and hip-hop festival.', null),
  ('arc', 'Chicago', '{house,techno}'::text[], 'House and techno in the birthplace of house music.', 'https://arcmusicfestival.com'),
  ('tomorrowland-winter', 'Alpe d''Huez', '{edm,house,techno}'::text[], 'Tomorrowland''s alpine edition in the French Alps.', 'https://www.tomorrowland.com/winter'),
  ('houghton', 'King''s Lynn', '{electronic,techno,house}'::text[], 'A 24-hour-licence art and music happening curated by Craig Richards.', null),
  ('edc-mexico', 'Mexico City', '{edm}'::text[], 'EDC''s Mexican mega-edition at the Autódromo Hermanos Rodríguez.', 'https://mexico.electricdaisycarnival.com'),
  ('airbeat-one', 'Neustadt-Glewe', '{edm,hardstyle}'::text[], 'Northern Germany''s international EDM festival with monumental stages.', 'https://www.airbeat-one.de'),
  ('ultra-europe', 'Split', '{edm,house,techno}'::text[], 'Ultra''s European flagship on the Croatian coast.', 'https://ultraeurope.com'),
  ('loveland', 'Amsterdam', '{techno,house}'::text[], 'Amsterdam''s long-running techno institution.', 'https://loveland.nl'),
  ('dimensions', 'Tisno', '{electronic,house,techno,bass}'::text[], 'Underground soundsystem culture on the Adriatic coast.', null),
  ('s2o-taiwan', 'Taipei', '{edm}'::text[], 'The Songkran water festival''s Taiwanese edition.', null),
  ('bonnaroo', 'Manchester (TN)', '{rock,pop,electronic,hiphop}'::text[], 'Four days of music and camping on The Farm in Tennessee.', 'https://www.bonnaroo.com'),
  ('crssd', 'San Diego', '{house,techno}'::text[], 'House and techno on the San Diego waterfront.', 'https://www.crssdfest.com'),
  ('a-state-of-trance', 'Rotterdam', '{trance}'::text[], 'Armin van Buuren''s trance mothership event.', 'https://www.astateoftrance.com'),
  ('together', 'Bangkok', '{edm}'::text[], null, null),
  ('lovefest', 'Vrnjačka Banja', '{electronic,techno}'::text[], 'Serbia''s love-themed open-air festival.', null),
  ('hard-summer', 'Los Angeles', '{edm,bass,hiphop}'::text[], 'LA''s genre-blurring bass and hip-hop festival.', null),
  ('snowbombing', 'Mayrhofen', '{electronic,house}'::text[], 'Europe''s original festival on snow, in the Austrian Alps.', 'https://www.snowbombing.com'),
  ('ava', 'Belfast', '{techno,electronic}'::text[], 'Belfast''s electronic music and visual arts festival.', null),
  ('ultra-japan', 'Tokyo', '{edm}'::text[], 'Ultra''s Japanese edition in Odaiba, Tokyo.', null),
  ('les-plages-electroniques', 'Cannes', '{edm,house}'::text[], 'Feet-in-the-sand festival on the beaches of Cannes.', 'https://www.plages-electroniques.com'),
  ('lollapalooza', 'Chicago', '{rock,pop,hiphop,electronic}'::text[], 'The iconic multi-genre festival in Grant Park.', 'https://www.lollapalooza.com'),
  ('vision-colour', null, '{edm,electronic}'::text[], null, null),
  ('hideout', 'Novalja', '{house,techno,bass}'::text[], 'A week of parties on Zrće beach.', null),
  ('djakarta-warehouse-project', 'Jakarta', '{edm}'::text[], 'Southeast Asia''s biggest dance music festival.', 'https://www.djakartawarehouse.com'),
  ('beonix', 'Limassol', '{techno,house}'::text[], 'Cyprus''s large-scale electronic music festival.', null),
  ('lost-village', 'Lincolnshire', '{electronic,house}'::text[], 'An immersive woodland festival of music, food and ideas.', null),
  ('beyond-the-valley', 'Barunah Plains', '{electronic,pop}'::text[], 'Australia''s New Year''s camping festival in Victoria.', null),
  ('untold-dubai', 'Dubai', '{edm,house}'::text[], 'Untold''s spectacular Middle East edition.', null),
  ('groove-cruise', 'Miami', '{house,edm}'::text[], 'The world''s biggest floating dance music festival.', null),
  ('ultra-korea', 'Seoul', '{edm}'::text[], 'Ultra''s Korean edition.', null),
  ('creamfields-chile', 'Santiago', '{edm,techno}'::text[], 'Creamfields'' South American stronghold.', null),
  ('white-party-bangkok', 'Bangkok', '{edm,house}'::text[], null, null),
  ('ultra-taiwan', 'Taipei', '{edm}'::text[], null, null),
  ('love-international', 'Tisno', '{house,techno,disco}'::text[], 'The Garden''s spiritual successor on Tisno bay.', null),
  ('defected-croatia', 'Tisno', '{house}'::text[], 'A week of house music heaven on the Adriatic.', null),
  ('neon-countdown', 'Bangkok', '{edm}'::text[], 'Thailand''s New Year countdown mega-rave.', null),
  ('sonus', 'Novalja', '{techno,house}'::text[], 'Five days of techno on Zrće beach.', null),
  ('nameless', 'Annone di Brianza', '{edm,hiphop}'::text[], 'Italy''s spring EDM opener in Lombardy.', null),
  ('edc-thailand', null, '{edm}'::text[], null, null),
  ('ultra-buenos-aires', 'Buenos Aires', '{edm}'::text[], null, null),
  ('fly-open-air', 'Edinburgh', '{techno,house}'::text[], 'Techno and house in Edinburgh''s historic gardens.', null),
  ('pitch-music-arts', 'Moyston', '{techno,electronic}'::text[], 'Australia''s boutique electronic arts festival.', null),
  ('beyond-wonderland', 'San Bernardino', '{edm,bass}'::text[], 'Insomniac''s fantasy-themed Southern California rave.', null),
  ('ultra-australia', 'Melbourne', '{edm}'::text[], null, null),
  ('glitch', 'Ta'' Qali', '{techno,house}'::text[], 'Malta''s underground electronic festival.', null),
  ('medusa', 'Cullera', '{edm,hardstyle}'::text[], 'Spain''s Mediterranean beach mega-festival.', null),
  ('sunset-by-neon', 'Kuala Lumpur', '{edm}'::text[], null, null),
  ('gmo-sonic', null, '{edm}'::text[], null, null),
  ('soundstorm', 'Riyadh', '{edm,electronic}'::text[], 'MDLBEAST''s colossal desert festival in Riyadh.', 'https://mdlbeast.com'),
  ('beats-for-love', 'Ostrava', '{electronic,dnb,edm}'::text[], 'Czechia''s electronic festival amid industrial heritage at Dolní Vítkovice.', null),
  ('nature-one', 'Kastellaun', '{techno,trance,house}'::text[], 'Germany''s rave institution at a former missile base.', 'https://www.nature-one.de'),
  ('ultra-south-africa', 'Johannesburg', '{edm}'::text[], null, null),
  ('lost-lands', 'Thornville', '{dubstep,bass}'::text[], 'Excision''s dinosaur-themed bass music mecca.', 'https://www.lostlandsfestival.com'),
  ('defected-malta', null, '{house}'::text[], null, null),
  ('verknipt', 'Utrecht', '{techno,hardtechno}'::text[], 'Utrecht''s hard-hitting techno marathon.', null),
  ('iii-points', 'Miami', '{electronic,hiphop,indie}'::text[], 'Miami''s underground music and art festival in Wynwood.', null),
  ('baum', 'Bogotá', '{techno,house}'::text[], 'Colombia''s leading electronic music festival.', null),
  ('balaton-sound', 'Zamárdi', '{edm,house}'::text[], 'A huge open-air on the beach of Lake Balaton.', null),
  ('melt', 'Gräfenhainichen', '{electronic,indie}'::text[], 'Electronic-indie festival among giant mining machines (final edition 2024).', null),
  ('sea-star', 'Umag', '{electronic,edm}'::text[], 'EXIT''s seaside spin-off in Istria.', null),
  ('saga', 'Bucharest', '{edm,house}'::text[], 'Bucharest''s biggest dance music festival.', null),
  ('electric-castle', 'Bonțida', '{electronic,rock,hiphop}'::text[], 'A week of music and art at Transylvania''s Bánffy Castle.', 'https://electriccastle.ro'),
  ('s2o-hong-kong', 'Hong Kong', '{edm}'::text[], null, null),
  ('vh1-supersonic', 'Pune', '{edm,electronic}'::text[], 'India''s multi-genre electronic festival.', null),
  ('creamfields-hong-kong', 'Hong Kong', '{edm}'::text[], null, null),
  ('oasis', 'Marrakech', '{house,techno}'::text[], 'Boutique house and techno getaway in Marrakech.', null),
  ('outlook-origins', 'Tisno', '{bass,dnb,dub}'::text[], 'Soundsystem culture festival on the Adriatic.', null),
  ('sonar-lisboa', 'Lisbon', '{electronic,techno}'::text[], 'Sónar''s Lisbon edition.', null)
) as d(slug, city, genres, description, website)
where f.slug = d.slug;

-- Holy Ship! Wrecked actually takes place in the Dominican Republic
-- (organizer is US-based, which is why DJ Mag lists it as USA).
update public.festivals
set country = 'DO', city = 'Punta Cana'
where slug = 'holy-ship-wrecked';
