-- ============================================================
-- User-requested additions (2026-07-15): Francofolies de La
-- Rochelle (new), Dour Festival (new), Les Vieilles Charrues
-- (new), Thuishaven (new) + complete 2026 lineups for these plus
-- the already-catalogued Francofolies Esch-sur-Alzette and Les
-- Ardentes (which only had partial lineups). Sourced from
-- official festival sites, Wikipedia, Songkick and regional
-- press. Idempotent: upserts on slug / (festival_id, year) /
-- (edition_id, artist_id) — safe to re-run.
-- ============================================================

insert into public.festivals (name, slug, country, city) values
  ('Francofolies de La Rochelle', 'francofolies-la-rochelle', 'FR', 'La Rochelle'),
  ('Dour Festival', 'dour-festival', 'BE', 'Dour'),
  ('Les Vieilles Charrues', 'les-vieilles-charrues', 'FR', 'Carhaix-Plouguer'),
  ('Thuishaven', 'thuishaven', 'NL', 'Amsterdam')
on conflict (slug) do nothing;

insert into public.festival_editions (festival_id, year, start_date, end_date)
select f.id, v.year, v.start_date::date, v.end_date::date
from (values
  ('francofolies-la-rochelle', 2026, '2026-07-10', '2026-07-14'),
  ('dour-festival', 2026, '2026-07-15', '2026-07-19'),
  ('les-vieilles-charrues', 2026, '2026-07-16', '2026-07-19'),
  ('thuishaven', 2026, '2026-05-16', '2026-05-16')
) as v(slug, year, start_date, end_date)
join public.festivals f on f.slug = v.slug
on conflict (festival_id, year) do update
  set start_date = excluded.start_date, end_date = excluded.end_date;

insert into public.artists (name)
select v.name
from (values
  ('Macklemore'),
  ('Gims'),
  ('PLK'),
  ('Niska'),
  ('Christophe Maé'),
  ('Feu! Chatterton'),
  ('Helena'),
  ('Miki'),
  ('Luiza'),
  ('La Mano 1.9'),
  ('Cassius Club'),
  ('Fatal Bazooka'),
  ('Mosimann'),
  ('L2B'),
  ('Sam Sauvage'),
  ('Zinée'),
  ('Ninon'),
  ('Adam El Mouna'),
  ('Marcy'),
  ('Dori'),
  ('Nosi Live Series'),
  ('Zebramix'),
  ('Terrenoire (avec l''Orchestre du Conservatoire d''Esch-sur-Alzette)'),
  ('O.B.F x Sr Wilson x Junior Roy'),
  ('Little Lion Sound'),
  ('Sumac Dub'),
  ('LXB Monkeys & Jahbotaï'),
  ('Youssou Ndour'),
  ('Zaz'),
  ('Léman'),
  ('Hina'),
  ('Félix Radu'),
  ('Sorosoro'),
  ('Agnès Jaoui'),
  ('Clarisse Lavanant'),
  ('Jok''air'),
  ('Yael Naim'),
  ('Keren Ann'),
  ('MPL'),
  ('La Traversée'),
  ('Tout le monde s''appelle Clara'),
  ('Teddybear'),
  ('Christophe Mali'),
  ('Brieg Guerveno'),
  ('Bienvenue Chez Yvan'),
  ('Bodie'),
  ('Odezenne'),
  ('Attention le tapis prend feu'),
  ('Orelsan'),
  ('Gaël Faye'),
  ('Skip The Use'),
  ('Vincent Delerm'),
  ('Vincent Dedienne'),
  ('Emily Loizeau'),
  ('Superpoze'),
  ('Bellboy'),
  ('Lisa Claudie'),
  ('Cocanha'),
  ('Peio Serbielle'),
  ('(French) Stories From Nashville'),
  ('Augusta'),
  ('Aya Nakamura'),
  ('Louane'),
  ('Marguerite'),
  ('Hugues Aufray'),
  ('Raphaël'),
  ('Salebarbes'),
  ('Piche'),
  ('Anaïs Rosso'),
  ('Billie'),
  ('Sylvain Duthu'),
  ('Lili Em'),
  ('Urumi'),
  ('Michel Hubert'),
  ('Ouai Stéphane'),
  ('Perceval'),
  ('Dafné Kritharas'),
  ('Mika'),
  ('Gaëtan Roussel'),
  ('Julien Clerc'),
  ('Rau_ze'),
  ('Ino Casablanca'),
  ('Anne Paceo'),
  ('Blou Feet'),
  ('Noée'),
  ('Rose'),
  ('Ravage'),
  ('Et si on chantait ?'),
  ('Boys Noize'),
  ('SPFDJ'),
  ('DJ Gigola'),
  ('PETERBLUE'),
  ('Durdenhauer'),
  ('Mika Heggemann'),
  ('Fenrick'),
  ('Emilija'),
  ('ISHA'),
  ('Limsa d''Aulnay'),
  ('Yvnnis'),
  ('Agobun Sound System'),
  ('Barako Bahamas'),
  ('DJ Cagna'),
  ('Earl Sixteen'),
  ('Grünt'),
  ('Ras Ladji'),
  ('La Roue'),
  ('La Scarpetta'),
  ('Laure Croft'),
  ('FUMI'),
  ('DJ Nathachelet'),
  ('Niko Hoke'),
  ('John Gilliot'),
  ('Reemshot'),
  ('Relajadita'),
  ('GIØ'),
  ('Sherifflazone'),
  ('Thomaslovefashionverviers'),
  ('Alonzo'),
  ('Amelie Lens'),
  ('Caribou'),
  ('Holy Priest'),
  ('Vald'),
  ('Vladimir Cauchemar'),
  ('Todiefor'),
  ('Zwangere Guy'),
  ('Charlie Sparks'),
  ('Hamdi'),
  ('KUKO'),
  ('Myd'),
  ('Onlynumbers'),
  ('Roland Cristal'),
  ('Rudimental'),
  ('Alpha Steppa'),
  ('Nai-Jah'),
  ('Béesau'),
  ('Blu Samu'),
  ('Boko Yout'),
  ('BYØRN'),
  ('Caravel'),
  ('Djaydub'),
  ('Dhazed'),
  ('Daddy Cookiz'),
  ('Gea'),
  ('Kaba'),
  ('Hyas'),
  ('King Alpha'),
  ('Fikir Amlak'),
  ('LESSSS'),
  ('LinLin'),
  ('LVDV'),
  ('Maissouille'),
  ('Radium'),
  ('Marie-Julie'),
  ('Nups3E'),
  ('SINAI'),
  ('Sköne'),
  ('Nmss'),
  ('Vera Moro'),
  ('Ricky Corazón'),
  ('YĪN YĪN'),
  ('Apashe'),
  ('Biga*Ranx'),
  ('Chris Stussy'),
  ('Guy2Bezbar'),
  ('Oklou'),
  ('Sammy Virji'),
  ('Bambounou'),
  ('Buraka Som Sistema'),
  ('Danyl'),
  ('Favé'),
  ('HAAi'),
  ('Mechatok'),
  ('Miss Bashful'),
  ('Peaches'),
  ('Sama'' Abdulhadi'),
  ('Smerz'),
  ('Swimming Paul'),
  ('Yoa'),
  ('Ão'),
  ('Camille Yembe'),
  ('Clara D'),
  ('DJ Schnake'),
  ('Frost Children'),
  ('Godson'),
  ('Hanamercy'),
  ('JAEL'),
  ('Telly'),
  ('Jeune Morty'),
  ('Keiyaa'),
  ('Khadija Al Hanafi'),
  ('Kingstep'),
  ('Ramon Judah'),
  ('Laura De Greef'),
  ('Lefto Early Bird'),
  ('Lewis Bennett'),
  ('Magi Merlin'),
  ('Mathilde Fernandez'),
  ('Pili Pili Girls'),
  ('Skarra Mucci'),
  ('Manudigital'),
  ('Tatyana Jane'),
  ('Damso'),
  ('Disiz'),
  ('Funk Tribu'),
  ('Meryl'),
  ('Original Koffee'),
  ('TOMORA'),
  ('Ultra Vomit'),
  ('2HOT2PLAY'),
  ('Benwal'),
  ('Blawan'),
  ('Bob Vylan'),
  ('COBRAH'),
  ('Fat Dog'),
  ('horsegiirL'),
  ('PERCEVAL'),
  ('R2'),
  ('Adult DVD'),
  ('Aunty Rayzor'),
  ('ELLiS·D'),
  ('FLKN'),
  ('Huntrill'),
  ('Jahtari'),
  ('Goldie'),
  ('Medic MC'),
  ('Speng Bond'),
  ('Kirara'),
  ('Le Motel'),
  ('Lézard'),
  ('Marhu'),
  ('Marina P'),
  ('Eeyun Purkins'),
  ('Pretty Much Average'),
  ('Rrita Jashari'),
  ('Abzu'),
  ('Aziza Jaye'),
  ('Théa'),
  ('TVOD'),
  ('Unicorn On Ketamine'),
  ('Cloudy'),
  ('Honey Dijon'),
  ('Interpol'),
  ('MAU P'),
  ('Pendulum'),
  ('Quavo'),
  ('Sean Paul'),
  ('Trym'),
  ('Alignment'),
  ('Amenra'),
  ('Ghinzu'),
  ('High Vis'),
  ('Hybrid Minds'),
  ('Sleaford Mods'),
  ('Teki Latex'),
  ('Neffa-T'),
  ('Young Miko'),
  ('A6el'),
  ('Aba Shanti-I'),
  ('Azzi On The Beat'),
  ('Betical'),
  ('Elea'),
  ('Elisethere'),
  ('Maliman'),
  ('Eosine'),
  ('Himra'),
  ('Kaat Van Stralen'),
  ('La Sécurité'),
  ('LAURAVIOLI'),
  ('mad miran'),
  ('Maïcee'),
  ('MEK''DR''DR'),
  ('Militarie Gun'),
  ('Roll & Record'),
  ('Alpha Pup'),
  ('Sòn du maquís'),
  ('The Experimental Tropic Blues Band'),
  ('VMO (Violent Magic Orchestra)'),
  ('Weeding Dub'),
  ('Playboi Carti'),
  ('Black Eyed Peas'),
  ('Future'),
  ('DAMSO'),
  ('Theodora'),
  ('Vald x Vladimir Cauchemar x Todiefor'),
  ('Destroy Lonely'),
  ('Riles'),
  ('Ascendant Vierge'),
  ('Fianso'),
  ('El Grande Toto'),
  ('Homixide Gang'),
  ('Houdi'),
  ('Lujipeka'),
  ('Rambo Goyard'),
  ('So La Lune'),
  ('Von Bikrav x Todiefor'),
  ('2L'),
  ('Adés the Planet'),
  ('Martin Vachiery x Richard Sexuel'),
  ('Samuel Moriero'),
  ('Yaniss – Le Rap en Mieux x Nysos'),
  ('Jacidorex'),
  ('Doria'),
  ('Sasso'),
  ('Sky'),
  ('William Luck'),
  ('Nøname'),
  ('Changeline'),
  ('Richie Beats'),
  ('IMA'),
  ('Neissy'),
  ('LY'),
  ('Kerysha'),
  ('63OG'),
  ('Junior'),
  ('DJ Sebb'),
  ('Bigkid for Blankka Club'),
  ('Lost Frequencies'),
  ('I Hate Models'),
  ('Kaaris'),
  ('Jolagreen23'),
  ('Kybba'),
  ('Leto'),
  ('Naza'),
  ('Rohff'),
  ('47ter'),
  ('Folie''s'),
  ('Georgio'),
  ('Monsieur Nov'),
  ('Sinik'),
  ('Sniper'),
  ('21AM Curation'),
  ('Timar'),
  ('Absolem'),
  ('Eve La Marka'),
  ('Martin Vachiery'),
  ('Tribal Kush'),
  ('Yuki Chiba'),
  ('Crystallmess'),
  ('Waïv'),
  ('Shannon'),
  ('Hysta'),
  ('Paul Seul'),
  ('Omaks'),
  ('Belgianly Made'),
  ('Byørn'),
  ('Rakim'),
  ('Marielou'),
  ('DJ Bea'),
  ('Djadja & Dinaz'),
  ('Genezio'),
  ('Kalash Criminel'),
  ('La Rvfleuze'),
  ('Menace Santana'),
  ('TK'),
  ('Xvbarbar'),
  ('ZKR'),
  ('Creeds'),
  ('Malaa x Alter Ego'),
  ('Smokedope2016'),
  ('Darlingchouchou'),
  ('Zed'),
  ('GT1boiavantcsurr'),
  ('Dumb'),
  ('XO'),
  ('TDJ'),
  ('Panteros666'),
  ('Dakeez'),
  ('Part Time Killer'),
  ('Matrakk B2B Part Time Killer'),
  ('Notinbed'),
  ('Matrakk'),
  ('Check Club'),
  ('Al-Walid'),
  ('LB aka Labat'),
  ('TH'),
  ('Spheres Sonores x La Draft'),
  ('Moneyboys Soundsystem'),
  ('EGO8'),
  ('Encore Une Autre'),
  ('Charlotte de Witte'),
  ('Josman'),
  ('Bigflo & Oli'),
  ('Esdeekid'),
  ('Nico Moreno'),
  ('La Fouine'),
  ('Nono La Grinta'),
  ('Carbonne'),
  ('Ebony'),
  ('Rsko'),
  ('Trinix'),
  ('Boutcha Bwa'),
  ('22Heures30'),
  ('Django'),
  ('La Hasba22'),
  ('Vortek''s'),
  ('Lushe'),
  ('Madpace'),
  ('Natte Visstick'),
  ('Fresh La Douille'),
  ('Le Crime'),
  ('Asdek x Kaaz'),
  ('OG Wizdom'),
  ('Bloody$anji'),
  ('Matou'),
  ('Spectra'),
  ('Anyme et Ses Potes'),
  ('Katy Perry'),
  ('Iliona'),
  ('Upsilone'),
  ('Nick Cave & The Bad Seeds'),
  ('Jean-Louis Aubert'),
  ('Patrick Watson'),
  ('Joy Crookes'),
  ('Jehnny Beth'),
  ('Bonne Nuit'),
  ('Jasmine Not Jafar'),
  ('Ne Rangez Pas Les Jardins'),
  ('Jetlag Gang'),
  ('Lalalar'),
  ('Super Parquet'),
  ('Cap Kozmik'),
  ('Lovana'),
  ('Dub Inc'),
  ('Yelle'),
  ('Cassius'),
  ('Sprints'),
  ('Asfar Shamsi'),
  ('Olli & The London Radio Pop Orchestra'),
  ('No Pain No Pain'),
  ('Djazia Satour'),
  ('Galant Tu Perds Ton Temps'),
  ('Gregailh'),
  ('Enneade'),
  ('Zord'),
  ('Kelt''Duo'),
  ('Maden'),
  ('Vanessa Paradis'),
  ('Rilès'),
  ('Suzane'),
  ('Miossec'),
  ('Maureen'),
  ('Tomora'),
  ('Xavier Rudd'),
  ('47 Ter'),
  ('Pact (Joachim Pastor, Joris Delacroix, Teho)'),
  ('Goodbye Karelle'),
  ('Tvod'),
  ('Lindigo'),
  ('Isam Elias'),
  ('Grand Ensemble Filos'),
  ('Plouz & Foen'),
  ('Luis Ripa'),
  ('Michel de Hey'),
  ('Tsepo'),
  ('Dr Dubplate'),
  ('Locklead'),
  ('Nathan Homan'),
  ('Suze Ijó'),
  ('M-High'),
  ('Fafi Abdel Nour'),
  ('Merel Helderman'),
  ('Solit'),
  ('Camille Doe'),
  ('PHIA'),
  ('Job de Jong')
) as v(name)
where not exists (
  select 1 from public.artists a where lower(a.name) = lower(v.name)
);

with lineup(slug, artist_name, order_index) as (
  values
    ('francofolies-esch', 'Macklemore', 0),
    ('francofolies-esch', 'Gims', 1),
    ('francofolies-esch', 'PLK', 2),
    ('francofolies-esch', 'Niska', 3),
    ('francofolies-esch', 'Christophe Maé', 4),
    ('francofolies-esch', 'Feu! Chatterton', 5),
    ('francofolies-esch', 'Helena', 6),
    ('francofolies-esch', 'Miki', 7),
    ('francofolies-esch', 'Luiza', 8),
    ('francofolies-esch', 'La Mano 1.9', 9),
    ('francofolies-esch', 'Cassius Club', 10),
    ('francofolies-esch', 'Fatal Bazooka', 11),
    ('francofolies-esch', 'Mosimann', 12),
    ('francofolies-esch', 'L2B', 13),
    ('francofolies-esch', 'Sam Sauvage', 14),
    ('francofolies-esch', 'Zinée', 15),
    ('francofolies-esch', 'Ninon', 16),
    ('francofolies-esch', 'Adam El Mouna', 17),
    ('francofolies-esch', 'Marcy', 18),
    ('francofolies-esch', 'Dori', 19),
    ('francofolies-esch', 'Nosi Live Series', 20),
    ('francofolies-esch', 'Zebramix', 21),
    ('francofolies-esch', 'Terrenoire (avec l''Orchestre du Conservatoire d''Esch-sur-Alzette)', 22),
    ('francofolies-esch', 'O.B.F x Sr Wilson x Junior Roy', 23),
    ('francofolies-esch', 'Little Lion Sound', 24),
    ('francofolies-esch', 'Sumac Dub', 25),
    ('francofolies-esch', 'LXB Monkeys & Jahbotaï', 26),
    ('francofolies-la-rochelle', 'Gims', 0),
    ('francofolies-la-rochelle', 'Youssou Ndour', 1),
    ('francofolies-la-rochelle', 'Zaz', 2),
    ('francofolies-la-rochelle', 'Luiza', 3),
    ('francofolies-la-rochelle', 'Léman', 4),
    ('francofolies-la-rochelle', 'Hina', 5),
    ('francofolies-la-rochelle', 'Félix Radu', 6),
    ('francofolies-la-rochelle', 'Sorosoro', 7),
    ('francofolies-la-rochelle', 'Agnès Jaoui', 8),
    ('francofolies-la-rochelle', 'Clarisse Lavanant', 9),
    ('francofolies-la-rochelle', 'Niska', 10),
    ('francofolies-la-rochelle', 'Jok''air', 11),
    ('francofolies-la-rochelle', 'L2B', 12),
    ('francofolies-la-rochelle', 'La Mano 1.9', 13),
    ('francofolies-la-rochelle', 'Yael Naim', 14),
    ('francofolies-la-rochelle', 'Keren Ann', 15),
    ('francofolies-la-rochelle', 'MPL', 16),
    ('francofolies-la-rochelle', 'La Traversée', 17),
    ('francofolies-la-rochelle', 'Tout le monde s''appelle Clara', 18),
    ('francofolies-la-rochelle', 'Teddybear', 19),
    ('francofolies-la-rochelle', 'Christophe Mali', 20),
    ('francofolies-la-rochelle', 'Brieg Guerveno', 21),
    ('francofolies-la-rochelle', 'Bienvenue Chez Yvan', 22),
    ('francofolies-la-rochelle', 'Bodie', 23),
    ('francofolies-la-rochelle', 'Odezenne', 24),
    ('francofolies-la-rochelle', 'Attention le tapis prend feu', 25),
    ('francofolies-la-rochelle', 'Orelsan', 26),
    ('francofolies-la-rochelle', 'Gaël Faye', 27),
    ('francofolies-la-rochelle', 'Miki', 28),
    ('francofolies-la-rochelle', 'Skip The Use', 29),
    ('francofolies-la-rochelle', 'Vincent Delerm', 30),
    ('francofolies-la-rochelle', 'Vincent Dedienne', 31),
    ('francofolies-la-rochelle', 'Emily Loizeau', 32),
    ('francofolies-la-rochelle', 'Superpoze', 33),
    ('francofolies-la-rochelle', 'Bellboy', 34),
    ('francofolies-la-rochelle', 'Lisa Claudie', 35),
    ('francofolies-la-rochelle', 'Cocanha', 36),
    ('francofolies-la-rochelle', 'Peio Serbielle', 37),
    ('francofolies-la-rochelle', '(French) Stories From Nashville', 38),
    ('francofolies-la-rochelle', 'Augusta', 39),
    ('francofolies-la-rochelle', 'Aya Nakamura', 40),
    ('francofolies-la-rochelle', 'Helena', 41),
    ('francofolies-la-rochelle', 'Louane', 42),
    ('francofolies-la-rochelle', 'Marguerite', 43),
    ('francofolies-la-rochelle', 'Hugues Aufray', 44),
    ('francofolies-la-rochelle', 'Raphaël', 45),
    ('francofolies-la-rochelle', 'Salebarbes', 46),
    ('francofolies-la-rochelle', 'Piche', 47),
    ('francofolies-la-rochelle', 'Anaïs Rosso', 48),
    ('francofolies-la-rochelle', 'Billie', 49),
    ('francofolies-la-rochelle', 'Sylvain Duthu', 50),
    ('francofolies-la-rochelle', 'Lili Em', 51),
    ('francofolies-la-rochelle', 'Urumi', 52),
    ('francofolies-la-rochelle', 'Michel Hubert', 53),
    ('francofolies-la-rochelle', 'Ouai Stéphane', 54),
    ('francofolies-la-rochelle', 'Perceval', 55),
    ('francofolies-la-rochelle', 'Dafné Kritharas', 56),
    ('francofolies-la-rochelle', 'Mika', 57),
    ('francofolies-la-rochelle', 'Feu! Chatterton', 58),
    ('francofolies-la-rochelle', 'Gaëtan Roussel', 59),
    ('francofolies-la-rochelle', 'Sam Sauvage', 60),
    ('francofolies-la-rochelle', 'Julien Clerc', 61),
    ('francofolies-la-rochelle', 'Rau_ze', 62),
    ('francofolies-la-rochelle', 'Ino Casablanca', 63),
    ('francofolies-la-rochelle', 'Anne Paceo', 64),
    ('francofolies-la-rochelle', 'Blou Feet', 65),
    ('francofolies-la-rochelle', 'Noée', 66),
    ('francofolies-la-rochelle', 'Rose', 67),
    ('francofolies-la-rochelle', 'Ravage', 68),
    ('francofolies-la-rochelle', 'Et si on chantait ?', 69),
    ('dour-festival', 'Boys Noize', 0),
    ('dour-festival', 'SPFDJ', 1),
    ('dour-festival', 'DJ Gigola', 2),
    ('dour-festival', 'PETERBLUE', 3),
    ('dour-festival', 'Durdenhauer', 4),
    ('dour-festival', 'Mika Heggemann', 5),
    ('dour-festival', 'Fenrick', 6),
    ('dour-festival', 'Emilija', 7),
    ('dour-festival', 'ISHA', 8),
    ('dour-festival', 'Limsa d''Aulnay', 9),
    ('dour-festival', 'Yvnnis', 10),
    ('dour-festival', 'Agobun Sound System', 11),
    ('dour-festival', 'Barako Bahamas', 12),
    ('dour-festival', 'DJ Cagna', 13),
    ('dour-festival', 'Earl Sixteen', 14),
    ('dour-festival', 'Grünt', 15),
    ('dour-festival', 'Ras Ladji', 16),
    ('dour-festival', 'La Roue', 17),
    ('dour-festival', 'La Scarpetta', 18),
    ('dour-festival', 'Laure Croft', 19),
    ('dour-festival', 'FUMI', 20),
    ('dour-festival', 'DJ Nathachelet', 21),
    ('dour-festival', 'Niko Hoke', 22),
    ('dour-festival', 'John Gilliot', 23),
    ('dour-festival', 'Reemshot', 24),
    ('dour-festival', 'Relajadita', 25),
    ('dour-festival', 'GIØ', 26),
    ('dour-festival', 'Sherifflazone', 27),
    ('dour-festival', 'Thomaslovefashionverviers', 28),
    ('dour-festival', 'Zinée', 29),
    ('dour-festival', 'Alonzo', 30),
    ('dour-festival', 'Amelie Lens', 31),
    ('dour-festival', 'Caribou', 32),
    ('dour-festival', 'Holy Priest', 33),
    ('dour-festival', 'Vald', 34),
    ('dour-festival', 'Vladimir Cauchemar', 35),
    ('dour-festival', 'Todiefor', 36),
    ('dour-festival', 'Zwangere Guy', 37),
    ('dour-festival', 'Charlie Sparks', 38),
    ('dour-festival', 'Hamdi', 39),
    ('dour-festival', 'Ino Casablanca', 40),
    ('dour-festival', 'KUKO', 41),
    ('dour-festival', 'Myd', 42),
    ('dour-festival', 'Onlynumbers', 43),
    ('dour-festival', 'Roland Cristal', 44),
    ('dour-festival', 'Rudimental', 45),
    ('dour-festival', 'Alpha Steppa', 46),
    ('dour-festival', 'Nai-Jah', 47),
    ('dour-festival', 'Béesau', 48),
    ('dour-festival', 'Blu Samu', 49),
    ('dour-festival', 'Boko Yout', 50),
    ('dour-festival', 'BYØRN', 51),
    ('dour-festival', 'Caravel', 52),
    ('dour-festival', 'Djaydub', 53),
    ('dour-festival', 'Dhazed', 54),
    ('dour-festival', 'Daddy Cookiz', 55),
    ('dour-festival', 'Gea', 56),
    ('dour-festival', 'Kaba', 57),
    ('dour-festival', 'Hyas', 58),
    ('dour-festival', 'King Alpha', 59),
    ('dour-festival', 'Fikir Amlak', 60),
    ('dour-festival', 'LESSSS', 61),
    ('dour-festival', 'LinLin', 62),
    ('dour-festival', 'LVDV', 63),
    ('dour-festival', 'Maissouille', 64),
    ('dour-festival', 'Radium', 65),
    ('dour-festival', 'Marie-Julie', 66),
    ('dour-festival', 'Nups3E', 67),
    ('dour-festival', 'SINAI', 68),
    ('dour-festival', 'Sköne', 69),
    ('dour-festival', 'Nmss', 70),
    ('dour-festival', 'Vera Moro', 71),
    ('dour-festival', 'Ricky Corazón', 72),
    ('dour-festival', 'YĪN YĪN', 73),
    ('dour-festival', 'Apashe', 74),
    ('dour-festival', 'Biga*Ranx', 75),
    ('dour-festival', 'Chris Stussy', 76),
    ('dour-festival', 'Guy2Bezbar', 77),
    ('dour-festival', 'Oklou', 78),
    ('dour-festival', 'Orelsan', 79),
    ('dour-festival', 'Sammy Virji', 80),
    ('dour-festival', 'Bambounou', 81),
    ('dour-festival', 'Buraka Som Sistema', 82),
    ('dour-festival', 'Danyl', 83),
    ('dour-festival', 'Favé', 84),
    ('dour-festival', 'HAAi', 85),
    ('dour-festival', 'Mechatok', 86),
    ('dour-festival', 'Miss Bashful', 87),
    ('dour-festival', 'Peaches', 88),
    ('dour-festival', 'Sama'' Abdulhadi', 89),
    ('dour-festival', 'Smerz', 90),
    ('dour-festival', 'Swimming Paul', 91),
    ('dour-festival', 'Yoa', 92),
    ('dour-festival', 'Ão', 93),
    ('dour-festival', 'Camille Yembe', 94),
    ('dour-festival', 'Clara D', 95),
    ('dour-festival', 'DJ Schnake', 96),
    ('dour-festival', 'Frost Children', 97),
    ('dour-festival', 'Godson', 98),
    ('dour-festival', 'Hanamercy', 99),
    ('dour-festival', 'JAEL', 100),
    ('dour-festival', 'Telly', 101),
    ('dour-festival', 'Jeune Morty', 102),
    ('dour-festival', 'Keiyaa', 103),
    ('dour-festival', 'Khadija Al Hanafi', 104),
    ('dour-festival', 'Kingstep', 105),
    ('dour-festival', 'Ramon Judah', 106),
    ('dour-festival', 'Laura De Greef', 107),
    ('dour-festival', 'Lefto Early Bird', 108),
    ('dour-festival', 'Lewis Bennett', 109),
    ('dour-festival', 'Magi Merlin', 110),
    ('dour-festival', 'Mathilde Fernandez', 111),
    ('dour-festival', 'Pili Pili Girls', 112),
    ('dour-festival', 'Skarra Mucci', 113),
    ('dour-festival', 'Manudigital', 114),
    ('dour-festival', 'Tatyana Jane', 115),
    ('dour-festival', 'Urumi', 116),
    ('dour-festival', 'Damso', 117),
    ('dour-festival', 'Disiz', 118),
    ('dour-festival', 'Funk Tribu', 119),
    ('dour-festival', 'Meryl', 120),
    ('dour-festival', 'Original Koffee', 121),
    ('dour-festival', 'TOMORA', 122),
    ('dour-festival', 'Ultra Vomit', 123),
    ('dour-festival', '2HOT2PLAY', 124),
    ('dour-festival', 'Benwal', 125),
    ('dour-festival', 'Blawan', 126),
    ('dour-festival', 'Bob Vylan', 127),
    ('dour-festival', 'COBRAH', 128),
    ('dour-festival', 'Fat Dog', 129),
    ('dour-festival', 'horsegiirL', 130),
    ('dour-festival', 'PERCEVAL', 131),
    ('dour-festival', 'R2', 132),
    ('dour-festival', 'Adult DVD', 133),
    ('dour-festival', 'Aunty Rayzor', 134),
    ('dour-festival', 'ELLiS·D', 135),
    ('dour-festival', 'FLKN', 136),
    ('dour-festival', 'Huntrill', 137),
    ('dour-festival', 'Jahtari', 138),
    ('dour-festival', 'Goldie', 139),
    ('dour-festival', 'Medic MC', 140),
    ('dour-festival', 'Speng Bond', 141),
    ('dour-festival', 'Kirara', 142),
    ('dour-festival', 'Le Motel', 143),
    ('dour-festival', 'Lézard', 144),
    ('dour-festival', 'Marhu', 145),
    ('dour-festival', 'Marina P', 146),
    ('dour-festival', 'Eeyun Purkins', 147),
    ('dour-festival', 'Pretty Much Average', 148),
    ('dour-festival', 'Rrita Jashari', 149),
    ('dour-festival', 'Abzu', 150),
    ('dour-festival', 'Aziza Jaye', 151),
    ('dour-festival', 'Théa', 152),
    ('dour-festival', 'TVOD', 153),
    ('dour-festival', 'Unicorn On Ketamine', 154),
    ('dour-festival', 'Cloudy', 155),
    ('dour-festival', 'Honey Dijon', 156),
    ('dour-festival', 'Interpol', 157),
    ('dour-festival', 'L2B', 158),
    ('dour-festival', 'MAU P', 159),
    ('dour-festival', 'Pendulum', 160),
    ('dour-festival', 'Quavo', 161),
    ('dour-festival', 'Sean Paul', 162),
    ('dour-festival', 'Trym', 163),
    ('dour-festival', 'Alignment', 164),
    ('dour-festival', 'Amenra', 165),
    ('dour-festival', 'Ghinzu', 166),
    ('dour-festival', 'High Vis', 167),
    ('dour-festival', 'Hybrid Minds', 168),
    ('dour-festival', 'Odezenne', 169),
    ('dour-festival', 'Sleaford Mods', 170),
    ('dour-festival', 'Teki Latex', 171),
    ('dour-festival', 'Neffa-T', 172),
    ('dour-festival', 'Young Miko', 173),
    ('dour-festival', 'A6el', 174),
    ('dour-festival', 'Aba Shanti-I', 175),
    ('dour-festival', 'Azzi On The Beat', 176),
    ('dour-festival', 'Betical', 177),
    ('dour-festival', 'Elea', 178),
    ('dour-festival', 'Elisethere', 179),
    ('dour-festival', 'Maliman', 180),
    ('dour-festival', 'Eosine', 181),
    ('dour-festival', 'Himra', 182),
    ('dour-festival', 'Kaat Van Stralen', 183),
    ('dour-festival', 'La Sécurité', 184),
    ('dour-festival', 'LAURAVIOLI', 185),
    ('dour-festival', 'mad miran', 186),
    ('dour-festival', 'Maïcee', 187),
    ('dour-festival', 'MEK''DR''DR', 188),
    ('dour-festival', 'Militarie Gun', 189),
    ('dour-festival', 'Roll & Record', 190),
    ('dour-festival', 'Alpha Pup', 191),
    ('dour-festival', 'Sòn du maquís', 192),
    ('dour-festival', 'The Experimental Tropic Blues Band', 193),
    ('dour-festival', 'VMO (Violent Magic Orchestra)', 194),
    ('dour-festival', 'Weeding Dub', 195),
    ('les-ardentes', 'Playboi Carti', 0),
    ('les-ardentes', 'Black Eyed Peas', 1),
    ('les-ardentes', 'Future', 2),
    ('les-ardentes', 'DAMSO', 3),
    ('les-ardentes', 'Theodora', 4),
    ('les-ardentes', 'Vald x Vladimir Cauchemar x Todiefor', 5),
    ('les-ardentes', 'Destroy Lonely', 6),
    ('les-ardentes', 'Niska', 7),
    ('les-ardentes', 'Riles', 8),
    ('les-ardentes', 'Ascendant Vierge', 9),
    ('les-ardentes', 'Fianso', 10),
    ('les-ardentes', 'El Grande Toto', 11),
    ('les-ardentes', 'Homixide Gang', 12),
    ('les-ardentes', 'Houdi', 13),
    ('les-ardentes', 'Lujipeka', 14),
    ('les-ardentes', 'Rambo Goyard', 15),
    ('les-ardentes', 'So La Lune', 16),
    ('les-ardentes', 'Von Bikrav x Todiefor', 17),
    ('les-ardentes', '2L', 18),
    ('les-ardentes', 'Adés the Planet', 19),
    ('les-ardentes', 'Martin Vachiery x Richard Sexuel', 20),
    ('les-ardentes', 'Samuel Moriero', 21),
    ('les-ardentes', 'Yaniss – Le Rap en Mieux x Nysos', 22),
    ('les-ardentes', 'Jacidorex', 23),
    ('les-ardentes', 'Doria', 24),
    ('les-ardentes', 'Sasso', 25),
    ('les-ardentes', 'Sky', 26),
    ('les-ardentes', 'William Luck', 27),
    ('les-ardentes', 'Nøname', 28),
    ('les-ardentes', 'Changeline', 29),
    ('les-ardentes', 'Richie Beats', 30),
    ('les-ardentes', 'IMA', 31),
    ('les-ardentes', 'Neissy', 32),
    ('les-ardentes', 'LY', 33),
    ('les-ardentes', 'Kerysha', 34),
    ('les-ardentes', '63OG', 35),
    ('les-ardentes', 'Junior', 36),
    ('les-ardentes', 'DJ Sebb', 37),
    ('les-ardentes', 'Bigkid for Blankka Club', 38),
    ('les-ardentes', 'Aya Nakamura', 39),
    ('les-ardentes', 'Lost Frequencies', 40),
    ('les-ardentes', 'I Hate Models', 41),
    ('les-ardentes', 'Kaaris', 42),
    ('les-ardentes', 'Jolagreen23', 43),
    ('les-ardentes', 'Kybba', 44),
    ('les-ardentes', 'Leto', 45),
    ('les-ardentes', 'Naza', 46),
    ('les-ardentes', 'Rohff', 47),
    ('les-ardentes', '47ter', 48),
    ('les-ardentes', 'Folie''s', 49),
    ('les-ardentes', 'Georgio', 50),
    ('les-ardentes', 'Monsieur Nov', 51),
    ('les-ardentes', 'Sinik', 52),
    ('les-ardentes', 'Sniper', 53),
    ('les-ardentes', '21AM Curation', 54),
    ('les-ardentes', 'Timar', 55),
    ('les-ardentes', 'Absolem', 56),
    ('les-ardentes', 'Eve La Marka', 57),
    ('les-ardentes', 'Martin Vachiery', 58),
    ('les-ardentes', 'Tribal Kush', 59),
    ('les-ardentes', 'Yuki Chiba', 60),
    ('les-ardentes', 'Crystallmess', 61),
    ('les-ardentes', 'Waïv', 62),
    ('les-ardentes', 'Shannon', 63),
    ('les-ardentes', 'Hysta', 64),
    ('les-ardentes', 'Paul Seul', 65),
    ('les-ardentes', 'Omaks', 66),
    ('les-ardentes', 'Belgianly Made', 67),
    ('les-ardentes', 'Byørn', 68),
    ('les-ardentes', 'Rakim', 69),
    ('les-ardentes', 'Marielou', 70),
    ('les-ardentes', 'DJ Bea', 71),
    ('les-ardentes', 'L2B', 72),
    ('les-ardentes', 'Djadja & Dinaz', 73),
    ('les-ardentes', 'Holy Priest', 74),
    ('les-ardentes', 'Genezio', 75),
    ('les-ardentes', 'Kalash Criminel', 76),
    ('les-ardentes', 'La Mano 1.9', 77),
    ('les-ardentes', 'La Rvfleuze', 78),
    ('les-ardentes', 'Menace Santana', 79),
    ('les-ardentes', 'R2', 80),
    ('les-ardentes', 'TK', 81),
    ('les-ardentes', 'Xvbarbar', 82),
    ('les-ardentes', 'ZKR', 83),
    ('les-ardentes', 'Creeds', 84),
    ('les-ardentes', 'Malaa x Alter Ego', 85),
    ('les-ardentes', 'Smokedope2016', 86),
    ('les-ardentes', 'Darlingchouchou', 87),
    ('les-ardentes', 'Zed', 88),
    ('les-ardentes', 'GT1boiavantcsurr', 89),
    ('les-ardentes', 'Dumb', 90),
    ('les-ardentes', 'XO', 91),
    ('les-ardentes', 'TDJ', 92),
    ('les-ardentes', 'Panteros666', 93),
    ('les-ardentes', 'Dakeez', 94),
    ('les-ardentes', 'Part Time Killer', 95),
    ('les-ardentes', 'Matrakk B2B Part Time Killer', 96),
    ('les-ardentes', 'Notinbed', 97),
    ('les-ardentes', 'Matrakk', 98),
    ('les-ardentes', 'Check Club', 99),
    ('les-ardentes', 'Al-Walid', 100),
    ('les-ardentes', 'LB aka Labat', 101),
    ('les-ardentes', 'TH', 102),
    ('les-ardentes', 'Sherifflazone', 103),
    ('les-ardentes', 'Spheres Sonores x La Draft', 104),
    ('les-ardentes', 'Moneyboys Soundsystem', 105),
    ('les-ardentes', 'EGO8', 106),
    ('les-ardentes', 'Encore Une Autre', 107),
    ('les-ardentes', 'PLK', 108),
    ('les-ardentes', 'Charlotte de Witte', 109),
    ('les-ardentes', 'Josman', 110),
    ('les-ardentes', 'Bigflo & Oli', 111),
    ('les-ardentes', 'Esdeekid', 112),
    ('les-ardentes', 'Nico Moreno', 113),
    ('les-ardentes', 'La Fouine', 114),
    ('les-ardentes', 'Nono La Grinta', 115),
    ('les-ardentes', 'Carbonne', 116),
    ('les-ardentes', 'Ebony', 117),
    ('les-ardentes', 'Miki', 118),
    ('les-ardentes', 'Rsko', 119),
    ('les-ardentes', 'Trinix', 120),
    ('les-ardentes', 'Boutcha Bwa', 121),
    ('les-ardentes', '22Heures30', 122),
    ('les-ardentes', 'Django', 123),
    ('les-ardentes', 'La Hasba22', 124),
    ('les-ardentes', 'Vortek''s', 125),
    ('les-ardentes', 'Lushe', 126),
    ('les-ardentes', 'Madpace', 127),
    ('les-ardentes', 'Natte Visstick', 128),
    ('les-ardentes', 'Fresh La Douille', 129),
    ('les-ardentes', 'Le Crime', 130),
    ('les-ardentes', 'Camille Yembe', 131),
    ('les-ardentes', 'Asdek x Kaaz', 132),
    ('les-ardentes', 'OG Wizdom', 133),
    ('les-ardentes', 'Bloody$anji', 134),
    ('les-ardentes', 'Matou', 135),
    ('les-ardentes', 'Spectra', 136),
    ('les-ardentes', 'John Gilliot', 137),
    ('les-ardentes', 'Anyme et Ses Potes', 138),
    ('les-vieilles-charrues', 'Katy Perry', 0),
    ('les-vieilles-charrues', 'Gims', 1),
    ('les-vieilles-charrues', 'Josman', 2),
    ('les-vieilles-charrues', 'Biga*Ranx', 3),
    ('les-vieilles-charrues', 'Iliona', 4),
    ('les-vieilles-charrues', 'Piche', 5),
    ('les-vieilles-charrues', 'Upsilone', 6),
    ('les-vieilles-charrues', 'Nick Cave & The Bad Seeds', 7),
    ('les-vieilles-charrues', 'Jean-Louis Aubert', 8),
    ('les-vieilles-charrues', 'Mosimann', 9),
    ('les-vieilles-charrues', 'Vald x Vladimir Cauchemar x Todiefor', 10),
    ('les-vieilles-charrues', 'Disiz', 11),
    ('les-vieilles-charrues', 'Patrick Watson', 12),
    ('les-vieilles-charrues', 'Georgio', 13),
    ('les-vieilles-charrues', 'Joy Crookes', 14),
    ('les-vieilles-charrues', 'Jehnny Beth', 15),
    ('les-vieilles-charrues', 'Luiza', 16),
    ('les-vieilles-charrues', 'Bonne Nuit', 17),
    ('les-vieilles-charrues', 'Jasmine Not Jafar', 18),
    ('les-vieilles-charrues', 'Ne Rangez Pas Les Jardins', 19),
    ('les-vieilles-charrues', 'Jetlag Gang', 20),
    ('les-vieilles-charrues', 'Lalalar', 21),
    ('les-vieilles-charrues', 'Cocanha', 22),
    ('les-vieilles-charrues', 'Super Parquet', 23),
    ('les-vieilles-charrues', 'Cap Kozmik', 24),
    ('les-vieilles-charrues', 'Lovana', 25),
    ('les-vieilles-charrues', 'Aya Nakamura', 26),
    ('les-vieilles-charrues', 'Mika', 27),
    ('les-vieilles-charrues', 'Interpol', 28),
    ('les-vieilles-charrues', 'Nico Moreno', 29),
    ('les-vieilles-charrues', 'Houdi', 30),
    ('les-vieilles-charrues', 'Dub Inc', 31),
    ('les-vieilles-charrues', 'Yelle', 32),
    ('les-vieilles-charrues', 'Cassius', 33),
    ('les-vieilles-charrues', 'Jolagreen23', 34),
    ('les-vieilles-charrues', 'Sprints', 35),
    ('les-vieilles-charrues', 'Asfar Shamsi', 36),
    ('les-vieilles-charrues', 'Folie''s', 37),
    ('les-vieilles-charrues', 'Olli & The London Radio Pop Orchestra', 38),
    ('les-vieilles-charrues', 'No Pain No Pain', 39),
    ('les-vieilles-charrues', 'Djazia Satour', 40),
    ('les-vieilles-charrues', 'Galant Tu Perds Ton Temps', 41),
    ('les-vieilles-charrues', 'Gregailh', 42),
    ('les-vieilles-charrues', 'Enneade', 43),
    ('les-vieilles-charrues', 'Zord', 44),
    ('les-vieilles-charrues', 'Kelt''Duo', 45),
    ('les-vieilles-charrues', 'Maden', 46),
    ('les-vieilles-charrues', 'Orelsan', 47),
    ('les-vieilles-charrues', 'Vanessa Paradis', 48),
    ('les-vieilles-charrues', 'Rilès', 49),
    ('les-vieilles-charrues', 'Feu! Chatterton', 50),
    ('les-vieilles-charrues', 'Suzane', 51),
    ('les-vieilles-charrues', 'Miossec', 52),
    ('les-vieilles-charrues', 'Maureen', 53),
    ('les-vieilles-charrues', 'Tomora', 54),
    ('les-vieilles-charrues', 'Xavier Rudd', 55),
    ('les-vieilles-charrues', '47 Ter', 56),
    ('les-vieilles-charrues', 'Danyl', 57),
    ('les-vieilles-charrues', 'Pact (Joachim Pastor, Joris Delacroix, Teho)', 58),
    ('les-vieilles-charrues', 'Goodbye Karelle', 59),
    ('les-vieilles-charrues', 'Tvod', 60),
    ('les-vieilles-charrues', 'Lindigo', 61),
    ('les-vieilles-charrues', 'Isam Elias', 62),
    ('les-vieilles-charrues', 'Grand Ensemble Filos', 63),
    ('les-vieilles-charrues', 'Plouz & Foen', 64),
    ('thuishaven', 'Luis Ripa', 0),
    ('thuishaven', 'Michel de Hey', 1),
    ('thuishaven', 'Tsepo', 2),
    ('thuishaven', 'Dr Dubplate', 3),
    ('thuishaven', 'Locklead', 4),
    ('thuishaven', 'Nathan Homan', 5),
    ('thuishaven', 'Suze Ijó', 6),
    ('thuishaven', 'M-High', 7),
    ('thuishaven', 'Fafi Abdel Nour', 8),
    ('thuishaven', 'Merel Helderman', 9),
    ('thuishaven', 'Solit', 10),
    ('thuishaven', 'Camille Doe', 11),
    ('thuishaven', 'PHIA', 12),
    ('thuishaven', 'Job de Jong', 13)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;

update public.festival_editions e
set lineup_published = true
from public.festivals f
where e.festival_id = f.id
  and e.year = 2026
  and f.slug in ('francofolies-esch', 'francofolies-la-rochelle', 'dour-festival', 'les-ardentes', 'les-vieilles-charrues', 'thuishaven');
