-- ============================================================
-- Historical lineups (batch 2) for editions users actually
-- attended per user_attendances: Les Plages Electroniques
-- (2017-2025, minus 2008/2020 with no findable/no-event data),
-- World Club Dome (2019, 2022-2025), Luxembourg Open Air
-- (2021-2025), Les Deferlantes (2017, 2021, 2025), Francofolies
-- Esch-sur-Alzette (2022-2025, lineup only for 2022/2024 —
-- 2023/2025 search results were indistinguishable from the
-- already-seeded 2026 lineup so only dates were kept for those
-- two). Sourced from official recaps, Wikipedia, JamBase, RA,
-- Music Festival Wizard, regional press.
-- Idempotent: upserts on (festival_id, year) / guards on artist
-- name / upserts on (edition_id, artist_id) — safe to re-run.
-- ============================================================

insert into public.festival_editions (festival_id, year, start_date, end_date)
select f.id, v.year, v.start_date::date, v.end_date::date
from (values
  ('les-plages-electroniques', 2017, '2017-08-10', '2017-08-12'),
  ('les-plages-electroniques', 2018, '2018-08-10', '2018-08-12'),
  ('les-plages-electroniques', 2021, '2021-08-06', '2021-08-08'),
  ('les-plages-electroniques', 2022, '2022-08-05', '2022-08-07'),
  ('les-plages-electroniques', 2023, '2023-08-04', '2023-08-06'),
  ('les-plages-electroniques', 2024, '2024-08-16', '2024-08-18'),
  ('les-plages-electroniques', 2025, '2025-08-08', '2025-08-10'),
  ('world-club-dome', 2019, '2019-06-07', '2019-06-09'),
  ('world-club-dome', 2022, '2022-06-03', '2022-06-05'),
  ('world-club-dome', 2023, '2023-06-09', '2023-06-11'),
  ('world-club-dome', 2024, '2024-09-06', '2024-09-08'),
  ('world-club-dome', 2025, '2025-06-06', '2025-06-08'),
  ('luxembourg-open-air', 2021, '2021-09-11', '2021-09-12'),
  ('luxembourg-open-air', 2022, '2022-09-09', '2022-09-10'),
  ('luxembourg-open-air', 2023, '2023-05-05', '2023-05-06'),
  ('luxembourg-open-air', 2024, '2024-05-03', '2024-05-04'),
  ('luxembourg-open-air', 2025, '2025-09-12', '2025-09-13'),
  ('les-deferlantes', 2017, '2017-07-08', '2017-07-11'),
  ('les-deferlantes', 2021, '2021-07-07', '2021-07-10'),
  ('les-deferlantes', 2025, '2025-06-26', '2025-06-29'),
  ('francofolies-esch', 2022, '2022-06-08', '2022-06-12'),
  ('francofolies-esch', 2023, '2023-06-08', '2023-06-11'),
  ('francofolies-esch', 2024, '2024-06-06', '2024-06-09'),
  ('francofolies-esch', 2025, '2025-06-06', '2025-06-08')
) as v(slug, year, start_date, end_date)
join public.festivals f on f.slug = v.slug
on conflict (festival_id, year) do update
  set start_date = excluded.start_date, end_date = excluded.end_date;

insert into public.artists (name)
select v.name from (values
  ('Fakear'),
  ('Bon Gamin'),
  ('Tambour Battant'),
  ('Lewis OfMan'),
  ('Flume'),
  ('FEDER'),
  ('Jabberwocky'),
  ('Ofenbach'),
  ('Darius'),
  ('Bondax'),
  ('Kartell'),
  ('Zimmer'),
  ('Cézaire'),
  ('David Guetta'),
  ('Martin Garrix'),
  ('Paul Kalkbrenner'),
  ('Charlotte de Witte'),
  ('Artbat'),
  ('Bon Entendeur'),
  ('Monolink'),
  ('Folamour'),
  ('DJ Lag'),
  ('Header'),
  ('Cut Killer'),
  ('Le Pedre'),
  ('Armin van Buuren'),
  ('Mind Against'),
  ('Gordo'),
  ('Lilly Palmer'),
  ('Stephan Bodzin'),
  ('Bellaire'),
  ('The Blessed Madonna'),
  ('Tale Of Us'),
  ('DJ Snake'),
  ('Boris Brejcha'),
  ('Fisher'),
  ('Gazo'),
  ('Feder'),
  ('Timmy Trumpet'),
  ('Kaytranada'),
  ('Creeds'),
  ('Mosimann'),
  ('Angie & Lazuli'),
  ('SCH'),
  ('Lost Frequencies'),
  ('Apashe'),
  ('Nico Moreno'),
  ('Miel de Montagne'),
  ('Tiësto'),
  ('Booba'),
  ('Eric Prydz'),
  ('Peggy Gou'),
  ('Kungs'),
  ('Purple Disco Machine'),
  ('Mochakk'),
  ('Agoria'),
  ('Trym'),
  ('Marion Di Napoli'),
  ('Vald'),
  ('Laylow'),
  ('Marshmello'),
  ('Nightmre'),
  ('Slander'),
  ('Gestört Aber GeiL'),
  ('W&W'),
  ('Zonderling'),
  ('Talla 2XLC'),
  ('Brennan Heart'),
  ('Deadmau5'),
  ('Steve Aoki'),
  ('Masquerade'),
  ('Headhunterz'),
  ('Paradise'),
  ('Ben Klock'),
  ('Sub Zero Project'),
  ('Claptone'),
  ('Felix Jaehn'),
  ('James Hype'),
  ('KSHMR'),
  ('Black Coffee'),
  ('3 Are Legend'),
  ('Angerfist'),
  ('DJ Rush'),
  ('HUGEL'),
  ('Imanbek'),
  ('Joel Corry'),
  ('Robin Schulz'),
  ('Scooter'),
  ('50 Cent'),
  ('Macklemore'),
  ('Rita Ora'),
  ('Salvatore Ganacci'),
  ('Dimitri Vegas & Like Mike'),
  ('Don Diablo'),
  ('Ben Böhmer'),
  ('FISHER'),
  ('Jamie Jones'),
  ('I Hate Models'),
  ('John Newman'),
  ('Marnik'),
  ('Mike Williams'),
  ('Brooks'),
  ('KREAM'),
  ('Bassjackers'),
  ('Tchami'),
  ('Malaa'),
  ('Will Sparks'),
  ('Blasterjaxx'),
  ('Maddix'),
  ('Joshwa'),
  ('The Rocketman'),
  ('Bennett'),
  ('Avaion'),
  ('Tita Lau'),
  ('DJs From Mars'),
  ('Renaud'),
  ('Petit Biscuit'),
  ('Die Antwoord'),
  ('Last Train'),
  ('Iggy Pop'),
  ('Sting'),
  ('Manu Chao'),
  ('Airbourne'),
  ('Archive'),
  ('Boulevard des Airs'),
  ('Midnight Oil'),
  ('Ibrahim Maalouf'),
  ('Jain'),
  ('Calypso Rose'),
  ('LP'),
  ('Ludwig Von 88'),
  ('Tinariwen'),
  ('Sum 41'),
  ('Ben Harper'),
  ('Jean-Louis Aubert'),
  ('Simple Minds'),
  ('Ninho'),
  ('Angèle'),
  ('Roméo Elvis'),
  ('Soprano'),
  ('Nemir'),
  ('Bob Sinclar'),
  ('Clara Luciani'),
  ('Hoshi'),
  ('Julien Doré'),
  ('Lamomali'),
  ('Philippe Katerine'),
  ('Rivo'),
  ('Leblanc'),
  ('J Balvin'),
  ('Cypress Hill'),
  ('Madness'),
  ('Bresh'),
  ('Kalash'),
  ('Silmarils'),
  ('AMK'),
  ('JRK 19'),
  ('Zamdane'),
  ('Camila Cabello'),
  ('Willsmith'),
  ('Gringe'),
  ('Rimès'),
  ('Rim''k'),
  ('Trinix'),
  ('Bigflo & Oli'),
  ('Werenoi'),
  ('Henri PFR'),
  ('PNL'),
  ('Damso'),
  ('Grand Corps Malade'),
  ('Shaka Ponk'),
  ('Tiakola'),
  ('Luidji'),
  ('La Fève'),
  ('Luther'),
  ('Baby Volcano'),
  ('Meute'),
  ('Zaho de Sagazan'),
  ('Ascendant Vierge'),
  ('KO KO MO'),
  ('Eloi'),
  ('Bagarre'),
  ('Black Lilys'),
  ('Charlotte Cardin'),
  ('Olivia Ruiz'),
  ('Raphaël')
) as v(name)
where not exists (select 1 from public.artists a where lower(a.name) = lower(v.name));

with lineup(slug, year, artist_name, order_index) as (
  values
    ('les-plages-electroniques', 2017, 'Fakear', 0),
    ('les-plages-electroniques', 2017, 'Bon Gamin', 1),
    ('les-plages-electroniques', 2017, 'Tambour Battant', 2),
    ('les-plages-electroniques', 2017, 'Lewis OfMan', 3),
    ('les-plages-electroniques', 2017, 'Flume', 4),
    ('les-plages-electroniques', 2017, 'FEDER', 5),
    ('les-plages-electroniques', 2017, 'Jabberwocky', 6),
    ('les-plages-electroniques', 2017, 'Ofenbach', 7),
    ('les-plages-electroniques', 2017, 'Darius', 8),
    ('les-plages-electroniques', 2017, 'Bondax', 9),
    ('les-plages-electroniques', 2017, 'Kartell', 10),
    ('les-plages-electroniques', 2017, 'Zimmer', 11),
    ('les-plages-electroniques', 2017, 'Cézaire', 12),
    ('les-plages-electroniques', 2022, 'David Guetta', 0),
    ('les-plages-electroniques', 2022, 'Martin Garrix', 1),
    ('les-plages-electroniques', 2022, 'Paul Kalkbrenner', 2),
    ('les-plages-electroniques', 2022, 'Charlotte de Witte', 3),
    ('les-plages-electroniques', 2022, 'Artbat', 4),
    ('les-plages-electroniques', 2022, 'Bon Entendeur', 5),
    ('les-plages-electroniques', 2022, 'Monolink', 6),
    ('les-plages-electroniques', 2022, 'Folamour', 7),
    ('les-plages-electroniques', 2022, 'DJ Lag', 8),
    ('les-plages-electroniques', 2022, 'Header', 9),
    ('les-plages-electroniques', 2022, 'Cut Killer', 10),
    ('les-plages-electroniques', 2022, 'Le Pedre', 11),
    ('les-plages-electroniques', 2023, 'Armin van Buuren', 0),
    ('les-plages-electroniques', 2023, 'Mind Against', 1),
    ('les-plages-electroniques', 2023, 'Gordo', 2),
    ('les-plages-electroniques', 2023, 'Lilly Palmer', 3),
    ('les-plages-electroniques', 2023, 'Stephan Bodzin', 4),
    ('les-plages-electroniques', 2023, 'Bellaire', 5),
    ('les-plages-electroniques', 2023, 'The Blessed Madonna', 6),
    ('les-plages-electroniques', 2023, 'Tale Of Us', 7),
    ('les-plages-electroniques', 2023, 'DJ Snake', 8),
    ('les-plages-electroniques', 2024, 'Boris Brejcha', 0),
    ('les-plages-electroniques', 2024, 'Fisher', 1),
    ('les-plages-electroniques', 2024, 'Gazo', 2),
    ('les-plages-electroniques', 2024, 'Feder', 3),
    ('les-plages-electroniques', 2024, 'Timmy Trumpet', 4),
    ('les-plages-electroniques', 2024, 'Kaytranada', 5),
    ('les-plages-electroniques', 2024, 'Bon Entendeur', 6),
    ('les-plages-electroniques', 2024, 'Creeds', 7),
    ('les-plages-electroniques', 2024, 'Mosimann', 8),
    ('les-plages-electroniques', 2024, 'Angie & Lazuli', 9),
    ('les-plages-electroniques', 2024, 'Paul Kalkbrenner', 10),
    ('les-plages-electroniques', 2024, 'SCH', 11),
    ('les-plages-electroniques', 2024, 'Lost Frequencies', 12),
    ('les-plages-electroniques', 2024, 'Apashe', 13),
    ('les-plages-electroniques', 2024, 'Nico Moreno', 14),
    ('les-plages-electroniques', 2024, 'Miel de Montagne', 15),
    ('les-plages-electroniques', 2025, 'Tiësto', 0),
    ('les-plages-electroniques', 2025, 'Charlotte de Witte', 1),
    ('les-plages-electroniques', 2025, 'Booba', 2),
    ('les-plages-electroniques', 2025, 'Eric Prydz', 3),
    ('les-plages-electroniques', 2025, 'Peggy Gou', 4),
    ('les-plages-electroniques', 2025, 'Kungs', 5),
    ('les-plages-electroniques', 2025, 'Purple Disco Machine', 6),
    ('les-plages-electroniques', 2025, 'Mochakk', 7),
    ('les-plages-electroniques', 2025, 'Agoria', 8),
    ('les-plages-electroniques', 2025, 'Trym', 9),
    ('les-plages-electroniques', 2025, 'Marion Di Napoli', 10),
    ('les-plages-electroniques', 2025, 'Vald', 11),
    ('les-plages-electroniques', 2025, 'Laylow', 12),
    ('world-club-dome', 2019, 'Armin van Buuren', 0),
    ('world-club-dome', 2019, 'David Guetta', 1),
    ('world-club-dome', 2019, 'Marshmello', 2),
    ('world-club-dome', 2019, 'Nightmre', 3),
    ('world-club-dome', 2019, 'Slander', 4),
    ('world-club-dome', 2019, 'Gestört Aber GeiL', 5),
    ('world-club-dome', 2019, 'W&W', 6),
    ('world-club-dome', 2019, 'Zonderling', 7),
    ('world-club-dome', 2019, 'Talla 2XLC', 8),
    ('world-club-dome', 2019, 'Brennan Heart', 9),
    ('world-club-dome', 2022, 'David Guetta', 0),
    ('world-club-dome', 2022, 'Deadmau5', 1),
    ('world-club-dome', 2022, 'Steve Aoki', 2),
    ('world-club-dome', 2022, 'Masquerade', 3),
    ('world-club-dome', 2022, 'Headhunterz', 4),
    ('world-club-dome', 2022, 'Paradise', 5),
    ('world-club-dome', 2022, 'Ben Klock', 6),
    ('world-club-dome', 2022, 'Sub Zero Project', 7),
    ('world-club-dome', 2022, 'Timmy Trumpet', 8),
    ('world-club-dome', 2023, 'Boris Brejcha', 0),
    ('world-club-dome', 2023, 'Claptone', 1),
    ('world-club-dome', 2023, 'David Guetta', 2),
    ('world-club-dome', 2023, 'Felix Jaehn', 3),
    ('world-club-dome', 2023, 'James Hype', 4),
    ('world-club-dome', 2023, 'KSHMR', 5),
    ('world-club-dome', 2023, 'Steve Aoki', 6),
    ('world-club-dome', 2024, 'David Guetta', 0),
    ('world-club-dome', 2024, 'Black Coffee', 1),
    ('world-club-dome', 2024, '3 Are Legend', 2),
    ('world-club-dome', 2024, 'Angerfist', 3),
    ('world-club-dome', 2024, 'Claptone', 4),
    ('world-club-dome', 2024, 'DJ Rush', 5),
    ('world-club-dome', 2024, 'DJ Snake', 6),
    ('world-club-dome', 2024, 'Felix Jaehn', 7),
    ('world-club-dome', 2024, 'HUGEL', 8),
    ('world-club-dome', 2024, 'Imanbek', 9),
    ('world-club-dome', 2024, 'Joel Corry', 10),
    ('world-club-dome', 2024, 'Robin Schulz', 11),
    ('world-club-dome', 2024, 'Scooter', 12),
    ('world-club-dome', 2024, 'Steve Aoki', 13),
    ('world-club-dome', 2025, '50 Cent', 0),
    ('world-club-dome', 2025, 'Macklemore', 1),
    ('world-club-dome', 2025, 'Rita Ora', 2),
    ('world-club-dome', 2025, 'Steve Aoki', 3),
    ('world-club-dome', 2025, 'Salvatore Ganacci', 4),
    ('world-club-dome', 2025, 'Tiësto', 5),
    ('world-club-dome', 2025, 'Dimitri Vegas & Like Mike', 6),
    ('world-club-dome', 2025, 'Don Diablo', 7),
    ('world-club-dome', 2025, 'Angerfist', 8),
    ('world-club-dome', 2025, 'Ben Böhmer', 9),
    ('world-club-dome', 2025, 'Boris Brejcha', 10),
    ('world-club-dome', 2025, 'FISHER', 11),
    ('world-club-dome', 2025, 'Jamie Jones', 12),
    ('world-club-dome', 2025, 'I Hate Models', 13),
    ('world-club-dome', 2025, 'John Newman', 14),
    ('world-club-dome', 2025, 'Brennan Heart', 15),
    ('luxembourg-open-air', 2021, 'Marnik', 0),
    ('luxembourg-open-air', 2021, 'Mike Williams', 1),
    ('luxembourg-open-air', 2021, 'Brooks', 2),
    ('luxembourg-open-air', 2022, 'KREAM', 0),
    ('luxembourg-open-air', 2022, 'HUGEL', 1),
    ('luxembourg-open-air', 2022, 'Felix Jaehn', 2),
    ('luxembourg-open-air', 2023, 'Bassjackers', 0),
    ('luxembourg-open-air', 2023, 'Tchami', 1),
    ('luxembourg-open-air', 2024, 'Malaa', 0),
    ('luxembourg-open-air', 2024, 'Will Sparks', 1),
    ('luxembourg-open-air', 2024, 'Blasterjaxx', 2),
    ('luxembourg-open-air', 2025, 'W&W', 0),
    ('luxembourg-open-air', 2025, 'Maddix', 1),
    ('luxembourg-open-air', 2025, 'Joshwa', 2),
    ('luxembourg-open-air', 2025, 'The Rocketman', 3),
    ('luxembourg-open-air', 2025, 'Bennett', 4),
    ('luxembourg-open-air', 2025, 'Avaion', 5),
    ('luxembourg-open-air', 2025, 'Tita Lau', 6),
    ('luxembourg-open-air', 2025, 'DJs From Mars', 7),
    ('les-deferlantes', 2017, 'Renaud', 0),
    ('les-deferlantes', 2017, 'Petit Biscuit', 1),
    ('les-deferlantes', 2017, 'Die Antwoord', 2),
    ('les-deferlantes', 2017, 'Last Train', 3),
    ('les-deferlantes', 2017, 'Iggy Pop', 4),
    ('les-deferlantes', 2017, 'Sting', 5),
    ('les-deferlantes', 2017, 'Manu Chao', 6),
    ('les-deferlantes', 2017, 'Airbourne', 7),
    ('les-deferlantes', 2017, 'Archive', 8),
    ('les-deferlantes', 2017, 'Boulevard des Airs', 9),
    ('les-deferlantes', 2017, 'Midnight Oil', 10),
    ('les-deferlantes', 2017, 'Ibrahim Maalouf', 11),
    ('les-deferlantes', 2017, 'Jain', 12),
    ('les-deferlantes', 2017, 'Calypso Rose', 13),
    ('les-deferlantes', 2017, 'Kungs', 14),
    ('les-deferlantes', 2017, 'LP', 15),
    ('les-deferlantes', 2017, 'Ludwig Von 88', 16),
    ('les-deferlantes', 2017, 'Tinariwen', 17),
    ('les-deferlantes', 2021, 'Sum 41', 0),
    ('les-deferlantes', 2021, 'Ben Harper', 1),
    ('les-deferlantes', 2021, 'Jean-Louis Aubert', 2),
    ('les-deferlantes', 2021, 'Simple Minds', 3),
    ('les-deferlantes', 2021, 'Ninho', 4),
    ('les-deferlantes', 2021, 'Angèle', 5),
    ('les-deferlantes', 2021, 'Roméo Elvis', 6),
    ('les-deferlantes', 2021, 'Soprano', 7),
    ('les-deferlantes', 2021, 'Nemir', 8),
    ('les-deferlantes', 2025, 'Bob Sinclar', 0),
    ('les-deferlantes', 2025, 'Clara Luciani', 1),
    ('les-deferlantes', 2025, 'Hoshi', 2),
    ('les-deferlantes', 2025, 'Julien Doré', 3),
    ('les-deferlantes', 2025, 'Lamomali', 4),
    ('les-deferlantes', 2025, 'Philippe Katerine', 5),
    ('les-deferlantes', 2025, 'Rivo', 6),
    ('les-deferlantes', 2025, 'Leblanc', 7),
    ('les-deferlantes', 2025, 'J Balvin', 8),
    ('les-deferlantes', 2025, 'Cypress Hill', 9),
    ('les-deferlantes', 2025, 'Madness', 10),
    ('les-deferlantes', 2025, 'Bresh', 11),
    ('les-deferlantes', 2025, 'Jean-Louis Aubert', 12),
    ('les-deferlantes', 2025, 'Kalash', 13),
    ('les-deferlantes', 2025, 'Last Train', 14),
    ('les-deferlantes', 2025, 'Silmarils', 15),
    ('les-deferlantes', 2025, 'AMK', 16),
    ('les-deferlantes', 2025, 'JRK 19', 17),
    ('les-deferlantes', 2025, 'Zamdane', 18),
    ('les-deferlantes', 2025, 'Camila Cabello', 19),
    ('les-deferlantes', 2025, 'Willsmith', 20),
    ('les-deferlantes', 2025, 'Gringe', 21),
    ('les-deferlantes', 2025, 'Rimès', 22),
    ('les-deferlantes', 2025, 'Rim''k', 23),
    ('les-deferlantes', 2025, 'Trinix', 24),
    ('les-deferlantes', 2025, 'DJ Snake', 25),
    ('les-deferlantes', 2025, 'Bigflo & Oli', 26),
    ('les-deferlantes', 2025, 'Boris Brejcha', 27),
    ('les-deferlantes', 2025, 'Gazo', 28),
    ('les-deferlantes', 2025, 'Werenoi', 29),
    ('les-deferlantes', 2025, 'Malaa', 30),
    ('les-deferlantes', 2025, 'Mosimann', 31),
    ('les-deferlantes', 2025, 'Henri PFR', 32),
    ('francofolies-esch', 2022, 'PNL', 0),
    ('francofolies-esch', 2022, 'Damso', 1),
    ('francofolies-esch', 2022, 'Clara Luciani', 2),
    ('francofolies-esch', 2022, 'Grand Corps Malade', 3),
    ('francofolies-esch', 2024, 'David Guetta', 0),
    ('francofolies-esch', 2024, 'Ninho', 1),
    ('francofolies-esch', 2024, 'Shaka Ponk', 2),
    ('francofolies-esch', 2024, 'Tiakola', 3),
    ('francofolies-esch', 2024, 'Luidji', 4),
    ('francofolies-esch', 2024, 'La Fève', 5),
    ('francofolies-esch', 2024, 'Luther', 6),
    ('francofolies-esch', 2024, 'Baby Volcano', 7),
    ('francofolies-esch', 2024, 'Lost Frequencies', 8),
    ('francofolies-esch', 2024, 'Meute', 9),
    ('francofolies-esch', 2024, 'Zaho de Sagazan', 10),
    ('francofolies-esch', 2024, 'Ascendant Vierge', 11),
    ('francofolies-esch', 2024, 'Apashe', 12),
    ('francofolies-esch', 2024, 'KO KO MO', 13),
    ('francofolies-esch', 2024, 'Eloi', 14),
    ('francofolies-esch', 2024, 'Bagarre', 15),
    ('francofolies-esch', 2024, 'Black Lilys', 16),
    ('francofolies-esch', 2024, 'Charlotte Cardin', 17),
    ('francofolies-esch', 2024, 'Olivia Ruiz', 18),
    ('francofolies-esch', 2024, 'Raphaël', 19)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = l.year
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;

update public.festival_editions e
set lineup_published = true
from public.festivals f
where e.festival_id = f.id and (
  (f.slug = 'les-plages-electroniques' and e.year = 2017) or
  (f.slug = 'les-plages-electroniques' and e.year = 2022) or
  (f.slug = 'les-plages-electroniques' and e.year = 2023) or
  (f.slug = 'les-plages-electroniques' and e.year = 2024) or
  (f.slug = 'les-plages-electroniques' and e.year = 2025) or
  (f.slug = 'world-club-dome' and e.year = 2019) or
  (f.slug = 'world-club-dome' and e.year = 2022) or
  (f.slug = 'world-club-dome' and e.year = 2023) or
  (f.slug = 'world-club-dome' and e.year = 2024) or
  (f.slug = 'world-club-dome' and e.year = 2025) or
  (f.slug = 'luxembourg-open-air' and e.year = 2021) or
  (f.slug = 'luxembourg-open-air' and e.year = 2022) or
  (f.slug = 'luxembourg-open-air' and e.year = 2023) or
  (f.slug = 'luxembourg-open-air' and e.year = 2024) or
  (f.slug = 'luxembourg-open-air' and e.year = 2025) or
  (f.slug = 'les-deferlantes' and e.year = 2017) or
  (f.slug = 'les-deferlantes' and e.year = 2021) or
  (f.slug = 'les-deferlantes' and e.year = 2025) or
  (f.slug = 'francofolies-esch' and e.year = 2022) or
  (f.slug = 'francofolies-esch' and e.year = 2024)
);
