-- ============================================================
-- Lineup expansion pass 3 for thin 2026 editions: SUNSET By
-- NEON, BAUM, FLY Open Air, Sea Star, Balaton Sound, Primer,
-- Beats For Love, Groove Cruise, Pitch Music & Arts, Love
-- International, Nibirii, EDC Thailand, Vision & Colour,
-- BEONIX, S2O Bangkok. Sourced from official sites/DJ Mag/RA/
-- EDM press.
--
-- Skipped: S2O Taiwan (no artist names surfaced, only a day-count),
-- SAGA Festival (already covered in an earlier pass, still no
-- further names announced), The Magic Of Tomorrowland (no 2026
-- lineup announced yet — also worth a follow-up check: research
-- suggests this edition is in Shanghai, China, not Boom, Belgium
-- as currently stored, which needs verifying before touching it).
--
-- Idempotent: guards on artist name / upserts on
-- (edition_id, artist_id) — safe to re-run.
-- ============================================================

insert into public.artists (name)
select v.name from (values
  ('ARTBAT'),
  ('R3HAB'),
  ('Chris Avantgarde'),
  ('PlastiK Funk'),
  ('7SKIES'),
  ('ANNA'),
  ('Chris Liebing'),
  ('Dixon'),
  ('Honey Dijon'),
  ('Indira Paganotto'),
  ('I Hate Models'),
  ('Joseph Capriati'),
  ('Len Faki'),
  ('Mall Grab'),
  ('Marcel Dettmann'),
  ('Nina Kraviz'),
  ('Richie Hawtin'),
  ('Sama'' Abdulhadi'),
  ('SNTS'),
  ('999999999'),
  ('Helena Hauff'),
  ('Boys Noize'),
  ('Planetary Assault Systems'),
  ('DJ Rush'),
  ('Kerri Chandler'),
  ('Sammy Virji'),
  ('Interplanetary Criminal'),
  ('Alisha'),
  ('Olive F'),
  ('Loreen'),
  ('Boris Brejcha'),
  ('Xzibit'),
  ('Layla Benitez'),
  ('Lottie'),
  ('Martin Garrix'),
  ('Afrojack'),
  ('Armin van Buuren'),
  ('Knife Party'),
  ('Yellow Claw'),
  ('Axwell'),
  ('Adam Ten'),
  ('Armand Van Helden'),
  ('Bedouin'),
  ('Stephan Bodzin'),
  ('Miss Monique'),
  ('Calvin Harris'),
  ('Charlotte de Witte'),
  ('Alesso'),
  ('Marshmello'),
  ('Dimension'),
  ('Dimitri Vegas & Like Mike'),
  ('Pendulum'),
  ('Paul van Dyk'),
  ('Aly & Fila'),
  ('Aphrodite'),
  ('Da Tweekaz'),
  ('Gene Farris'),
  ('Marco Bailey'),
  ('MORTEN'),
  ('ReOrder'),
  ('John Summit'),
  ('Cloonee'),
  ('Green Velvet'),
  ('Vini Vici'),
  ('Cassian'),
  ('Jason Ross'),
  ('Markus Schulz'),
  ('Chris Lorenzo'),
  ('Cristoph'),
  ('Eris Drew'),
  ('Octo Octa'),
  ('MARRØN'),
  ('Job Jobse'),
  ('Palms Trax'),
  ('Âme'),
  ('Pangaea'),
  ('OK Williams'),
  ('Special Request'),
  ('DJ Nobu'),
  ('Yung Singh'),
  ('Jyoty'),
  ('Yu Su'),
  ('Crazy P'),
  ('Horse Meat Disco'),
  ('Roman Flugel'),
  ('Midland'),
  ('Daniel Avery'),
  ('Enzo Siragusa'),
  ('Craig Richards'),
  ('Hodge'),
  ('Klangkuenstler'),
  ('Dax J'),
  ('Wilkinson'),
  ('Marlon Hoffstadt'),
  ('Hannah Laing'),
  ('Netsky'),
  ('Fox Stevenson'),
  ('Felix Kröcher'),
  ('Tiësto'),
  ('Zedd'),
  ('deadmau5'),
  ('Alok'),
  ('Sebastian Ingrosso'),
  ('Seven Lions'),
  ('Loud Luxury'),
  ('Fisher'),
  ('Gareth Emery'),
  ('Chase & Status'),
  ('Angerfist'),
  ('Brennan Heart'),
  ('Sub Zero Project'),
  ('Sound Rush'),
  ('Svdden Death'),
  ('Sub Focus'),
  ('Knock2'),
  ('Lilly Palmer'),
  ('DJ Tennis'),
  ('Dombresky'),
  ('Loco Dice'),
  ('Kygo'),
  ('Porter Robinson'),
  ('Gryffin'),
  ('Slander'),
  ('Gorgon City'),
  ('Ray Volpe'),
  ('ISOxo'),
  ('AC Slater'),
  ('ARMNHMR'),
  ('SIDEPIECE'),
  ('Sultan + Shepard'),
  ('Adam Beyer'),
  ('CamelPhat'),
  ('Röyksopp'),
  ('Argy'),
  ('Monolink'),
  ('Jan Blomqvist'),
  ('Patrick Mason'),
  ('Benny Benassi'),
  ('Pan-Pot'),
  ('Franky Wah'),
  ('Raxon'),
  ('Spartaque'),
  ('OXIA'),
  ('Alan Walker'),
  ('Steve Aoki'),
  ('Lost Frequencies'),
  ('Don Diablo'),
  ('Dabin'),
  ('GRYFFIN'),
  ('William Black')
) as v(name)
where not exists (select 1 from public.artists a where lower(a.name) = lower(v.name));

with lineup(slug, artist_name, order_index) as (
  values
    ('sunset-by-neon', 'ARTBAT', 100),
    ('sunset-by-neon', 'R3HAB', 101),
    ('sunset-by-neon', 'Chris Avantgarde', 102),
    ('sunset-by-neon', 'PlastiK Funk', 103),
    ('sunset-by-neon', '7SKIES', 104),
    ('baum', 'ANNA', 100),
    ('baum', 'Chris Liebing', 101),
    ('baum', 'Dixon', 102),
    ('baum', 'Honey Dijon', 103),
    ('baum', 'Indira Paganotto', 104),
    ('baum', 'I Hate Models', 105),
    ('baum', 'Joseph Capriati', 106),
    ('baum', 'Len Faki', 107),
    ('baum', 'Mall Grab', 108),
    ('baum', 'Marcel Dettmann', 109),
    ('baum', 'Nina Kraviz', 110),
    ('baum', 'Richie Hawtin', 111),
    ('baum', 'Sama'' Abdulhadi', 112),
    ('baum', 'SNTS', 113),
    ('baum', '999999999', 114),
    ('baum', 'Helena Hauff', 115),
    ('baum', 'Boys Noize', 116),
    ('baum', 'Planetary Assault Systems', 117),
    ('baum', 'DJ Rush', 118),
    ('fly-open-air', 'Kerri Chandler', 100),
    ('fly-open-air', 'Sammy Virji', 101),
    ('fly-open-air', 'Interplanetary Criminal', 102),
    ('fly-open-air', 'Alisha', 103),
    ('fly-open-air', 'Olive F', 104),
    ('sea-star', 'Loreen', 100),
    ('sea-star', 'I Hate Models', 101),
    ('sea-star', 'Indira Paganotto', 102),
    ('sea-star', 'Boris Brejcha', 103),
    ('sea-star', 'Xzibit', 104),
    ('sea-star', 'Layla Benitez', 105),
    ('sea-star', 'Lottie', 106),
    ('balaton-sound', 'Martin Garrix', 100),
    ('balaton-sound', 'Afrojack', 101),
    ('balaton-sound', 'Armin van Buuren', 102),
    ('balaton-sound', 'Knife Party', 103),
    ('balaton-sound', 'Yellow Claw', 104),
    ('primer', 'Axwell', 100),
    ('primer', 'Adam Ten', 101),
    ('primer', 'Armand Van Helden', 102),
    ('primer', 'Bedouin', 103),
    ('primer', 'Stephan Bodzin', 104),
    ('primer', 'Miss Monique', 105),
    ('beats-for-love', 'Calvin Harris', 100),
    ('beats-for-love', 'Charlotte de Witte', 101),
    ('beats-for-love', 'Alesso', 102),
    ('beats-for-love', 'Marshmello', 103),
    ('beats-for-love', 'Dimension', 104),
    ('beats-for-love', 'Dimitri Vegas & Like Mike', 105),
    ('beats-for-love', 'Pendulum', 106),
    ('beats-for-love', 'Paul van Dyk', 107),
    ('beats-for-love', 'Aly & Fila', 108),
    ('beats-for-love', 'Aphrodite', 109),
    ('beats-for-love', 'Da Tweekaz', 110),
    ('beats-for-love', 'Gene Farris', 111),
    ('beats-for-love', 'Marco Bailey', 112),
    ('beats-for-love', 'MORTEN', 113),
    ('beats-for-love', 'ReOrder', 114),
    ('groove-cruise', 'John Summit', 100),
    ('groove-cruise', 'Cloonee', 101),
    ('groove-cruise', 'Green Velvet', 102),
    ('groove-cruise', 'Vini Vici', 103),
    ('groove-cruise', 'Cassian', 104),
    ('groove-cruise', 'Jason Ross', 105),
    ('groove-cruise', 'Markus Schulz', 106),
    ('groove-cruise', 'Chris Lorenzo', 107),
    ('groove-cruise', 'Cristoph', 108),
    ('pitch-music-arts', 'Charlotte de Witte', 100),
    ('pitch-music-arts', 'Eris Drew', 101),
    ('pitch-music-arts', 'Octo Octa', 102),
    ('pitch-music-arts', 'MARRØN', 103),
    ('pitch-music-arts', 'Job Jobse', 104),
    ('pitch-music-arts', 'Palms Trax', 105),
    ('pitch-music-arts', 'Âme', 106),
    ('pitch-music-arts', 'Pangaea', 107),
    ('pitch-music-arts', 'OK Williams', 108),
    ('pitch-music-arts', 'Special Request', 109),
    ('pitch-music-arts', 'DJ Nobu', 110),
    ('pitch-music-arts', 'Sama'' Abdulhadi', 111),
    ('pitch-music-arts', 'Yung Singh', 112),
    ('pitch-music-arts', 'Jyoty', 113),
    ('pitch-music-arts', 'Yu Su', 114),
    ('love-international', 'Crazy P', 100),
    ('love-international', 'Horse Meat Disco', 101),
    ('love-international', 'Roman Flugel', 102),
    ('love-international', 'Palms Trax', 103),
    ('love-international', 'Midland', 104),
    ('love-international', 'Daniel Avery', 105),
    ('love-international', 'Enzo Siragusa', 106),
    ('love-international', 'Craig Richards', 107),
    ('love-international', 'Hodge', 108),
    ('nibirii', 'Klangkuenstler', 100),
    ('nibirii', 'Vini Vici', 101),
    ('nibirii', 'I Hate Models', 102),
    ('nibirii', 'Dax J', 103),
    ('nibirii', 'Dimension', 104),
    ('nibirii', 'Wilkinson', 105),
    ('nibirii', 'Marlon Hoffstadt', 106),
    ('nibirii', 'Hannah Laing', 107),
    ('nibirii', 'Netsky', 108),
    ('nibirii', 'Fox Stevenson', 109),
    ('nibirii', 'Felix Kröcher', 110),
    ('edc-thailand', 'Tiësto', 100),
    ('edc-thailand', 'Zedd', 101),
    ('edc-thailand', 'Afrojack', 102),
    ('edc-thailand', 'Armin van Buuren', 103),
    ('edc-thailand', 'deadmau5', 104),
    ('edc-thailand', 'Alok', 105),
    ('edc-thailand', 'Axwell', 106),
    ('edc-thailand', 'Sebastian Ingrosso', 107),
    ('edc-thailand', 'Seven Lions', 108),
    ('edc-thailand', 'Loud Luxury', 109),
    ('edc-thailand', 'Fisher', 110),
    ('edc-thailand', 'Gareth Emery', 111),
    ('edc-thailand', 'Chase & Status', 112),
    ('edc-thailand', 'Wilkinson', 113),
    ('edc-thailand', 'Angerfist', 114),
    ('edc-thailand', 'Brennan Heart', 115),
    ('edc-thailand', 'Sub Zero Project', 116),
    ('edc-thailand', 'Sound Rush', 117),
    ('edc-thailand', 'Svdden Death', 118),
    ('edc-thailand', 'Sub Focus', 119),
    ('edc-thailand', 'Knock2', 120),
    ('edc-thailand', 'Nina Kraviz', 121),
    ('edc-thailand', 'Lilly Palmer', 122),
    ('edc-thailand', 'DJ Tennis', 123),
    ('edc-thailand', 'Dombresky', 124),
    ('edc-thailand', 'Loco Dice', 125),
    ('vision-colour', 'Kygo', 100),
    ('vision-colour', 'John Summit', 101),
    ('vision-colour', 'Charlotte de Witte', 102),
    ('vision-colour', 'Porter Robinson', 103),
    ('vision-colour', 'Gryffin', 104),
    ('vision-colour', 'Slander', 105),
    ('vision-colour', 'Gorgon City', 106),
    ('vision-colour', 'Netsky', 107),
    ('vision-colour', 'Markus Schulz', 108),
    ('vision-colour', 'Ray Volpe', 109),
    ('vision-colour', 'Knock2', 110),
    ('vision-colour', 'ISOxo', 111),
    ('vision-colour', 'AC Slater', 112),
    ('vision-colour', 'ARMNHMR', 113),
    ('vision-colour', 'SIDEPIECE', 114),
    ('vision-colour', 'Sultan + Shepard', 115),
    ('beonix', 'Adam Beyer', 100),
    ('beonix', 'CamelPhat', 101),
    ('beonix', 'Röyksopp', 102),
    ('beonix', 'Argy', 103),
    ('beonix', 'Monolink', 104),
    ('beonix', 'Jan Blomqvist', 105),
    ('beonix', 'Patrick Mason', 106),
    ('beonix', 'Bedouin', 107),
    ('beonix', 'Benny Benassi', 108),
    ('beonix', 'Pan-Pot', 109),
    ('beonix', 'Franky Wah', 110),
    ('beonix', 'Raxon', 111),
    ('beonix', 'Spartaque', 112),
    ('beonix', 'OXIA', 113),
    ('s2o-bangkok', 'Alan Walker', 100),
    ('s2o-bangkok', 'Steve Aoki', 101),
    ('s2o-bangkok', 'Lost Frequencies', 102),
    ('s2o-bangkok', 'I Hate Models', 103),
    ('s2o-bangkok', 'AC Slater', 104),
    ('s2o-bangkok', 'Zedd', 105),
    ('s2o-bangkok', 'Don Diablo', 106),
    ('s2o-bangkok', 'Dabin', 107),
    ('s2o-bangkok', 'SIDEPIECE', 108),
    ('s2o-bangkok', 'Kygo', 109),
    ('s2o-bangkok', 'GRYFFIN', 110),
    ('s2o-bangkok', 'Ray Volpe', 111),
    ('s2o-bangkok', 'Da Tweekaz', 112),
    ('s2o-bangkok', 'William Black', 113)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;
