-- ============================================================
-- Lineup expansion pass for thin 2026 editions (Movement,
-- Dekmantel, AMF, A State Of Trance, Ultra Korea/Japan,
-- Solidays, Delta Festival, POSITIV, Lovefest, Verknipt).
-- Sourced from official sites/DJ Mag/RA/Billboard/press.
--
-- Deliberately NOT touched:
-- - MELT Festival: conflicting reports on whether a 2026 edition
--   is even happening (one source says the festival ended after
--   2024) — the existing thin lineup is left as-is pending a
--   clearer signal, rather than risk fabricating a lineup for an
--   event that might not occur.
-- - EXIT Festival: already flagged in an earlier seed pass as
--   not happening in Novi Sad in 2026 (multi-city global tour
--   instead) — same reasoning as before, needs a product
--   decision, not a data fix.
-- - Ultra Korea/Japan, SAGA, DWP: only Phase 1 lineups exist as
--   of this research; added what is confirmed, not guessed.
--
-- Idempotent: guards on artist name / upserts on
-- (edition_id, artist_id) — safe to re-run.
-- ============================================================

insert into public.artists (name)
select v.name from (values
  ('Sara Landry'),
  ('Carl Cox'),
  ('Dom Dolla'),
  ('Richie Hawtin'),
  ('Danny Brown'),
  ('Barry Can''t Swim'),
  ('The Dare'),
  ('999999999'),
  ('Carl Craig'),
  ('Cajmere'),
  ('Mochakk'),
  ('Boys Noize'),
  ('Mcr-T'),
  ('Nia Archives'),
  ('TEED'),
  ('Claude VonStroke'),
  ('Octo Octa'),
  ('Kevin Saunderson'),
  ('Dantiez'),
  ('Juan Atkins'),
  ('Moritz von Oswald'),
  ('Donato Dozzy'),
  ('Neel'),
  ('Green Velvet'),
  ('Ellen Allien'),
  ('DJ Stingray 313'),
  ('Kyle Hall'),
  ('Byron The Aquarius'),
  ('Colette'),
  ('DJ Heather'),
  ('Audion'),
  ('Blawan'),
  ('Dax J'),
  ('Terrence Dixon'),
  ('Skrillex'),
  ('Eris Drew'),
  ('A Guy Called Gerald'),
  ('Jyoty'),
  ('Sampha'),
  ('Mala'),
  ('Sir Spyro'),
  ('Helena Hauff'),
  ('SHERELLE'),
  ('Kode9'),
  ('James Holden'),
  ('Surgeon'),
  ('Marcel Dettmann'),
  ('Actress'),
  ('Underground Resistance'),
  ('Saul Williams'),
  ('Ricardo Villalobos'),
  ('CCL'),
  ('trickpony'),
  ('Blasha'),
  ('Allatt'),
  ('DVS1'),
  ('Nicolas Lutz'),
  ('Mia Koden'),
  ('Konduku'),
  ('gyrofield'),
  ('DARKSIDE'),
  ('Bitter Babe'),
  ('Channel One'),
  ('Fumiya Tanaka'),
  ('Brodinski'),
  ('Slikback'),
  ('Dr. Rubinstein'),
  ('Ben UFO'),
  ('Call Super'),
  ('Objekt'),
  ('Pariah'),
  ('PLO Man'),
  ('Skee Mask'),
  ('Afrojack'),
  ('Amelie Lens'),
  ('Armin van Buuren'),
  ('ARTBAT'),
  ('D-Block & S-te-Fan'),
  ('David Guetta'),
  ('Korolova'),
  ('Marlon Hoffstadt'),
  ('Oliver Heldens'),
  ('Maddix'),
  ('Cosmic Gate'),
  ('Rank 1'),
  ('Hannah Laing'),
  ('Aly & Fila'),
  ('John O''Callaghan'),
  ('Mauro Picotto'),
  ('Laura van Dam'),
  ('Ferry Corsten'),
  ('Olivia Lensen'),
  ('Giuseppe Ottaviani'),
  ('Deep Dish'),
  ('Amber Revival'),
  ('Ammara'),
  ('Andrew Rayel'),
  ('Ben Gold'),
  ('Billy Gillies'),
  ('David Forbes'),
  ('Ebenezer'),
  ('Estiva'),
  ('Jorn van Deynhoven'),
  ('Kyau & Albert'),
  ('Marlo'),
  ('Matt Fax'),
  ('Ørjan Nilsen'),
  ('Push'),
  ('Richard Durand'),
  ('Ruben de Ronde'),
  ('Sean Tyas'),
  ('Signum'),
  ('Super8 & Tab'),
  ('Martin Garrix'),
  ('Axwell'),
  ('Ingrosso'),
  ('Adam Beyer'),
  ('Sasha'),
  ('Nicole Moudaber'),
  ('Alesso'),
  ('The Martinez Brothers'),
  ('Peggy Gou'),
  ('Zedd'),
  ('Knock2'),
  ('Orelsan'),
  ('Gims'),
  ('Bigflo & Oli'),
  ('Major Lazer'),
  ('Zara Larsson'),
  ('Zaho'),
  ('Suzane'),
  ('Skip The Use'),
  ('Yael Naim'),
  ('Nina Kraviz'),
  ('I Hate Models'),
  ('Vladimir Cauchemar'),
  ('Todiefor'),
  ('Nico Moreno'),
  ('L2B'),
  ('Mosimann'),
  ('Vald'),
  ('Josman'),
  ('Guy2Bezbar'),
  ('Helena'),
  ('Meryl'),
  ('Ino Casablanca'),
  ('La Mano 1.9'),
  ('Kungs'),
  ('Benny Benassi'),
  ('Adèle Castillon'),
  ('Mandragora'),
  ('Bennett'),
  ('Acid Arab'),
  ('Cassimm'),
  ('Frederic.'),
  ('Nure'),
  ('Daniella Da Silva'),
  ('Omaks'),
  ('Paga'),
  ('Sköne'),
  ('Kevin De Vries'),
  ('Miki'),
  ('Thylacine'),
  ('TK'),
  ('Trinix'),
  ('Lilly Palmer'),
  ('Bellini'),
  ('Notmytype'),
  ('Boris Brejcha'),
  ('Carla Schmitt'),
  ('Nicolas Cuer'),
  ('Charlotte de Witte'),
  ('Novah'),
  ('Biianco'),
  ('Fisher'),
  ('Venga'),
  ('Marco Carola'),
  ('Enrico Sangiuliano'),
  ('APRD'),
  ('Zuke'),
  ('AREA ØNE'),
  ('Ben Techy'),
  ('Blurred Movement'),
  ('Ramøn'),
  ('BYØRN'),
  ('DROS'),
  ('Juul Exler'),
  ('Entasia'),
  ('Freddi'),
  ('Fantasm'),
  ('Føss'),
  ('FUMI'),
  ('Jånks'),
  ('Hurts'),
  ('NYCO'),
  ('Inafekt'),
  ('NewTone'),
  ('Iosio'),
  ('JALO'),
  ('Vino'),
  ('Jazzy'),
  ('Jowi'),
  ('JO3Y3T'),
  ('Karah'),
  ('KLOFAMA'),
  ('LS41'),
  ('Nzgûl'),
  ('SANTØS'),
  ('SuP'),
  ('TASSERY'),
  ('WILDERÍCH'),
  ('zwilling'),
  ('Winson'),
  ('LØREN'),
  ('Nikolina'),
  ('Rebekah'),
  ('6EJOU'),
  ('APHØTIC'),
  ('BLNK'),
  ('Lieks'),
  ('BØĘRY'),
  ('Cloudy'),
  ('KUKO'),
  ('Cortes'),
  ('NØRAJ'),
  ('Davyboi'),
  ('Franck'),
  ('Divasi'),
  ('DJ IP'),
  ('Dr G'),
  ('Serafina'),
  ('hardsok'),
  ('Jayron'),
  ('Johannes Schuster'),
  ('Justin Jay'),
  ('Rozie'),
  ('Katy Rough'),
  ('Kruelty'),
  ('Neek'),
  ('Nicolas Julian'),
  ('Pawlowski'),
  ('PETERBLUE'),
  ('Raxeller'),
  ('Restricted'),
  ('Rowin'),
  ('SLVL'),
  ('USH'),
  ('TITI'),
  ('Toxic Machinery'),
  ('Vieze Asbak'),
  ('Xamuel')
) as v(name)
where not exists (select 1 from public.artists a where lower(a.name) = lower(v.name));

with lineup(slug, artist_name, order_index) as (
  values
    ('movement', 'Sara Landry', 100),
    ('movement', 'Carl Cox', 101),
    ('movement', 'Dom Dolla', 102),
    ('movement', 'Richie Hawtin', 103),
    ('movement', 'Danny Brown', 104),
    ('movement', 'Barry Can''t Swim', 105),
    ('movement', 'The Dare', 106),
    ('movement', '999999999', 107),
    ('movement', 'Carl Craig', 108),
    ('movement', 'Cajmere', 109),
    ('movement', 'Mochakk', 110),
    ('movement', 'Boys Noize', 111),
    ('movement', 'Mcr-T', 112),
    ('movement', 'Nia Archives', 113),
    ('movement', 'TEED', 114),
    ('movement', 'Claude VonStroke', 115),
    ('movement', 'Octo Octa', 116),
    ('movement', 'Kevin Saunderson', 117),
    ('movement', 'Dantiez', 118),
    ('movement', 'Juan Atkins', 119),
    ('movement', 'Moritz von Oswald', 120),
    ('movement', 'Donato Dozzy', 121),
    ('movement', 'Neel', 122),
    ('movement', 'Green Velvet', 123),
    ('movement', 'Ellen Allien', 124),
    ('movement', 'DJ Stingray 313', 125),
    ('movement', 'Kyle Hall', 126),
    ('movement', 'Byron The Aquarius', 127),
    ('movement', 'Colette', 128),
    ('movement', 'DJ Heather', 129),
    ('movement', 'Audion', 130),
    ('movement', 'Blawan', 131),
    ('movement', 'Dax J', 132),
    ('movement', 'Terrence Dixon', 133),
    ('dekmantel', 'Skrillex', 100),
    ('dekmantel', 'Eris Drew', 101),
    ('dekmantel', 'A Guy Called Gerald', 102),
    ('dekmantel', 'Jyoty', 103),
    ('dekmantel', 'Sampha', 104),
    ('dekmantel', 'Mala', 105),
    ('dekmantel', 'Sir Spyro', 106),
    ('dekmantel', 'Helena Hauff', 107),
    ('dekmantel', 'SHERELLE', 108),
    ('dekmantel', 'Kode9', 109),
    ('dekmantel', 'James Holden', 110),
    ('dekmantel', 'Surgeon', 111),
    ('dekmantel', 'Marcel Dettmann', 112),
    ('dekmantel', 'Actress', 113),
    ('dekmantel', 'Carl Craig', 114),
    ('dekmantel', 'Underground Resistance', 115),
    ('dekmantel', 'Saul Williams', 116),
    ('dekmantel', 'Ricardo Villalobos', 117),
    ('dekmantel', 'CCL', 118),
    ('dekmantel', 'trickpony', 119),
    ('dekmantel', 'Blasha', 120),
    ('dekmantel', 'Allatt', 121),
    ('dekmantel', 'DVS1', 122),
    ('dekmantel', 'Nicolas Lutz', 123),
    ('dekmantel', 'Mia Koden', 124),
    ('dekmantel', 'Konduku', 125),
    ('dekmantel', 'gyrofield', 126),
    ('dekmantel', 'DARKSIDE', 127),
    ('dekmantel', 'Bitter Babe', 128),
    ('dekmantel', 'Channel One', 129),
    ('dekmantel', 'Fumiya Tanaka', 130),
    ('dekmantel', 'Brodinski', 131),
    ('dekmantel', 'Slikback', 132),
    ('dekmantel', 'Dr. Rubinstein', 133),
    ('dekmantel', 'Ben UFO', 134),
    ('dekmantel', 'Call Super', 135),
    ('dekmantel', 'Objekt', 136),
    ('dekmantel', 'Pariah', 137),
    ('dekmantel', 'PLO Man', 138),
    ('dekmantel', 'Skee Mask', 139),
    ('amf', 'Afrojack', 100),
    ('amf', 'Amelie Lens', 101),
    ('amf', 'Armin van Buuren', 102),
    ('amf', 'ARTBAT', 103),
    ('amf', 'D-Block & S-te-Fan', 104),
    ('amf', 'David Guetta', 105),
    ('amf', 'Korolova', 106),
    ('amf', 'Marlon Hoffstadt', 107),
    ('a-state-of-trance', 'Oliver Heldens', 100),
    ('a-state-of-trance', 'Maddix', 101),
    ('a-state-of-trance', 'Cosmic Gate', 102),
    ('a-state-of-trance', 'Rank 1', 103),
    ('a-state-of-trance', 'Hannah Laing', 104),
    ('a-state-of-trance', 'Aly & Fila', 105),
    ('a-state-of-trance', 'John O''Callaghan', 106),
    ('a-state-of-trance', 'Mauro Picotto', 107),
    ('a-state-of-trance', 'Laura van Dam', 108),
    ('a-state-of-trance', 'Ferry Corsten', 109),
    ('a-state-of-trance', 'Olivia Lensen', 110),
    ('a-state-of-trance', 'Giuseppe Ottaviani', 111),
    ('a-state-of-trance', 'Armin van Buuren', 112),
    ('a-state-of-trance', 'Deep Dish', 113),
    ('a-state-of-trance', 'Amber Revival', 114),
    ('a-state-of-trance', 'Ammara', 115),
    ('a-state-of-trance', 'Andrew Rayel', 116),
    ('a-state-of-trance', 'Ben Gold', 117),
    ('a-state-of-trance', 'Billy Gillies', 118),
    ('a-state-of-trance', 'David Forbes', 119),
    ('a-state-of-trance', 'Ebenezer', 120),
    ('a-state-of-trance', 'Estiva', 121),
    ('a-state-of-trance', 'Jorn van Deynhoven', 122),
    ('a-state-of-trance', 'Korolova', 123),
    ('a-state-of-trance', 'Kyau & Albert', 124),
    ('a-state-of-trance', 'Marlo', 125),
    ('a-state-of-trance', 'Matt Fax', 126),
    ('a-state-of-trance', 'Ørjan Nilsen', 127),
    ('a-state-of-trance', 'Push', 128),
    ('a-state-of-trance', 'Richard Durand', 129),
    ('a-state-of-trance', 'Ruben de Ronde', 130),
    ('a-state-of-trance', 'Sean Tyas', 131),
    ('a-state-of-trance', 'Signum', 132),
    ('a-state-of-trance', 'Super8 & Tab', 133),
    ('ultra-korea', 'Afrojack', 100),
    ('ultra-korea', 'Martin Garrix', 101),
    ('ultra-korea', 'Axwell', 102),
    ('ultra-korea', 'Ingrosso', 103),
    ('ultra-korea', 'Adam Beyer', 104),
    ('ultra-korea', 'Sasha', 105),
    ('ultra-korea', 'Nicole Moudaber', 106),
    ('ultra-japan', 'Alesso', 100),
    ('ultra-japan', 'The Martinez Brothers', 101),
    ('ultra-japan', 'Peggy Gou', 102),
    ('ultra-japan', 'Sara Landry', 103),
    ('ultra-japan', 'Zedd', 104),
    ('ultra-japan', 'Knock2', 105),
    ('solidays', 'Orelsan', 100),
    ('solidays', 'Gims', 101),
    ('solidays', 'Bigflo & Oli', 102),
    ('solidays', 'Major Lazer', 103),
    ('solidays', 'Zara Larsson', 104),
    ('solidays', 'Zaho', 105),
    ('solidays', 'Suzane', 106),
    ('solidays', 'Skip The Use', 107),
    ('solidays', 'Yael Naim', 108),
    ('solidays', 'Amelie Lens', 109),
    ('solidays', 'Nina Kraviz', 110),
    ('solidays', 'I Hate Models', 111),
    ('solidays', 'Vladimir Cauchemar', 112),
    ('solidays', 'Todiefor', 113),
    ('solidays', 'Nico Moreno', 114),
    ('solidays', 'L2B', 115),
    ('solidays', 'Mosimann', 116),
    ('solidays', 'Vald', 117),
    ('solidays', 'Josman', 118),
    ('solidays', 'Guy2Bezbar', 119),
    ('solidays', 'Helena', 120),
    ('solidays', 'Meryl', 121),
    ('solidays', 'Ino Casablanca', 122),
    ('solidays', 'La Mano 1.9', 123),
    ('delta-festival', 'Kungs', 100),
    ('delta-festival', 'Adam Beyer', 101),
    ('delta-festival', 'Benny Benassi', 102),
    ('delta-festival', 'Adèle Castillon', 103),
    ('delta-festival', 'L2B', 104),
    ('delta-festival', 'Mandragora', 105),
    ('delta-festival', 'Mosimann', 106),
    ('delta-festival', 'Bennett', 107),
    ('delta-festival', 'Acid Arab', 108),
    ('delta-festival', 'Cassimm', 109),
    ('delta-festival', 'Frederic.', 110),
    ('delta-festival', 'Nure', 111),
    ('delta-festival', 'Daniella Da Silva', 112),
    ('delta-festival', 'Omaks', 113),
    ('delta-festival', 'Paga', 114),
    ('delta-festival', 'Sköne', 115),
    ('delta-festival', 'Kevin De Vries', 116),
    ('delta-festival', 'Miki', 117),
    ('delta-festival', 'Thylacine', 118),
    ('delta-festival', 'TK', 119),
    ('delta-festival', 'Trinix', 120),
    ('delta-festival', 'Lilly Palmer', 121),
    ('delta-festival', 'Bellini', 122),
    ('delta-festival', 'Notmytype', 123),
    ('positiv', 'Boris Brejcha', 100),
    ('positiv', 'Carla Schmitt', 101),
    ('positiv', 'Nicolas Cuer', 102),
    ('positiv', 'Charlotte de Witte', 103),
    ('positiv', 'Marlon Hoffstadt', 104),
    ('positiv', 'Novah', 105),
    ('positiv', 'Biianco', 106),
    ('positiv', 'Fisher', 107),
    ('positiv', 'Venga', 108),
    ('lovefest', 'Marco Carola', 100),
    ('lovefest', 'Adam Beyer', 101),
    ('lovefest', 'Enrico Sangiuliano', 102),
    ('verknipt', 'APRD', 100),
    ('verknipt', 'Zuke', 101),
    ('verknipt', 'AREA ØNE', 102),
    ('verknipt', 'Ben Techy', 103),
    ('verknipt', 'Blurred Movement', 104),
    ('verknipt', 'Ramøn', 105),
    ('verknipt', 'BYØRN', 106),
    ('verknipt', 'DROS', 107),
    ('verknipt', 'Juul Exler', 108),
    ('verknipt', 'Entasia', 109),
    ('verknipt', 'Freddi', 110),
    ('verknipt', 'Fantasm', 111),
    ('verknipt', 'Føss', 112),
    ('verknipt', 'FUMI', 113),
    ('verknipt', 'Jånks', 114),
    ('verknipt', 'Hurts', 115),
    ('verknipt', 'NYCO', 116),
    ('verknipt', 'Inafekt', 117),
    ('verknipt', 'NewTone', 118),
    ('verknipt', 'Iosio', 119),
    ('verknipt', 'JALO', 120),
    ('verknipt', 'Vino', 121),
    ('verknipt', 'Jazzy', 122),
    ('verknipt', 'Jowi', 123),
    ('verknipt', 'JO3Y3T', 124),
    ('verknipt', 'Karah', 125),
    ('verknipt', 'KLOFAMA', 126),
    ('verknipt', 'LS41', 127),
    ('verknipt', 'Nzgûl', 128),
    ('verknipt', 'SANTØS', 129),
    ('verknipt', 'SuP', 130),
    ('verknipt', 'TASSERY', 131),
    ('verknipt', 'WILDERÍCH', 132),
    ('verknipt', 'zwilling', 133),
    ('verknipt', 'Winson', 134),
    ('verknipt', 'LØREN', 135),
    ('verknipt', 'Nikolina', 136),
    ('verknipt', 'Rebekah', 137),
    ('verknipt', '6EJOU', 138),
    ('verknipt', 'APHØTIC', 139),
    ('verknipt', 'BLNK', 140),
    ('verknipt', 'Lieks', 141),
    ('verknipt', 'BØĘRY', 142),
    ('verknipt', 'Cloudy', 143),
    ('verknipt', 'KUKO', 144),
    ('verknipt', 'Cortes', 145),
    ('verknipt', 'NØRAJ', 146),
    ('verknipt', 'Davyboi', 147),
    ('verknipt', 'Franck', 148),
    ('verknipt', 'Divasi', 149),
    ('verknipt', 'DJ IP', 150),
    ('verknipt', 'Dr G', 151),
    ('verknipt', 'Serafina', 152),
    ('verknipt', 'hardsok', 153),
    ('verknipt', 'Jayron', 154),
    ('verknipt', 'Johannes Schuster', 155),
    ('verknipt', 'Justin Jay', 156),
    ('verknipt', 'Rozie', 157),
    ('verknipt', 'Katy Rough', 158),
    ('verknipt', 'Kruelty', 159),
    ('verknipt', 'Neek', 160),
    ('verknipt', 'Nicolas Julian', 161),
    ('verknipt', 'Pawlowski', 162),
    ('verknipt', 'PETERBLUE', 163),
    ('verknipt', 'Raxeller', 164),
    ('verknipt', 'Restricted', 165),
    ('verknipt', 'Rowin', 166),
    ('verknipt', 'SLVL', 167),
    ('verknipt', 'USH', 168),
    ('verknipt', 'TITI', 169),
    ('verknipt', 'Toxic Machinery', 170),
    ('verknipt', 'Vieze Asbak', 171),
    ('verknipt', 'Xamuel', 172)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;
