-- ============================================================
-- Lineup gap-fill for the 40 soonest upcoming (Aug-Sep 2026) dated
-- editions that had no lineup at all, researched 2026-08-05.
--
-- Only officially-announced lineups were added (poster reveals,
-- official site/socials, or a named outlet reporting the official
-- bill) -- artists are stored in billing order (headliner first).
-- 37 of the 40 got a real lineup; the other 3 didn't:
--   burning-man    -- leaderless, participant-driven event, no
--                     artist bill in the traditional sense
--   dream-village  -- 2026 lineup genuinely not announced yet
--   sonus          -- confirmed CANCELLED for 2026 outright (not just
--                     lineup-less) -- its now-invalid 2026 edition row
--                     is removed below rather than left dangling,
--                     same treatment Mysteryland got in
--                     lot2_dated_no_lineup_festivals.sql when it
--                     turned out to be skipping a year.
-- ============================================================

delete from public.festival_editions e
using public.festivals f
where e.festival_id = f.id and f.slug = 'sonus' and e.year = 2026;

-- 37 festivals, 324 distinct artist names
insert into public.artists (name)
select v.name
from (values
  ('A Day to Remember'),
  ('Adam Beyer'),
  ('Adam Ten'),
  ('Airbourne'),
  ('Alan Walker'),
  ('Alarico'),
  ('Alcest'),
  ('Alestorm'),
  ('Alexis Taylor'),
  ('Alisha'),
  ('Alpha Blondy'),
  ('Aly$hia'),
  ('Amelie Lens'),
  ('Amorphis'),
  ('Amyl and The Sniffers'),
  ('Andy C'),
  ('Anfisa Letyago'),
  ('Angerfist'),
  ('Anna Calvi'),
  ('Anyma'),
  ('Arch Enemy'),
  ('Armand Van Helden'),
  ('Armin van Buuren'),
  ('ARTBAT'),
  ('Ashnikko'),
  ('Aurora Halal'),
  ('AVAION'),
  ('Avangart Tabldot'),
  ('Avenged Sevenfold'),
  ('Axwell'),
  ('Baby Keem'),
  ('BABYMETAL'),
  ('Bedouin'),
  ('Ben Klock'),
  ('Ben Sims'),
  ('Ben UFO'),
  ('Benny Benassi'),
  ('Biffy Clyro'),
  ('Biga Ranx'),
  ('Biianco'),
  ('Blawan'),
  ('Blood Orange'),
  ('Boris Brejcha'),
  ('Bring Me The Horizon'),
  ('Butch'),
  ('Call Super'),
  ('Calvin Harris'),
  ('CamelPhat'),
  ('Capo Plaza'),
  ('Caribou'),
  ('Carl Cox'),
  ('Carla Schmitt'),
  ('Carla''s Dreams'),
  ('Carpenter Brut'),
  ('CCL'),
  ('Charles B'),
  ('Charli xcx'),
  ('Charlotte de Witte'),
  ('Chase & Status'),
  ('Chris Liebing'),
  ('Chris Stussy'),
  ('Clipse'),
  ('CMAT'),
  ('Cryptopsy'),
  ('Damian Lazarus'),
  ('Dave'),
  ('David Byrne'),
  ('Dax J'),
  ('Death Cab for Cutie'),
  ('Deborah De Luca'),
  ('Deftones'),
  ('Demi Lovato'),
  ('Derrick Carter'),
  ('Diego Miranda'),
  ('Dimitri Vegas'),
  ('Disclosure'),
  ('Dixon'),
  ('DJ Aya'),
  ('DJ Gigola'),
  ('DJ Koze'),
  ('DJ Nobu'),
  ('DJ Seinfeld'),
  ('Djo'),
  ('DMX Krew'),
  ('Dom Dolla'),
  ('Dotan'),
  ('Dub Inc'),
  ('Dubfire'),
  ('Duke Dumont'),
  ('DVS1'),
  ('Dyed Soundorom'),
  ('Earl Sweatshirt'),
  ('Ellen Allien'),
  ('Elton John'),
  ('Empire of the Sun'),
  ('English Teacher'),
  ('Enrico Sangiuliano'),
  ('Eric Prydz'),
  ('Eve'),
  ('Ezra Collective'),
  ('Faithless'),
  ('Fatboy Slim'),
  ('FISHER'),
  ('FKA twigs'),
  ('Flo Rida'),
  ('Floating Points'),
  ('Florence + The Machine'),
  ('Fontaines D.C.'),
  ('Foo Fighters'),
  ('Four Tet'),
  ('Franz Ferdinand'),
  ('Geese'),
  ('Gilberto Gil'),
  ('Gojira'),
  ('Goldie'),
  ('Gorillaz'),
  ('Green Velvet'),
  ('Gretel'),
  ('Hannah Laing'),
  ('Hatebreed'),
  ('Helena Hauff'),
  ('Helloween'),
  ('Henning Baer'),
  ('Honey Dijon'),
  ('Hot Since 82'),
  ('HVOB'),
  ('Héctor Oaks'),
  ('I Hate Models'),
  ('In Flames'),
  ('Indira Paganotto'),
  ('Interplanetary Criminal'),
  ('Iron Maiden'),
  ('Italobrothers'),
  ('J Balvin'),
  ('Jade'),
  ('JADE'),
  ('James Hype'),
  ('Jamie Jones'),
  ('Jamiroquai'),
  ('Jane Fitz'),
  ('Japanese Breakfast'),
  ('Jeff Mills'),
  ('Job Jobse'),
  ('John Summit'),
  ('John Talabot'),
  ('Joris Voorn'),
  ('Jorja Smith'),
  ('Joseph Capriati'),
  ('JPEGMAFIA'),
  ('Judas Priest'),
  ('Kasabian'),
  ('Keo'),
  ('Kerri Chandler'),
  ('Kettama'),
  ('KI/KI'),
  ('KIM SWIM'),
  ('Klangkuenstler'),
  ('Kneecap'),
  ('Kobosil'),
  ('Kompromat'),
  ('Kygo'),
  ('L''Arc-en-Ciel'),
  ('Lamb of God'),
  ('Lauren Auder'),
  ('Laurent Garnier'),
  ('LCD Soundsystem'),
  ('LE SSERAFIM'),
  ('Len Faki'),
  ('Leprous'),
  ('Lewis Capaldi'),
  ('Lilly Palmer'),
  ('Limp Bizkit'),
  ('Loco Dice'),
  ('Lorde'),
  ('Loredana'),
  ('Louie Vega'),
  ('Lowertown'),
  ('Loyle Carner'),
  ('Luciano'),
  ('Luke Slater'),
  ('Lykke Li'),
  ('Maceo Plex'),
  ('Machine Gun Kelly'),
  ('Madness'),
  ('Major Lazer'),
  ('Major Lazer Soundsystem'),
  ('Mall Grab'),
  ('Malugi'),
  ('Marcellus Pittman'),
  ('Marco Carola'),
  ('Maribou State'),
  ('Marie Davidson'),
  ('Marlon Hoffstadt'),
  ('Maroon 5'),
  ('Marshmello'),
  ('Martin Garrix'),
  ('MATTN'),
  ('Mau P'),
  ('MCR-T'),
  ('Megadeth'),
  ('Michael Bibi'),
  ('Mind Against'),
  ('MIRA'),
  ('Moby'),
  ('Mochakk'),
  ('Modest Mouse'),
  ('Mogwai'),
  ('MRAK'),
  ('My Chemical Romance'),
  ('Nia Archives'),
  ('Nick Cave & The Bad Seeds'),
  ('Nick Cave and the Bad Seeds'),
  ('Nicky Romero'),
  ('Nicolas Cuer'),
  ('Nicole Moudaber'),
  ('Nina Kraviz'),
  ('Novah'),
  ('Objekt'),
  ('Olive F'),
  ('Oliver Heldens'),
  ('OMIKI'),
  ('Overmono'),
  ('Pale Waves'),
  ('Pan-Pot'),
  ('Pantera'),
  ('Papa Roach'),
  ('Paradise Lost'),
  ('Parcels'),
  ('Paul Kalkbrenner'),
  ('Paul van Dyk'),
  ('Pavement'),
  ('Pawsa'),
  ('Peach'),
  ('Peaches'),
  ('Pedro Sampaio'),
  ('Peggy Gou'),
  ('Peverelist'),
  ('Pierce the Veil'),
  ('Prosumer'),
  ('Protoje'),
  ('Puya'),
  ('Queen Omega'),
  ('Raphael Palacci'),
  ('Raresh'),
  ('Ravyn Lenae'),
  ('RAYE'),
  ('Reinier Zonneveld'),
  ('Rhadoo'),
  ('Ricardo Villalobos'),
  ('Richie Hawtin'),
  ('Rise Against'),
  ('Rivo'),
  ('Ryan Elliott'),
  ('Rødhåd'),
  ('Rüfüs Du Sol'),
  ('Sakanaction'),
  ('Sammy Virji'),
  ('Sara Landry'),
  ('Sasha & John Digweed'),
  ('Saxon'),
  ('Scissor Sisters'),
  ('Scooter'),
  ('Seth Troxler'),
  ('Shaggy'),
  ('Shame'),
  ('Shanti Celeste'),
  ('Shenseea'),
  ('Sickick'),
  ('Simo Cell'),
  ('Skepta'),
  ('Skrillex'),
  ('Slaughter to Prevail'),
  ('Solomun'),
  ('Sombr'),
  ('Sonja Moonear'),
  ('Sonny Fodera'),
  ('Soulfly'),
  ('Soulwax'),
  ('Sparks'),
  ('Speedy J'),
  ('Steel Pulse'),
  ('Stephan Bodzin'),
  ('Steve Aoki'),
  ('Sting'),
  ('Stray Kids'),
  ('Sublime'),
  ('Suede'),
  ('Sven Väth'),
  ('Swae Lee'),
  ('Swedish House Mafia'),
  ('Tedua'),
  ('The Avalanches'),
  ('The Beths'),
  ('The Chainsmokers'),
  ('The Cure'),
  ('The Hacker'),
  ('The Hives'),
  ('The Itals'),
  ('The Martinez Brothers'),
  ('The Prodigy'),
  ('The Skatalites'),
  ('The Strokes'),
  ('The xx'),
  ('Timmy Trumpet'),
  ('Tiësto'),
  ('Tool'),
  ('TR/ST'),
  ('Turnstile'),
  ('Twenty One Pilots'),
  ('Tyga'),
  ('Tyler, The Creator'),
  ('Underworld'),
  ('Vanroose'),
  ('Venga'),
  ('Vintage Culture'),
  ('VTSS'),
  ('Wednesday 13'),
  ('Wet Leg'),
  ('WhoMadeWho'),
  ('Wilco'),
  ('Wolf Alice'),
  ('Wu-Tang Clan'),
  ('Wunderhorse'),
  ('Zara Larsson')
) as v(name)
where not exists (
  select 1 from public.artists a where lower(a.name) = lower(v.name)
);

with lineup(slug, artist_name, order_index) as (
  values
    ('arc', 'Anyma', 0),
    ('arc', 'Underworld', 1),
    ('arc', 'Michael Bibi', 2),
    ('arc', 'Honey Dijon', 3),
    ('arc', 'Sara Landry', 4),
    ('arc', 'Mochakk', 5),
    ('arc', 'Mau P', 6),
    ('arc', 'Chase & Status', 7),
    ('arc', 'Vintage Culture', 8),
    ('arc', 'Damian Lazarus', 9),
    ('arc', 'Nia Archives', 10),
    ('arc', 'Chris Stussy', 11),
    ('arc', 'Green Velvet', 12),
    ('arc', 'Derrick Carter', 13),
    ('bloodstock-open-air', 'Judas Priest', 0),
    ('bloodstock-open-air', 'Lamb of God', 1),
    ('bloodstock-open-air', 'Slaughter to Prevail', 2),
    ('bloodstock-open-air', 'Saxon', 3),
    ('bloodstock-open-air', 'Cryptopsy', 4),
    ('bloodstock-open-air', 'Wednesday 13', 5),
    ('bloodstock-open-air', 'Leprous', 6),
    ('bloodstock-open-air', 'Carpenter Brut', 7),
    ('boomtown', 'Kneecap', 0),
    ('boomtown', 'Scissor Sisters', 1),
    ('boomtown', 'Madness', 2),
    ('boomtown', 'Skrillex', 3),
    ('boomtown', 'Four Tet', 4),
    ('boomtown', 'Faithless', 5),
    ('boomtown', 'Scooter', 6),
    ('boomtown', 'Shaggy', 7),
    ('boomtown', 'Eve', 8),
    ('boomtown', 'Ashnikko', 9),
    ('brunch-electronik', 'Solomun', 0),
    ('brunch-electronik', 'Paul Kalkbrenner', 1),
    ('brunch-electronik', 'Mind Against', 2),
    ('brunch-electronik', 'WhoMadeWho', 3),
    ('brunch-electronik', 'Butch', 4),
    ('brunch-electronik', 'Rivo', 5),
    ('brunch-electronik', 'Vanroose', 6),
    ('brunch-electronik', 'Avangart Tabldot', 7),
    ('brunch-electronik', 'Raphael Palacci', 8),
    ('creamfields', 'Disclosure', 0),
    ('creamfields', 'Calvin Harris', 1),
    ('creamfields', 'Swedish House Mafia', 2),
    ('creamfields', 'Sonny Fodera', 3),
    ('creamfields', 'Carl Cox', 4),
    ('creamfields', 'Armin van Buuren', 5),
    ('creamfields', 'Duke Dumont', 6),
    ('creamfields', 'John Summit', 7),
    ('creamfields', 'Andy C', 8),
    ('creamfields', 'Amelie Lens', 9),
    ('creamfields', 'Underworld', 10),
    ('creamfields', 'Chris Stussy', 11),
    ('creamfields', 'Armand Van Helden', 12),
    ('decibel-open-air', 'Paul Kalkbrenner', 0),
    ('decibel-open-air', 'Capo Plaza', 1),
    ('decibel-open-air', 'Tedua', 2),
    ('decibel-open-air', 'Adam Beyer', 3),
    ('decibel-open-air', 'Benny Benassi', 4),
    ('decibel-open-air', 'Maceo Plex', 5),
    ('decibel-open-air', 'Reinier Zonneveld', 6),
    ('decibel-open-air', 'Blawan', 7),
    ('decibel-open-air', 'DJ Nobu', 8),
    ('decibel-open-air', 'Len Faki', 9),
    ('decibel-open-air', 'DVS1', 10),
    ('decibel-open-air', 'Indira Paganotto', 11),
    ('dimensions', 'John Talabot', 0),
    ('dimensions', 'The Hacker', 1),
    ('dimensions', 'Objekt', 2),
    ('dimensions', 'Prosumer', 3),
    ('dimensions', 'Raresh', 4),
    ('dimensions', 'Marcellus Pittman', 5),
    ('dimensions', 'Jane Fitz', 6),
    ('dimensions', 'Sonja Moonear', 7),
    ('dimensions', 'Ryan Elliott', 8),
    ('dimensions', 'Dyed Soundorom', 9),
    ('dimensions', 'DMX Krew', 10),
    ('echelon-festival', 'Charlotte de Witte', 0),
    ('echelon-festival', 'Boris Brejcha', 1),
    ('echelon-festival', 'Paul van Dyk', 2),
    ('echelon-festival', 'Deborah De Luca', 3),
    ('echelon-festival', 'Kobosil', 4),
    ('echelon-festival', 'I Hate Models', 5),
    ('echelon-festival', 'Angerfist', 6),
    ('echelon-festival', 'AVAION', 7),
    ('echelon-festival', 'Lilly Palmer', 8),
    ('electric-picnic', 'Fontaines D.C.', 0),
    ('electric-picnic', 'Gorillaz', 1),
    ('electric-picnic', 'CMAT', 2),
    ('electric-picnic', 'Wunderhorse', 3),
    ('electric-picnic', 'Zara Larsson', 4),
    ('electric-picnic', 'Wolf Alice', 5),
    ('electric-picnic', 'Djo', 6),
    ('electric-picnic', 'JADE', 7),
    ('electric-picnic', 'Skepta', 8),
    ('electric-picnic', 'Loyle Carner', 9),
    ('electric-picnic', 'Ravyn Lenae', 10),
    ('electric-picnic', 'Duke Dumont', 11),
    ('electric-picnic', 'Geese', 12),
    ('electric-picnic', 'JPEGMAFIA', 13),
    ('fly-open-air', 'Kerri Chandler', 0),
    ('fly-open-air', 'Sammy Virji', 1),
    ('fly-open-air', 'Interplanetary Criminal', 2),
    ('fly-open-air', 'Alisha', 3),
    ('fly-open-air', 'Olive F', 4),
    ('glitch', 'Amelie Lens', 0),
    ('glitch', 'Ben Klock', 1),
    ('glitch', 'Rødhåd', 2),
    ('glitch', 'Job Jobse', 3),
    ('glitch', 'Chris Stussy', 4),
    ('glitch', 'VTSS', 5),
    ('glitch', 'Alarico', 6),
    ('glitch', 'Mall Grab', 7),
    ('glitch', 'KI/KI', 8),
    ('glitch', 'Henning Baer', 9),
    ('green-man-festival', 'Mogwai', 0),
    ('green-man-festival', 'Wilco', 1),
    ('green-man-festival', 'Four Tet', 2),
    ('green-man-festival', 'Wolf Alice', 3),
    ('green-man-festival', 'Sparks', 4),
    ('green-man-festival', 'The Beths', 5),
    ('green-man-festival', 'Anna Calvi', 6),
    ('houghton', 'Ben UFO', 0),
    ('houghton', 'Ricardo Villalobos', 1),
    ('houghton', 'Peach', 2),
    ('houghton', 'Call Super', 3),
    ('houghton', 'Shanti Celeste', 4),
    ('houghton', 'Helena Hauff', 5),
    ('houghton', 'Objekt', 6),
    ('houghton', 'Marie Davidson', 7),
    ('houghton', 'CCL', 8),
    ('houghton', 'Aurora Halal', 9),
    ('houghton', 'Rhadoo', 10),
    ('houghton', 'Peverelist', 11),
    ('houghton', 'Simo Cell', 12),
    ('lost-village', 'Overmono', 0),
    ('lost-village', 'Soulwax', 1),
    ('lost-village', 'The Avalanches', 2),
    ('lost-village', 'Caribou', 3),
    ('lost-village', 'Solomun', 4),
    ('lost-village', 'Peggy Gou', 5),
    ('lost-village', 'Ben UFO', 6),
    ('lost-village', 'DJ Koze', 7),
    ('lost-village', 'Dixon', 8),
    ('lost-village', 'Seth Troxler', 9),
    ('lost-village', 'Ezra Collective', 10),
    ('lost-village', 'DJ Seinfeld', 11),
    ('louder-than-life', 'Iron Maiden', 0),
    ('louder-than-life', 'My Chemical Romance', 1),
    ('louder-than-life', 'Limp Bizkit', 2),
    ('louder-than-life', 'Tool', 3),
    ('louder-than-life', 'Pantera', 4),
    ('louder-than-life', 'Megadeth', 5),
    ('louder-than-life', 'Pierce the Veil', 6),
    ('louder-than-life', 'A Day to Remember', 7),
    ('louder-than-life', 'Papa Roach', 8),
    ('louder-than-life', 'Sublime', 9),
    ('louder-than-life', 'Gojira', 10),
    ('louder-than-life', 'The Prodigy', 11),
    ('louder-than-life', 'BABYMETAL', 12),
    ('lovefest', 'Charlotte de Witte', 0),
    ('lovefest', 'Marco Carola', 1),
    ('lovefest', 'Adam Beyer', 2),
    ('lovefest', 'Enrico Sangiuliano', 3),
    ('lovefest', 'ARTBAT', 4),
    ('lovefest', 'Nina Kraviz', 5),
    ('lovefest', 'Loco Dice', 6),
    ('lovefest', 'Anfisa Letyago', 7),
    ('lovefest', 'Deborah De Luca', 8),
    ('lovefest', 'Louie Vega', 9),
    ('lovefest', 'Pan-Pot', 10),
    ('loveland', 'Sven Väth', 0),
    ('loveland', 'Sasha & John Digweed', 1),
    ('loveland', 'Fatboy Slim', 2),
    ('loveland', 'Eric Prydz', 3),
    ('loveland', 'Ben Klock', 4),
    ('loveland', 'Hot Since 82', 5),
    ('loveland', 'CamelPhat', 6),
    ('loveland', 'Mau P', 7),
    ('loveland', 'Chris Liebing', 8),
    ('loveland', 'Speedy J', 9),
    ('loveland', 'Nicole Moudaber', 10),
    ('loveland', 'Joris Voorn', 11),
    ('lowlands', 'Tyler, The Creator', 0),
    ('lowlands', 'Lorde', 1),
    ('lowlands', 'Sombr', 2),
    ('lowlands', 'Major Lazer', 3),
    ('lowlands', 'Maribou State', 4),
    ('lowlands', 'Turnstile', 5),
    ('lowlands', 'Amyl and The Sniffers', 6),
    ('lowlands', 'Blood Orange', 7),
    ('lowlands', 'Clipse', 8),
    ('lowlands', 'Floating Points', 9),
    ('lowlands', 'JPEGMAFIA', 10),
    ('lowlands', 'Nia Archives', 11),
    ('lowlands', 'Richie Hawtin', 12),
    ('lowlands', 'Steel Pulse', 13),
    ('lowlands', 'Parcels', 14),
    ('medusa', 'Tiësto', 0),
    ('medusa', 'Carl Cox', 1),
    ('medusa', 'Marco Carola', 2),
    ('medusa', 'Dimitri Vegas', 3),
    ('medusa', 'Steve Aoki', 4),
    ('medusa', 'Timmy Trumpet', 5),
    ('medusa', 'Adam Beyer', 6),
    ('medusa', 'James Hype', 7),
    ('medusa', 'Nicky Romero', 8),
    ('medusa', 'Angerfist', 9),
    ('medusa', 'Oliver Heldens', 10),
    ('medusa', 'Mau P', 11),
    ('neopop', 'Rødhåd', 0),
    ('neopop', 'Ben Klock', 1),
    ('neopop', 'Jeff Mills', 2),
    ('neopop', 'Joseph Capriati', 3),
    ('neopop', 'Nina Kraviz', 4),
    ('neopop', 'Goldie', 5),
    ('neopop', 'Dubfire', 6),
    ('neopop', 'Luke Slater', 7),
    ('neopop', 'Ellen Allien', 8),
    ('neopop', 'Laurent Garnier', 9),
    ('neopop', 'Chris Liebing', 10),
    ('neopop', 'Ben Sims', 11),
    ('nibirii', 'I Hate Models', 0),
    ('nibirii', 'Klangkuenstler', 1),
    ('nibirii', 'Marlon Hoffstadt', 2),
    ('nibirii', 'Héctor Oaks', 3),
    ('nibirii', 'Hannah Laing', 4),
    ('nibirii', 'DJ Aya', 5),
    ('nibirii', 'DJ Gigola', 6),
    ('nibirii', 'KIM SWIM', 7),
    ('nibirii', 'Malugi', 8),
    ('nibirii', 'MCR-T', 9),
    ('nibirii', 'Dax J', 10),
    ('outside-lands', 'Charli xcx', 0),
    ('outside-lands', 'Rüfüs Du Sol', 1),
    ('outside-lands', 'The Strokes', 2),
    ('outside-lands', 'The xx', 3),
    ('outside-lands', 'Baby Keem', 4),
    ('outside-lands', 'Turnstile', 5),
    ('outside-lands', 'Djo', 6),
    ('outside-lands', 'Empire of the Sun', 7),
    ('outside-lands', 'Death Cab for Cutie', 8),
    ('outside-lands', 'Modest Mouse', 9),
    ('outside-lands', 'Clipse', 10),
    ('outside-lands', 'Wet Leg', 11),
    ('panorama', 'Solomun', 0),
    ('panorama', 'Peggy Gou', 1),
    ('panorama', 'Mochakk', 2),
    ('panorama', 'Pawsa', 3),
    ('panorama', 'Mau P', 4),
    ('panorama', 'Jamie Jones', 5),
    ('panorama', 'Seth Troxler', 6),
    ('panorama', 'The Martinez Brothers', 7),
    ('positiv', 'Boris Brejcha', 0),
    ('positiv', 'Charlotte de Witte', 1),
    ('positiv', 'FISHER', 2),
    ('positiv', 'Marlon Hoffstadt', 3),
    ('positiv', 'Novah', 4),
    ('positiv', 'Biianco', 5),
    ('positiv', 'Carla Schmitt', 6),
    ('positiv', 'Nicolas Cuer', 7),
    ('positiv', 'Venga', 8),
    ('primer', 'Axwell', 0),
    ('primer', 'Armand Van Helden', 1),
    ('primer', 'MRAK', 2),
    ('primer', 'Adam Ten', 3),
    ('primer', 'Stephan Bodzin', 4),
    ('primer', 'Bedouin', 5),
    ('primer', 'OMIKI', 6),
    ('reading-festival', 'Charli xcx', 0),
    ('reading-festival', 'Chase & Status', 1),
    ('reading-festival', 'Dave', 2),
    ('reading-festival', 'Florence + The Machine', 3),
    ('reading-festival', 'Fontaines D.C.', 4),
    ('reading-festival', 'RAYE', 5),
    ('reading-festival', 'Skepta', 6),
    ('reading-festival', 'Jade', 7),
    ('reading-festival', 'Kneecap', 8),
    ('reading-festival', 'Kettama', 9),
    ('reading-festival', 'Geese', 10),
    ('reeperbahn-festival', 'English Teacher', 0),
    ('reeperbahn-festival', 'Keo', 1),
    ('reeperbahn-festival', 'Shame', 2),
    ('reeperbahn-festival', 'Gretel', 3),
    ('reeperbahn-festival', 'Lowertown', 4),
    ('reeperbahn-festival', 'Alexis Taylor', 5),
    ('reeperbahn-festival', 'Lauren Auder', 6),
    ('reeperbahn-festival', 'Pale Waves', 7),
    ('reeperbahn-festival', 'Dotan', 8),
    ('reeperbahn-festival', 'HVOB', 9),
    ('reeperbahn-festival', 'TR/ST', 10),
    ('rock-en-seine', 'The Cure', 0),
    ('rock-en-seine', 'Nick Cave & The Bad Seeds', 1),
    ('rock-en-seine', 'Tyler, The Creator', 2),
    ('rock-en-seine', 'Deftones', 3),
    ('rock-en-seine', 'Turnstile', 4),
    ('rock-en-seine', 'Franz Ferdinand', 5),
    ('rock-en-seine', 'Sparks', 6),
    ('rock-en-seine', 'Kompromat', 7),
    ('rock-en-seine', 'Clipse', 8),
    ('rock-en-seine', 'Mogwai', 9),
    ('rock-en-seine', 'Wolf Alice', 10),
    ('rock-en-seine', 'Peaches', 11),
    ('rock-en-seine', 'Lykke Li', 12),
    ('rock-in-rio', 'Foo Fighters', 0),
    ('rock-in-rio', 'Elton John', 1),
    ('rock-in-rio', 'Maroon 5', 2),
    ('rock-in-rio', 'Avenged Sevenfold', 3),
    ('rock-in-rio', 'Jamiroquai', 4),
    ('rock-in-rio', 'Stray Kids', 5),
    ('rock-in-rio', 'Bring Me The Horizon', 6),
    ('rock-in-rio', 'Machine Gun Kelly', 7),
    ('rock-in-rio', 'Demi Lovato', 8),
    ('rock-in-rio', 'J Balvin', 9),
    ('rock-in-rio', 'Gilberto Gil', 10),
    ('rock-in-rio', 'Rise Against', 11),
    ('rock-in-rio', 'The Hives', 12),
    ('rock-in-rio', 'Pedro Sampaio', 13),
    ('rototom-sunsplash', 'Major Lazer Soundsystem', 0),
    ('rototom-sunsplash', 'Alpha Blondy', 1),
    ('rototom-sunsplash', 'Luciano', 2),
    ('rototom-sunsplash', 'Shenseea', 3),
    ('rototom-sunsplash', 'Protoje', 4),
    ('rototom-sunsplash', 'The Skatalites', 5),
    ('rototom-sunsplash', 'Queen Omega', 6),
    ('rototom-sunsplash', 'Dub Inc', 7),
    ('rototom-sunsplash', 'Biga Ranx', 8),
    ('rototom-sunsplash', 'The Itals', 9),
    ('saga', 'Tyga', 0),
    ('saga', 'Sickick', 1),
    ('saga', 'Loredana', 2),
    ('saga', 'Carla''s Dreams', 3),
    ('saga', 'Diego Miranda', 4),
    ('saga', 'Puya', 5),
    ('saga', 'Aly$hia', 6),
    ('saga', 'Italobrothers', 7),
    ('saga', 'Charles B', 8),
    ('saga', 'MATTN', 9),
    ('saga', 'MIRA', 10),
    ('shaky-knees-festival', 'The Strokes', 0),
    ('shaky-knees-festival', 'Gorillaz', 1),
    ('shaky-knees-festival', 'Twenty One Pilots', 2),
    ('shaky-knees-festival', 'Pavement', 3),
    ('shaky-knees-festival', 'Turnstile', 4),
    ('shaky-knees-festival', 'LCD Soundsystem', 5),
    ('shaky-knees-festival', 'Wu-Tang Clan', 6),
    ('shaky-knees-festival', 'Fontaines D.C.', 7),
    ('shaky-knees-festival', 'Modest Mouse', 8),
    ('shaky-knees-festival', 'The Prodigy', 9),
    ('shaky-knees-festival', 'Japanese Breakfast', 10),
    ('summer-breeze-open-air', 'Helloween', 0),
    ('summer-breeze-open-air', 'In Flames', 1),
    ('summer-breeze-open-air', 'Lamb of God', 2),
    ('summer-breeze-open-air', 'Arch Enemy', 3),
    ('summer-breeze-open-air', 'Airbourne', 4),
    ('summer-breeze-open-air', 'Hatebreed', 5),
    ('summer-breeze-open-air', 'Alcest', 6),
    ('summer-breeze-open-air', 'Paradise Lost', 7),
    ('summer-breeze-open-air', 'Saxon', 8),
    ('summer-breeze-open-air', 'Amorphis', 9),
    ('summer-breeze-open-air', 'Soulfly', 10),
    ('summer-breeze-open-air', 'Alestorm', 11),
    ('summer-sonic', 'L''Arc-en-Ciel', 0),
    ('summer-sonic', 'Jamiroquai', 1),
    ('summer-sonic', 'The Strokes', 2),
    ('summer-sonic', 'David Byrne', 3),
    ('summer-sonic', 'BABYMETAL', 4),
    ('summer-sonic', 'LE SSERAFIM', 5),
    ('summer-sonic', 'FKA twigs', 6),
    ('summer-sonic', 'Kasabian', 7),
    ('summer-sonic', 'Suede', 8),
    ('summer-sonic', 'Sakanaction', 9),
    ('sziget', 'Bring Me The Horizon', 0),
    ('sziget', 'Florence + The Machine', 1),
    ('sziget', 'Twenty One Pilots', 2),
    ('sziget', 'Skrillex', 3),
    ('sziget', 'Skepta', 4),
    ('sziget', 'Zara Larsson', 5),
    ('sziget', 'Sombr', 6),
    ('sziget', 'Lewis Capaldi', 7),
    ('sziget', 'Jorja Smith', 8),
    ('sziget', 'Underworld', 9),
    ('sziget', 'Biffy Clyro', 10),
    ('sziget', 'Dom Dolla', 11),
    ('untold', 'Sting', 0),
    ('untold', 'Martin Garrix', 1),
    ('untold', 'Kygo', 2),
    ('untold', 'Marshmello', 3),
    ('untold', 'Flo Rida', 4),
    ('untold', 'Lewis Capaldi', 5),
    ('untold', 'Carl Cox', 6),
    ('untold', 'Solomun', 7),
    ('untold', 'The Chainsmokers', 8),
    ('untold', 'Steve Aoki', 9),
    ('untold', 'Zara Larsson', 10),
    ('untold', 'Alan Walker', 11),
    ('untold', 'Swae Lee', 12),
    ('way-out-west', 'Nick Cave and the Bad Seeds', 0),
    ('way-out-west', 'The Cure', 1),
    ('way-out-west', 'Gorillaz', 2),
    ('way-out-west', 'Lorde', 3),
    ('way-out-west', 'Moby', 4),
    ('way-out-west', 'The xx', 5),
    ('way-out-west', 'Clipse', 6),
    ('way-out-west', 'Zara Larsson', 7),
    ('way-out-west', 'Four Tet', 8),
    ('way-out-west', 'Earl Sweatshirt', 9),
    ('way-out-west', 'Blood Orange', 10)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;

update public.festival_editions e
set lineup_published = true
from public.festivals f
where e.festival_id = f.id
  and e.year = 2026
  and f.slug in (
    'arc',
    'bloodstock-open-air',
    'boomtown',
    'brunch-electronik',
    'creamfields',
    'decibel-open-air',
    'dimensions',
    'echelon-festival',
    'electric-picnic',
    'fly-open-air',
    'glitch',
    'green-man-festival',
    'houghton',
    'lost-village',
    'louder-than-life',
    'lovefest',
    'loveland',
    'lowlands',
    'medusa',
    'neopop',
    'nibirii',
    'outside-lands',
    'panorama',
    'positiv',
    'primer',
    'reading-festival',
    'reeperbahn-festival',
    'rock-en-seine',
    'rock-in-rio',
    'rototom-sunsplash',
    'saga',
    'shaky-knees-festival',
    'summer-breeze-open-air',
    'summer-sonic',
    'sziget',
    'untold',
    'way-out-west'
  );
