-- ============================================================
-- Lineup expansion pass 2 for thin 2026 editions: Ultra
-- Australia/South Africa, Parookaville, Lost Lands, Primavera
-- Sound, CRSSD, Glitch, Panorama, Thuishaven, Beyond Wonderland,
-- Dimensions, Snowbombing, DGTL, Terminal V, Hideout.
-- Sourced from official sites/DJ Mag/RA/EDM press.
-- Idempotent: guards on artist name / upserts on
-- (edition_id, artist_id) — safe to re-run.
-- ============================================================

insert into public.artists (name)
select v.name from (values
  ('The Chainsmokers'),
  ('DJ Snake'),
  ('Zedd'),
  ('Oliver Heldens'),
  ('Miss Monique'),
  ('Nico Moreno'),
  ('MaRLo'),
  ('Darren Styles'),
  ('Fatima Hajji'),
  ('Rebuke'),
  ('Rivo'),
  ('Oscar L'),
  ('KAAZE'),
  ('HI-LO'),
  ('Carter Walsh'),
  ('John Summit'),
  ('Axwell'),
  ('Afrojack'),
  ('R3HAB'),
  ('Apashe'),
  ('Kyle Watson'),
  ('DJ Kent'),
  ('Dennis Ferrer'),
  ('Shimza'),
  ('Major League DJz'),
  ('Scorpion Kings'),
  ('DBN Gogo'),
  ('Liquideep'),
  ('Sun-El Musician'),
  ('Armin van Buuren'),
  ('Charlotte de Witte'),
  ('Timmy Trumpet'),
  ('Felix Jaehn'),
  ('Alle Farben'),
  ('ATB'),
  ('Gestört aber GeiL'),
  ('Moguai'),
  ('Topic'),
  ('Don Diablo'),
  ('Blasterjaxx'),
  ('Bovski'),
  ('Cassian'),
  ('Jeffrey Sutorius'),
  ('Excision'),
  ('ILLENIUM'),
  ('Subtronics'),
  ('NGHTMRE'),
  ('Liquid Stranger'),
  ('Ganja White Night'),
  ('Seven Lions'),
  ('Wooli'),
  ('Flux Pavilion'),
  ('Doctor P'),
  ('FuntCase'),
  ('Crankdat'),
  ('Flosstradamus'),
  ('Zomboy'),
  ('Krewella'),
  ('ATLiens'),
  ('SLANDER'),
  ('Space Laces'),
  ('Doja Cat'),
  ('Massive Attack'),
  ('The Cure'),
  ('Addison Rae'),
  ('Skrillex'),
  ('The xx'),
  ('Gorillaz'),
  ('My Bloody Valentine'),
  ('Bad Gyal'),
  ('Peggy Gou'),
  ('Little Simz'),
  ('Kneecap'),
  ('Overmono'),
  ('Oklou'),
  ('Viagra Boys'),
  ('Ethel Cain'),
  ('Big Thief'),
  ('Blood Orange'),
  ('Olivia Rodrigo'),
  ('Cirez D'),
  ('Amelie Lens'),
  ('Dom Dolla'),
  ('The Martinez Brothers'),
  ('Vintage Culture'),
  ('Lane 8'),
  ('Polo & Pan'),
  ('TOKiMONSTA'),
  ('Tycho'),
  ('Cut Copy'),
  ('Modeselektor'),
  ('HoneyLuv'),
  ('Deborah De Luca'),
  ('Ben Klock'),
  ('Rødhåd'),
  ('Job Jobse'),
  ('Chris Stussy'),
  ('KI/KI'),
  ('Quelza'),
  ('Silva Bumpa'),
  ('VTSS'),
  ('Henning Baer'),
  ('BASHKKA'),
  ('Mall Grab'),
  ('Dax J'),
  ('Efdemin'),
  ('Solomun'),
  ('Mochakk'),
  ('Pawsa'),
  ('Mau P'),
  ('BLOND:ISH'),
  ('Jamie Jones'),
  ('Seth Troxler'),
  ('Erick E'),
  ('ROOG'),
  ('Dimitri'),
  ('Lucien Foort'),
  ('Steve Cop'),
  ('Klubbheads'),
  ('Tiësto'),
  ('Alison Wonderland'),
  ('Alok'),
  ('Steve Angello'),
  ('GRiZ'),
  ('Dabin'),
  ('Deorro'),
  ('DJ Diesel'),
  ('TroyBoi'),
  ('Matroda'),
  ('Black Tiger Sex Machine'),
  ('Eptic'),
  ('Giuseppe Ottaviani'),
  ('Ilan Bluestone'),
  ('Vini Vici'),
  ('Gareth Emery'),
  ('Bunney'),
  ('Radioactive Man'),
  ('Prosumer'),
  ('DJ Storm'),
  ('John Talabot'),
  ('The Hacker'),
  ('Objekt'),
  ('Margaret Dygas'),
  ('Jane Fitz'),
  ('Ryan Elliott'),
  ('Dyed Soundorom'),
  ('Maribou State'),
  ('De La Soul'),
  ('Orbital'),
  ('Hybrid Minds'),
  ('Sub Focus'),
  ('Folamour'),
  ('MJ Cole'),
  ('4am Kru'),
  ('Horse Meat Disco'),
  ('Joy Orbison'),
  ('Jayda G'),
  ('CamelPhat'),
  ('Âme'),
  ('DJ Tennis'),
  ('Armand van Helden'),
  ('Gerd Janson'),
  ('FJAAK'),
  ('Young Marco'),
  ('Avalon Emerson'),
  ('Sara Landry'),
  ('SPFDJ'),
  ('I Hate Models'),
  ('Clara Cuvé'),
  ('Robert Hood'),
  ('Patrick Topping'),
  ('Klangkuenstler'),
  ('East End Dubs'),
  ('Ben Hemsley'),
  ('Alan Fitzpatrick'),
  ('Skream'),
  ('Gorgon City'),
  ('LF SYSTEM'),
  ('Danny Howard'),
  ('Partiboi69'),
  ('Ewan McVicar'),
  ('Eliza Rose'),
  ('Kettama'),
  ('Paul Woolford'),
  ('Sam Divine'),
  ('Darius Syrossian')
) as v(name)
where not exists (select 1 from public.artists a where lower(a.name) = lower(v.name));

with lineup(slug, artist_name, order_index) as (
  values
    ('ultra-australia', 'The Chainsmokers', 100),
    ('ultra-australia', 'DJ Snake', 101),
    ('ultra-australia', 'Zedd', 102),
    ('ultra-australia', 'Oliver Heldens', 103),
    ('ultra-australia', 'Miss Monique', 104),
    ('ultra-australia', 'Nico Moreno', 105),
    ('ultra-australia', 'MaRLo', 106),
    ('ultra-australia', 'Darren Styles', 107),
    ('ultra-australia', 'Fatima Hajji', 108),
    ('ultra-australia', 'Rebuke', 109),
    ('ultra-australia', 'Rivo', 110),
    ('ultra-australia', 'Oscar L', 111),
    ('ultra-australia', 'KAAZE', 112),
    ('ultra-australia', 'HI-LO', 113),
    ('ultra-australia', 'Carter Walsh', 114),
    ('ultra-south-africa', 'John Summit', 100),
    ('ultra-south-africa', 'DJ Snake', 101),
    ('ultra-south-africa', 'Axwell', 102),
    ('ultra-south-africa', 'Afrojack', 103),
    ('ultra-south-africa', 'R3HAB', 104),
    ('ultra-south-africa', 'Apashe', 105),
    ('ultra-south-africa', 'Kyle Watson', 106),
    ('ultra-south-africa', 'DJ Kent', 107),
    ('ultra-south-africa', 'Dennis Ferrer', 108),
    ('ultra-south-africa', 'Shimza', 109),
    ('ultra-south-africa', 'Major League DJz', 110),
    ('ultra-south-africa', 'Scorpion Kings', 111),
    ('ultra-south-africa', 'DBN Gogo', 112),
    ('ultra-south-africa', 'Liquideep', 113),
    ('ultra-south-africa', 'Sun-El Musician', 114),
    ('parookaville', 'Armin van Buuren', 100),
    ('parookaville', 'Charlotte de Witte', 101),
    ('parookaville', 'The Chainsmokers', 102),
    ('parookaville', 'Timmy Trumpet', 103),
    ('parookaville', 'Axwell', 104),
    ('parookaville', 'Felix Jaehn', 105),
    ('parookaville', 'Alle Farben', 106),
    ('parookaville', 'ATB', 107),
    ('parookaville', 'Gestört aber GeiL', 108),
    ('parookaville', 'Moguai', 109),
    ('parookaville', 'Topic', 110),
    ('parookaville', 'Don Diablo', 111),
    ('parookaville', 'Blasterjaxx', 112),
    ('parookaville', 'Bovski', 113),
    ('parookaville', 'Cassian', 114),
    ('parookaville', 'Jeffrey Sutorius', 115),
    ('lost-lands', 'Excision', 100),
    ('lost-lands', 'ILLENIUM', 101),
    ('lost-lands', 'Subtronics', 102),
    ('lost-lands', 'NGHTMRE', 103),
    ('lost-lands', 'Liquid Stranger', 104),
    ('lost-lands', 'Ganja White Night', 105),
    ('lost-lands', 'Seven Lions', 106),
    ('lost-lands', 'Wooli', 107),
    ('lost-lands', 'Flux Pavilion', 108),
    ('lost-lands', 'Doctor P', 109),
    ('lost-lands', 'FuntCase', 110),
    ('lost-lands', 'Crankdat', 111),
    ('lost-lands', 'Flosstradamus', 112),
    ('lost-lands', 'Zomboy', 113),
    ('lost-lands', 'Krewella', 114),
    ('lost-lands', 'ATLiens', 115),
    ('lost-lands', 'SLANDER', 116),
    ('lost-lands', 'Space Laces', 117),
    ('primavera-sound', 'Doja Cat', 100),
    ('primavera-sound', 'Massive Attack', 101),
    ('primavera-sound', 'The Cure', 102),
    ('primavera-sound', 'Addison Rae', 103),
    ('primavera-sound', 'Skrillex', 104),
    ('primavera-sound', 'The xx', 105),
    ('primavera-sound', 'Gorillaz', 106),
    ('primavera-sound', 'My Bloody Valentine', 107),
    ('primavera-sound', 'Bad Gyal', 108),
    ('primavera-sound', 'Peggy Gou', 109),
    ('primavera-sound', 'Little Simz', 110),
    ('primavera-sound', 'Kneecap', 111),
    ('primavera-sound', 'Overmono', 112),
    ('primavera-sound', 'Oklou', 113),
    ('primavera-sound', 'Viagra Boys', 114),
    ('primavera-sound', 'Ethel Cain', 115),
    ('primavera-sound', 'Big Thief', 116),
    ('primavera-sound', 'Blood Orange', 117),
    ('primavera-sound', 'Olivia Rodrigo', 118),
    ('crssd', 'Cirez D', 100),
    ('crssd', 'Amelie Lens', 101),
    ('crssd', 'Dom Dolla', 102),
    ('crssd', 'The Martinez Brothers', 103),
    ('crssd', 'Vintage Culture', 104),
    ('crssd', 'Lane 8', 105),
    ('crssd', 'Polo & Pan', 106),
    ('crssd', 'TOKiMONSTA', 107),
    ('crssd', 'Tycho', 108),
    ('crssd', 'Cut Copy', 109),
    ('crssd', 'Modeselektor', 110),
    ('crssd', 'HoneyLuv', 111),
    ('crssd', 'Deborah De Luca', 112),
    ('glitch', 'Amelie Lens', 100),
    ('glitch', 'Ben Klock', 101),
    ('glitch', 'Rødhåd', 102),
    ('glitch', 'Job Jobse', 103),
    ('glitch', 'Chris Stussy', 104),
    ('glitch', 'KI/KI', 105),
    ('glitch', 'Quelza', 106),
    ('glitch', 'Silva Bumpa', 107),
    ('glitch', 'VTSS', 108),
    ('glitch', 'Henning Baer', 109),
    ('glitch', 'BASHKKA', 110),
    ('glitch', 'Mall Grab', 111),
    ('glitch', 'Dax J', 112),
    ('glitch', 'Efdemin', 113),
    ('panorama', 'Solomun', 100),
    ('panorama', 'Peggy Gou', 101),
    ('panorama', 'Mochakk', 102),
    ('panorama', 'Pawsa', 103),
    ('panorama', 'Mau P', 104),
    ('panorama', 'BLOND:ISH', 105),
    ('panorama', 'Vintage Culture', 106),
    ('panorama', 'Jamie Jones', 107),
    ('panorama', 'Seth Troxler', 108),
    ('panorama', 'The Martinez Brothers', 109),
    ('thuishaven', 'Erick E', 100),
    ('thuishaven', 'ROOG', 101),
    ('thuishaven', 'Dimitri', 102),
    ('thuishaven', 'Lucien Foort', 103),
    ('thuishaven', 'Steve Cop', 104),
    ('thuishaven', 'Klubbheads', 105),
    ('beyond-wonderland', 'Tiësto', 100),
    ('beyond-wonderland', 'Zedd', 101),
    ('beyond-wonderland', 'Alison Wonderland', 102),
    ('beyond-wonderland', 'Alok', 103),
    ('beyond-wonderland', 'SLANDER', 104),
    ('beyond-wonderland', 'Steve Angello', 105),
    ('beyond-wonderland', 'GRiZ', 106),
    ('beyond-wonderland', 'Dabin', 107),
    ('beyond-wonderland', 'Deorro', 108),
    ('beyond-wonderland', 'DJ Diesel', 109),
    ('beyond-wonderland', 'TroyBoi', 110),
    ('beyond-wonderland', 'Matroda', 111),
    ('beyond-wonderland', 'ATLiens', 112),
    ('beyond-wonderland', 'Black Tiger Sex Machine', 113),
    ('beyond-wonderland', 'Eptic', 114),
    ('beyond-wonderland', 'Space Laces', 115),
    ('beyond-wonderland', 'Giuseppe Ottaviani', 116),
    ('beyond-wonderland', 'Ilan Bluestone', 117),
    ('beyond-wonderland', 'Vini Vici', 118),
    ('beyond-wonderland', 'Gareth Emery', 119),
    ('dimensions', 'Bunney', 100),
    ('dimensions', 'Radioactive Man', 101),
    ('dimensions', 'Prosumer', 102),
    ('dimensions', 'DJ Storm', 103),
    ('dimensions', 'John Talabot', 104),
    ('dimensions', 'The Hacker', 105),
    ('dimensions', 'Objekt', 106),
    ('dimensions', 'Margaret Dygas', 107),
    ('dimensions', 'Jane Fitz', 108),
    ('dimensions', 'Ryan Elliott', 109),
    ('dimensions', 'Dyed Soundorom', 110),
    ('snowbombing', 'Maribou State', 100),
    ('snowbombing', 'De La Soul', 101),
    ('snowbombing', 'Orbital', 102),
    ('snowbombing', 'Hybrid Minds', 103),
    ('snowbombing', 'Sub Focus', 104),
    ('snowbombing', 'Folamour', 105),
    ('snowbombing', 'MJ Cole', 106),
    ('snowbombing', '4am Kru', 107),
    ('snowbombing', 'Horse Meat Disco', 108),
    ('dgtl', 'Joy Orbison', 100),
    ('dgtl', 'Jayda G', 101),
    ('dgtl', 'CamelPhat', 102),
    ('dgtl', 'Âme', 103),
    ('dgtl', 'DJ Tennis', 104),
    ('dgtl', 'Armand van Helden', 105),
    ('dgtl', 'Gerd Janson', 106),
    ('dgtl', 'FJAAK', 107),
    ('dgtl', 'Young Marco', 108),
    ('dgtl', 'Avalon Emerson', 109),
    ('terminal-v', 'Sara Landry', 100),
    ('terminal-v', 'SPFDJ', 101),
    ('terminal-v', 'I Hate Models', 102),
    ('terminal-v', 'Clara Cuvé', 103),
    ('terminal-v', 'Robert Hood', 104),
    ('terminal-v', 'Patrick Topping', 105),
    ('terminal-v', 'Mall Grab', 106),
    ('terminal-v', 'Klangkuenstler', 107),
    ('terminal-v', 'East End Dubs', 108),
    ('terminal-v', 'Ben Hemsley', 109),
    ('hideout', 'Alan Fitzpatrick', 100),
    ('hideout', 'Skream', 101),
    ('hideout', 'Gorgon City', 102),
    ('hideout', 'LF SYSTEM', 103),
    ('hideout', 'Danny Howard', 104),
    ('hideout', 'Partiboi69', 105),
    ('hideout', 'Ewan McVicar', 106),
    ('hideout', 'Eliza Rose', 107),
    ('hideout', 'Kettama', 108),
    ('hideout', 'Paul Woolford', 109),
    ('hideout', 'Sam Divine', 110),
    ('hideout', 'Darius Syrossian', 111)
)
insert into public.edition_artists (edition_id, artist_id, order_index)
select e.id, a.id, l.order_index
from lineup l
join public.festivals f on f.slug = l.slug
join public.festival_editions e on e.festival_id = f.id and e.year = 2026
join public.artists a on lower(a.name) = lower(l.artist_name)
on conflict (edition_id, artist_id) do nothing;
