-- AI-generated summaries of a festival's community reviews (à la
-- Google Maps). One row per festival per UI language, regenerated by
-- the summarize-reviews Edge Function whenever the review count
-- changes (review_count doubles as the cache-invalidation key).

create table public.festival_review_summaries (
  festival_id uuid not null references public.festivals (id) on delete cascade,
  language text not null check (language in ('en', 'fr', 'nl', 'de', 'es')),
  summary text not null,
  review_count int not null,
  updated_at timestamptz not null default now(),
  primary key (festival_id, language)
);

alter table public.festival_review_summaries enable row level security;

-- Public read (like reviews themselves); writes only via the service
-- role inside the Edge Function (no insert/update policies).
create policy "summaries read" on public.festival_review_summaries
  for select using (true);
